### PR TITLE
Move most static methods in FileLocator back to SIL.Core

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/629)

### CODE REVIEW

**Comment by JohnThomson** [comment]
I'd like to see more (in the issue description maybe?) about why this is appropriate.

Is there a document somewhere that attempts to describe the principles governing what goes in which of libpalaso's modules?

I've only begun to glance at this and will be out most of next week, so don't hold it up to respond to this (or wait for me to finish a review)

---

Review status: 0 of 14 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/629#-:-L6cw58Zeyzk7_dKKB67:bgcyzjd)*

**Comment by ddaspit** [comment]
Maybe I should move the FileLocator back to SIL.Core in my PR. I don't quite remember why I moved it to SIL.Core.Desktop. There must be something in it that wouldn't compile in .NET Standard. I will look at moving it back tomorrow.

**Comment by ddaspit** [comment]
I looked at FileLocator real quick. It looks like I moved it because of one method `GetFromRegistryProgramThatOpensFileType`. The method accesses the registry APIs, which is not included in .NET Standard because it is Windows-specific. Microsoft does provide NuGet packages for the registry APIs to help migrate libraries to .NET Standard, so I could move FileLocator back to SIL.Core. I was trying to avoid dependencies on these Windows-specific packages. I'm guessing you need this class to be in SIL.Core because another assembly that you want to convert to .NET Standard references it. Is that correct? If you need it, I can reference the registry package and move it back in my PR.

**Comment by andrew-polk** [comment]
> I'm guessing you need this class to be in SIL.Core because another assembly that you want to convert to .NET Standard references it. Is that correct?

Yes. I am converting the parts of Glyssen to .NET Standard 2.0 which can be moved. This is so Faith Comes By Hearing can use it in their .NET Core application they are developing.

So the move of FileLocator to SIL.Desktop was painful to deal with, as were/are Logger, ErrorReporter, and PathUtilities.

Personally, I don't need that method, so I would happy just moving it to SIL.Desktop, but if there is a solution to keep it in SIL.Core, that will likely help other clients in the future.

Thanks!

**Comment by ddaspit** [comment]
I didn't explicitly close this. It must have closed when I merged in my PR, I'm not sure why.

**Comment by ddaspit** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/629#-:-L7hpH6JirmkexApl7CC:bnfp4nl)*

**Comment by glasseyes** [comment]
I guess this will require changes to chorus master with things moving

**Comment by andrew-polk** [comment]
> I guess this will require changes to chorus master with things moving

If chorus uses SIL.Core.Desktop (which it must if it uses these methods and compiles), it won't need to make any change as all the moved methods are still there, marked obsolete.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/629#-:-L7iikMhTn_I3cpbVj2g:bv9koa4)*

**Pull request merged**
