### PR TITLE
Primary country

### PR DESCRIPTION
**Pull request by glasseyes**
This reworks PR 474 to add the PrimaryCountry field to the LanguageDataIndex.txt and LanguageDataIndex.json

It will also help keep the LanguageCodes.txt in sync with the LanguageIndex.txt from now on.

It includes a new generation of LanguageDataIndex.txt with the new field using the data currently in the repo.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/478)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Looks good...a few minor suggestions. Thanks for your patience reworking my mess. Sorry I couldn't figure out what you were getting at. I think the comments we've come up with between us will help in future.
Is it possible to attach a comment to the LanguageDataIndex property that explains what it is for and how it is generated? Being designer code, probably it would get wiped out, but I thought it worth considering.

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[LanguageData/GetAndCheckSources.cs, line 15 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5gm1TM7hFJbjZprz3:-Ki5gm1TM7hFJbjZprz4:b-txtnpo) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/GetAndCheckSources.cs#L15)):*
> ```Smalltalk
> namespace LanguageData
> {
> 	public class GetAndCheckSources
> ```

While you are working on this class, could you give it a class comment that describes more fully its purpose, use and responsibility?
In particular, since I'm inferring that it is used to get some kind of source data on which our language data tables are built, it would be helpful to know
- how is it invoked? Part of every run of every client app, part of every build of libpalaso, or run by some manual process when someone chooses to update sources?
- what IS the source for this data that it gets and checks? How often does it change, and how often should this consequently be run (if it's manual)?

---

*[LanguageData/LanguageDataIndex.cs, line 16 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5oDNE3dNZ-6CX9__z:-Ki5oDNE3dNZ-6CX9_a-:bolh0o6) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/LanguageDataIndex.cs#L16)):*
> ```Smalltalk
> 	/// <summary>
> 	/// Generates LanguageDataIndex.txt using data from the Ethnologue, IANA subtag repository and the SLDR.
> 	/// This is used to populate SIL.WritingSystems.LanguageLookup for searching
> ```

A missing step here is worth a mention, I think... "LanguageDataIndex.txt (becomes/is?) the value of the resource LanguageRegistryResources.LanguageDataIndex and is used to populate...."
Is there anything that has to be done besides running LanguageData to cause the actual resource to be updated so the new data will be used? If so I think it would be worth mentioning here.

---

*[LanguageData/LanguageDataIndex.cs, line 291 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5iegSFr5lTxr-OUa3:-Ki5iegT6lLhJw4m6Vzt:bc8hmq4) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/LanguageDataIndex.cs#L291)):*
> ```Smalltalk
> 						if (String.IsNullOrEmpty(languageInfo.PrimaryCountry) && languageInfo.Countries.Count == 1)
> 						{
> 							languageInfo.PrimaryCountry = languageInfo.Countries.First();
> ```

As I discovered while working on an earlier version, there are about 30 languages (including qaa) where the one country has name "?". I don't think that is useful to record as a PrimaryCountry value, so it would probably be good to filter them out here.

---

*[LanguageData.Tests/GetAndCheckSourcesTests.cs, line 68 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5jAiRSBjbtTDGFY3N:-Ki5jAiRSBjbtTDGFY3O:b-dke2xr) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData.Tests/GetAndCheckSourcesTests.cs#L68)):*
> ```Smalltalk
> 			File.WriteAllText(filename, "33333333333333333333333333333333333333333333333333333333333333333");
> 			filename = Path.Combine(".", "LanguageCodes.txt");
> 			File.WriteAllText(filename, "44444444444444444444444444444444444444444444444444444444444444444");
> ```

These seem very odd filenames...you're obviously following a pattern but if there's a reason for it I'd like to see it documented.

---

*[SIL.WritingSystems/LanguageInfo.cs, line 6 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5pZz5LKGcl3BpZtAR:-Ki5pZz5LKGcl3BpZtAS:b-7wnj2h) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems/LanguageInfo.cs#L6)):*
> ```Smalltalk
> namespace SIL.WritingSystems
> {
> 	public class LanguageInfo
> ```

While you're improving things in this area, how about a class comment here?
Like me, someone who wants something new in LanguageInfo objects is probably going to start HERE trying to get it added, because this is the class from which you get those objects. So it's a good place to document as much as possible of the related code and process that should be used to add anything.

---

*[SIL.WritingSystems/LanguageLookup.cs, line 14 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5jWYnGT6L-hirvS8K:-Ki5jWYnGT6L-hirvS8L:b-912ab4) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems/LanguageLookup.cs#L14)):*
> ```Smalltalk
> 	/// <summary>
> 	/// Lets you find a language using data from the Ethnologue, IANA subtag repository and the SLDR.
> 	/// It obtains the data from LanguageDataIndex.txt which has been generated by the LanguageData program
> ```

This is a very helpful addition but I'd like to see even more, to save someone making the same sort of mistake that I did.
I'd suggest adding something like, "We want to keep all fields in LanguageInfo corresponding to columns in LanguageDataIndex.txt and fields in LanguageDataIndex.json
which are generated by code in the LanguageDataIndex constructor from information retrieved from ethnologue.com by code in GetAndCheckSources when the LanguageData program is run. (One reason is so it will also be available to web apps using the json file.)
So, any new information that the code here needs to initialize in LanguageInfo objects should not be computed here, but computed or retrieved from the ethnologue in LanguageDataIndex(), added to LanguageDataIndex.txt and .json, and then simply read into the appropriate fields here.

---

*[SIL.WritingSystems/LanguageLookup.cs, line 71 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5l_ZgwCPNnucGWcok:-Ki5l_ZgwCPNnucGWcol:b-fk089e) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems/LanguageLookup.cs#L71)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		///  For testing; used to detect if we need more special cases in LanguageInfo.PrimaryCountry.
> ```

The special cases are now in the LanguageDataIndex constructor

---

*[SIL.WritingSystems.Tests/LanguageLookupTests.cs, line 104 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5looaxEyPxRXOck0s:-Ki5looaxEyPxRXOck0t:b-6ezc9v) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems.Tests/LanguageLookupTests.cs#L104)):*
> ```Smalltalk
> 		[TestCase("xak", "Venezuela")] // two special cases, the countries without regions and with >1 country
> 		[TestCase("itd", "Indonesia")]
> 		[TestCase("qaa", "?")] // a special case
> ```

I think a simple empty string would be a better indication that we don't know a country for this language. I don't know for sure, but there may well be some that don't have anything, so why make clients check two different things to detect 'unknown'?

---

*[SIL.WritingSystems.Tests/LanguageLookupTests.cs, line 120 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5mG2CEoiXI2Z65gUi:-Ki5mG2CEoiXI2Z65gUj:b8a1fgj) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems.Tests/LanguageLookupTests.cs#L120)):*
> ```Smalltalk
> 		/// </summary>
> 		[Test]
> 		public void AllExpectedLanguagesHaveUniquePrimaryCountries()
> ```

This may well be worth keeping, but I wonder whether the check should be done and results reported as part of running LanguageData?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-:-Ki5maNP7CFxCA4ZRbdG:baryw54)*

**Comment by glasseyes** [comment]
Thanks for your patience too. I've added comments to the LanguageRegistryResources.resx resource which will persist as well as to the designer file that could be overwritten at some point

(this is incomplete and the 'done' parts aren't pushed yet)

---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[LanguageData/GetAndCheckSources.cs, line 15 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5gm1TM7hFJbjZprz3:-KiEMWfJ68P-rxDpiyVD:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/GetAndCheckSources.cs#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

While you are working on this class, could you give it a class comment that describes more fully its purpose, use and responsibility?
In particular, since I'm inferring that it is used to get some kind of source data on which our language data tables are built, it would be helpful to know
- how is it invoked? Part of every run of every client app, part of every build of libpalaso, or run by some manual process when someone chooses to update sources?
- what IS the source for this data that it gets and checks? How often does it change, and how often should this consequently be run (if it's manual)?
</blockquote></details>

Done.

---

*[LanguageData/LanguageDataIndex.cs, line 16 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5oDNE3dNZ-6CX9__z:-KiEvjaXTLOVrLes41BO:bsozqkv) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/LanguageDataIndex.cs#L16)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

A missing step here is worth a mention, I think... "LanguageDataIndex.txt (becomes/is?) the value of the resource LanguageRegistryResources.LanguageDataIndex and is used to populate...."
Is there anything that has to be done besides running LanguageData to cause the actual resource to be updated so the new data will be used? If so I think it would be worth mentioning here.
</blockquote></details>

I've added links to the wiki which I'll update once I finalise the new process in the "Language List automation/consumption by libpalaso" trello card

---

*[LanguageData/LanguageDataIndex.cs, line 291 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5iegSFr5lTxr-OUa3:-KiEw78KKKMGMqs7LWZ_:b-c4v1uu) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/LanguageDataIndex.cs#L291)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As I discovered while working on an earlier version, there are about 30 languages (including qaa) where the one country has name "?". I don't think that is useful to record as a PrimaryCountry value, so it would probably be good to filter them out here.
</blockquote></details>

the qaa '?' seems to be deliberate, and the others are good pointers to places to fix so I'm currently inclined to leave them

---

*[LanguageData.Tests/GetAndCheckSourcesTests.cs, line 68 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5jAiRSBjbtTDGFY3N:-KiEM0vO3u1a8L9hgY0W:bw4lg73) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData.Tests/GetAndCheckSourcesTests.cs#L68)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

These seem very odd filenames...you're obviously following a pattern but if there's a reason for it I'd like to see it documented.
</blockquote></details>

these files already existed in SIL.WritingSystems/Resources so that is all I'm using

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-:-KiEMZP8g2aCjPuQjNrm:b13gx2k)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[LanguageData/LanguageDataIndex.cs, line 291 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5iegSFr5lTxr-OUa3:-KiFtAep5QcZebtpRJqY:behc78y) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/LanguageDataIndex.cs#L291)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

the qaa '?' seems to be deliberate, and the others are good pointers to places to fix so I'm currently inclined to leave them
</blockquote></details>

It's hard to imagine what someone might be hoping to find by typing a question mark into a search box for a language, but we should be thinking here of what will help our end users, not what will document something for us to fix later. I ran the original decision past @hatton and he also thought dropping them was wise, but I don't know his exact reasoning. Are there ones where country is simply missing or blank? Is question mark meant to mean something different?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/478)*

**Comment by glasseyes** [comment]
Review status: 2 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[LanguageData/LanguageDataIndex.cs, line 291 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5iegSFr5lTxr-OUa3:-KiTK4u84o7LM37-__Z2:b-ht1a38) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/LanguageData/LanguageDataIndex.cs#L291)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's hard to imagine what someone might be hoping to find by typing a question mark into a search box for a language, but we should be thinking here of what will help our end users, not what will document something for us to fix later. I ran the original decision past @hatton and he also thought dropping them was wise, but I don't know his exact reasoning. Are there ones where country is simply missing or blank? Is question mark meant to mean something different?
</blockquote></details>

OK, done (apart from the unknown language) - they are all for the tag-Script type tags 

---

*[SIL.WritingSystems/LanguageInfo.cs, line 6 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5pZz5LKGcl3BpZtAR:-KiYH9zMU6vK3UPihjyh:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems/LanguageInfo.cs#L6)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

While you're improving things in this area, how about a class comment here?
Like me, someone who wants something new in LanguageInfo objects is probably going to start HERE trying to get it added, because this is the class from which you get those objects. So it's a good place to document as much as possible of the related code and process that should be used to add anything.
</blockquote></details>

Done.

---

*[SIL.WritingSystems/LanguageLookup.cs, line 14 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5jWYnGT6L-hirvS8K:-KiYJFKRdhQYrQGDKwf5:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems/LanguageLookup.cs#L14)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is a very helpful addition but I'd like to see even more, to save someone making the same sort of mistake that I did.
I'd suggest adding something like, "We want to keep all fields in LanguageInfo corresponding to columns in LanguageDataIndex.txt and fields in LanguageDataIndex.json
which are generated by code in the LanguageDataIndex constructor from information retrieved from ethnologue.com by code in GetAndCheckSources when the LanguageData program is run. (One reason is so it will also be available to web apps using the json file.)
So, any new information that the code here needs to initialize in LanguageInfo objects should not be computed here, but computed or retrieved from the ethnologue in LanguageDataIndex(), added to LanguageDataIndex.txt and .json, and then simply read into the appropriate fields here.
</blockquote></details>

Done.

---

*[SIL.WritingSystems/LanguageLookup.cs, line 71 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5l_ZgwCPNnucGWcok:-KiYJknxH6g9GQ5Kbqs9:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems/LanguageLookup.cs#L71)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

The special cases are now in the LanguageDataIndex constructor
</blockquote></details>

Done.

---

*[SIL.WritingSystems.Tests/LanguageLookupTests.cs, line 104 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5looaxEyPxRXOck0s:-KiZPXtTXs9daYHZCl2U:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems.Tests/LanguageLookupTests.cs#L104)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think a simple empty string would be a better indication that we don't know a country for this language. I don't know for sure, but there may well be some that don't have anything, so why make clients check two different things to detect 'unknown'?
</blockquote></details>

Done.

---

*[SIL.WritingSystems.Tests/LanguageLookupTests.cs, line 120 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5mG2CEoiXI2Z65gUi:-KiZ7r5I_WWe7LRuFy2a:btukmh2) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems.Tests/LanguageLookupTests.cs#L120)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This may well be worth keeping, but I wonder whether the check should be done and results reported as part of running LanguageData?
</blockquote></details>

Currently all the tests related to the LanguageDataIndex data are in LanguageLookupTests so I think it is worth keeping it there.

I'm adding console output in LanguageDataIndex.cs with that same code to say which languages it is that don't have countries

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/478)*

**Comment by JohnThomson** [comment]
:lgtm: Nice work, thanks for your patience.

---

Reviewed 1 of 10 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[SIL.WritingSystems/LanguageInfo.cs, line 6 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-Ki5pZz5LKGcl3BpZtAR:-Ki_ITpLu2R1YuUNCqOJ:btojbfd) ([raw file](https://github.com/sillsdev/libpalaso/blob/4eb80b29d86c296697b1fa906bdc9dfdad44210d/SIL.WritingSystems/LanguageInfo.cs#L6)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/478#-:-Ki_JMCAXQdza4Ad0nwB:b7q6slh)*

**Pull request merged**
