### PR TITLE
Nugetification of libpalaso-2.6

### PR DESCRIPTION
**Pull request by glasseyes**
get NAudio, Commons.Xml.RelaxNG, Moq, Rhino.Mocks from nuget
all closest versions to what is currently in the repo

upgrade Commons.Xml.RelaxNG to 3.2.3 from 2.0.0
upgrade Rhino.Mocks to 3.6.1 from 3.5
upgrade Moq from 4.0.812 to 4.0.10827
upgrade icu.net to 2.2.0
don't include dbus or ibus project targets in windows builds nor icu dlls in linux builds

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/584)

### CODE REVIEW

**Comment by glasseyes** [comment]
there is no 2.6 windows build reporting to github so this won't pass on the other branches

**Comment by ermshiperete** [comment]
Reviewed 35 of 35 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj, line 132 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/584#-KwieSVDJCDqQfsURD8D:-KwieSVDJCDqQfsURD8E:b-84y25g) ([raw file](https://github.com/sillsdev/libpalaso/blob/2cb0ebc34cf71946c273b6795e2c4f0e0e22c60c/PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj#L132)):*
> ```XML
>       <HintPath>..\lib\commonMono\ibusdotnet.dll</HintPath>
>     </Reference>
>     <Reference Include="NDesk.DBus">
> ```

I think we still needs NDesk.DBus because ibusdotnet depends on it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/584)*

**Comment by glasseyes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj, line 132 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/584#-KwieSVDJCDqQfsURD8D:-KwivQDeai5kBUbXwjyE:b7vyi9a) ([raw file](https://github.com/sillsdev/libpalaso/blob/2cb0ebc34cf71946c273b6795e2c4f0e0e22c60c/PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj#L132)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I think we still needs NDesk.DBus because ibusdotnet depends on it.
</blockquote></details>

Thanks, I didn't realise that as there was no dependency in the nuget package. Will fix that tomorrow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/584)*

**Comment by jasonleenaylor** [comment]
*[PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj, line 132 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/584#-KwieSVDJCDqQfsURD8D:-KwjbyeJAhN0H3kv8S5c:b5njxeh) ([raw file](https://github.com/sillsdev/libpalaso/blob/2cb0ebc34cf71946c273b6795e2c4f0e0e22c60c/PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj#L132)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

Thanks, I didn't realise that as there was no dependency in the nuget package. Will fix that tomorrow
</blockquote></details>

Also of note, we use the NDesk.DBus that is built off of Tom Hindle's fork.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/584)*

**Comment by glasseyes** [comment]
Review status: 33 of 35 files reviewed at latest revision, 1 unresolved discussion.

---

*[PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj, line 132 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/584#-KwieSVDJCDqQfsURD8D:-KwmUn01U8mMAeHWB7PC:b14pmt1) ([raw file](https://github.com/sillsdev/libpalaso/blob/2cb0ebc34cf71946c273b6795e2c4f0e0e22c60c/PalasoUIWindowsForms.Tests/PalasoUIWindowsForms.Tests.csproj#L132)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Also of note, we use the NDesk.DBus that is built off of Tom Hindle's fork.
</blockquote></details>

Yep, the public nuget package is managed by TH and EB
And done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/584)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/584#-:-KwnZJTACA25U2rJRXax:bnfp4nl)*

**Pull request merged**
