### PR TITLE
Improvements for UI locale menu strings

### PR DESCRIPTION
**Pull request by tombogle**
Added common UI string for More menu.
Improved logic in IetfLanguageTag to get better results for zh-TW

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1171)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1171)* status: all files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`SIL.Windows.Forms.WritingSystems/Extensions.cs` line 83 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1171#-N3Vxxvs6thAVjqO8yWu:-N3Vxxvs6thAVjqO8yWv:b-scql4) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca80c574118b548c796aced66374ae67a40987c/SIL.Windows.Forms.WritingSystems/Extensions.cs#L83)):*
> ```Smalltalk
> 
> 		public static string MoreLanguagesMenuText => LocalizationManager.GetString("Common.MoreMenuItem",
> 			"&More...", "Last item in menu of UI languages, used to open localization dialog box");
> ```

Maybe there's no better place to put this, but technically it isn't an extension, of course.
___
*[`SIL.Windows.Forms.WritingSystems/Extensions.cs` line 83 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1171#-N3VyujNBdIw-ib3P8Lx:-N3VyujNBdIw-ib3P8Ly:bjg291p) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca80c574118b548c796aced66374ae67a40987c/SIL.Windows.Forms.WritingSystems/Extensions.cs#L83)):*
> ```Smalltalk
> 
> 		public static string MoreLanguagesMenuText => LocalizationManager.GetString("Common.MoreMenuItem",
> 			"&More...", "Last item in menu of UI languages, used to open localization dialog box");
> ```

I'm out of touch with the l10n story for libpalaso these days. Should this get added to one or more .xlf files?

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms.WritingSystems/Extensions.cs` line 83 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1171#-N3Vxxvs6thAVjqO8yWu:-N3ZM1Yw5Xn5MHlqqT9Z:b-4kwu3r) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca80c574118b548c796aced66374ae67a40987c/SIL.Windows.Forms.WritingSystems/Extensions.cs#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe there's no better place to put this, but technically it isn't an extension, of course.
</blockquote></details>

Good point. I'll look for a more appropriate place. When I added it originally, it was going to be part of (or a companion to) an extension method. But then I moved that into L10nSharp. (And then I punted...)

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms.WritingSystems/Extensions.cs` line 83 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1171#-N3VyujNBdIw-ib3P8Lx:-N3ZMLXCAs2CeJHi9xqi:b2nhswy) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca80c574118b548c796aced66374ae67a40987c/SIL.Windows.Forms.WritingSystems/Extensions.cs#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm out of touch with the l10n story for libpalaso these days. Should this get added to one or more .xlf files?
</blockquote></details>

Yes

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms.WritingSystems/Extensions.cs` line 83 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1171#-N3VyujNBdIw-ib3P8Lx:-N3ZhB22BKphPQh7zcns:bwtc4kv) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca80c574118b548c796aced66374ae67a40987c/SIL.Windows.Forms.WritingSystems/Extensions.cs#L83)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

No, looking more closely, I guess any new strings should just be included in Crowdin when it is updated, and then any app that uses that string needs to get the updated localizations that it cares about.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms.WritingSystems/Extensions.cs` line 83 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1171#-N3Vxxvs6thAVjqO8yWu:-N3_m6tt9ni8-xo9cbdA:bt639cg) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca80c574118b548c796aced66374ae67a40987c/SIL.Windows.Forms.WritingSystems/Extensions.cs#L83)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Good point. I'll look for a more appropriate place. When I added it originally, it was going to be part of (or a companion to) an extension method. But then I moved that into L10nSharp. (And then I punted...)
</blockquote></details>

I decided to go with something closer to "plan A" for the time being

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms.WritingSystems/Extensions.cs` line 83 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1171#-N3VyujNBdIw-ib3P8Lx:-N3bN7TB0n7muGg3aHHg:b-w62e4a) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca80c574118b548c796aced66374ae67a40987c/SIL.Windows.Forms.WritingSystems/Extensions.cs#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ok, I'll trust you that Crowdin somehow gets the new source string without it being added to the English xlf.
</blockquote></details>

The checked in English xliff file is just for testing. The real one gets generated form the extraction process.

**Pull request merged**
