### PR TITLE
Reorder image fetching for GetImageFromClipboard to try PNG first

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This can help preserve transparency in copied images.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1344)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[`SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1344#-O5Pi9YV385ldfroI9Br:-O5Pi9YWCWoZCu-QxTuw:bowvl3) ([raw file](https://github.com/sillsdev/libpalaso/blob/9bf7b61e8d3490310212b1a6fce41d8afcd7f148/SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs#L63)):*
> ```Smalltalk
> 			if (dataObject == null)
> 				return null;
> 			Exception ex = null;
> ```

Not your fault, but it looks like there is no use for this variable.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1344)* status: 1 of 2 files reviewed, all discussions resolved

___
*[`SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs` line 81 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1344#-O5PiKa07VxmfpLVI1iB:-O5PiKa07VxmfpLVI1iC:b6zgrye) ([raw file](https://github.com/sillsdev/libpalaso/blob/9bf7b61e8d3490310212b1a6fce41d8afcd7f148/SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs#L81)):*
> ```Smalltalk
> 				catch (Exception e)
> 				{
> 					ex = e;
> ```

if the variable is removed a comment here explaining that we are intentionally ignoring it and falling back to other options would be good

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1344)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1344#-O5Pi9YV385ldfroI9Br:-O5Pi_WD9tdaUgLqkySv:b-mzqtly) ([raw file](https://github.com/sillsdev/libpalaso/blob/9bf7b61e8d3490310212b1a6fce41d8afcd7f148/SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs#L63)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Not your fault, but it looks like there is no use for this variable.
</blockquote></details>

That's not quite true.  At the end of the method, if an image is not returned, and the ex variable is not null, then the method (re)throws ex instead of returning null.  But that's certainly not obvious from the default snippets shown by the reviewing tool.  And I'll admit it's a marginal use.  But it is a use.  :-)

**Comment by jasonleenaylor** [comment]
*[`SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs` line 63 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1344#-O5Pi9YV385ldfroI9Br:-O5Pr8qO81PcVSftkA4s:b-lkhy94) ([raw file](https://github.com/sillsdev/libpalaso/blob/9bf7b61e8d3490310212b1a6fce41d8afcd7f148/SIL.Windows.Forms/Clipboarding/WindowsClipboard.cs#L63)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

That's not quite true.  At the end of the method, if an image is not returned, and the ex variable is not null, then the method (re)throws ex instead of returning null.  But that's certainly not obvious from the default snippets shown by the reviewing tool.  And I'll admit it's a marginal use.  But it is a use.  :-)
</blockquote></details>

Ah, I didn't expand far enough. :smile:

**Review by jasonleenaylor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1344#-:-O5PrHJn6SeQ0YqHNgCH:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
