### PR TITLE
Internationalization and layout fixes in exception/problem reporting dialogs

### PR DESCRIPTION
**Pull request by tombogle**
Internationalized the ExceptionReportingDialog
Also used LocalizationManager for the caption for the ProblemNotificationDialog.
Fixed layout issues in ExceptionReportingDialog to prevent overlapping text.
Fixed handling of \n in message text so that it lays out correctly in the ProblemNotificationDialog (because strings returned from L10NSharp typically don't have the \r)
[WIP] Could not figure out how to re-extract the strings to update the XLF files.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1148)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1148)* status: all files reviewed, 3 unresolved discussions (waiting on @ermshiperete and @tombogle)

___
*[SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs, line 917 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-Mz17f-H7ZpSLax_qz1T:-Mz17f-H7ZpSLax_qz1U:b-7pzrp0) ([raw file](https://github.com/sillsdev/libpalaso/blob/fdb6a0848ef2bbe5e121d0b882ff307f40e9413e/SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs#L917)):*
> ```Smalltalk
> 		/// <summary>
> 		/// Although this is public and can be set externally for an application that has a custom
> 		/// policy (e.e., does not use Jira), be aware that if you want it to localized, you will
> ```

i.e.?



_Code quote:_
```Smalltalk
e.e.
```
___
*[SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs, line 917 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-Mz17h_W1Z09GmG09FYy:-Mz17h_W1Z09GmG09FYz:b-g04bg2) ([raw file](https://github.com/sillsdev/libpalaso/blob/fdb6a0848ef2bbe5e121d0b882ff307f40e9413e/SIL.Windows.Forms/Reporting/ExceptionReportingDialog.cs#L917)):*
> ```Smalltalk
> 		/// <summary>
> 		/// Although this is public and can be set externally for an application that has a custom
> 		/// policy (e.e., does not use Jira), be aware that if you want it to localized, you will
> ```

to get localized?



_Code quote:_
```Smalltalk
to localized
```
___
*[SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs, line 46 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-Mz16SYOB7j1-OXHJQo7:-Mz16SYOB7j1-OXHJQo8:b-864obf) ([raw file](https://github.com/sillsdev/libpalaso/blob/fdb6a0848ef2bbe5e121d0b882ff307f40e9413e/SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs#L46)):*
> ```Smalltalk
> 		{
> 			using (var d = new ProblemNotificationDialog(message,
> 				LocalizationManager.GetString("ProblemNotificationDialog.Caption", "Problem")))
> ```

I thought your plan was to wrap such calls in a try/catch or something else to guarantee we never get an exception.

Similarly, I thought you were not planning to use the extender.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1148)* status: all files reviewed, 1 unresolved discussion (waiting on @ermshiperete and @tombogle)

___
*[SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs, line 56 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-MzHF0bfDOzLKBbys0lp:-MzHF0bfDOzLKBbys0lq:b-aoe892) ([raw file](https://github.com/sillsdev/libpalaso/blob/43bf07f6aca90b8a2d2c77ed2e5e92f940de3558/SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs#L56)):*
> ```Smalltalk
> 				try { Logger.WriteError(e); } catch { /* We tried. */ }
> 				caption = "Problem";
> 			}
> ```

Seems like it might be worth a little utility method maybe even an extension method.
"Problem".LocalizeSafely("ProblemNotificationDialog.Caption")

**Comment by tombogle** [comment]
___
*[SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs, line 56 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-MzHF0bfDOzLKBbys0lp:-MzHILzS9bbFLem7NUcE:b-it0xpv) ([raw file](https://github.com/sillsdev/libpalaso/blob/43bf07f6aca90b8a2d2c77ed2e5e92f940de3558/SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs#L56)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Seems like it might be worth a little utility method maybe even an extension method.
"Problem".LocalizeSafely("ProblemNotificationDialog.Caption")
</blockquote></details>

Certainly considered that. The problem is that in order for ExtractXliff to find the strings, they need to have LocalizationManager.GetString(<literal id>, <literal English string>...
It is possible to tell ExtractXliff about other signatures, but it complicates things.
I did consider using an enumeration, but it didn't feel like it would make things a whole lot better. The other option is to use GetDynamicString, but that also complicates the extraction, basically turning it into a manual process, and these strings are not really "dynamic" in that sense.
The most appealing option was to actually make "fail-safe" overloads in L10nSharp itself to  handle this, but that felt like a fair bit of extra work for this one situation, and more importantly it wouldn't address the very real problem of a missing L10nSharp DLL (or one with an incompatible version). Of course, we'd like to hope that could never happen in a real-life installation, but then we'd like to hope that no fatal error could ever happen!

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete)

___
*[SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs, line 56 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-MzHF0bfDOzLKBbys0lp:-MzHPVlJ6PGq3LNE7i41:b-c3tlw3) ([raw file](https://github.com/sillsdev/libpalaso/blob/43bf07f6aca90b8a2d2c77ed2e5e92f940de3558/SIL.Windows.Forms/Reporting/ProblemNotificationDialog.cs#L56)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Certainly considered that. The problem is that in order for ExtractXliff to find the strings, they need to have LocalizationManager.GetString(<literal id>, <literal English string>...
It is possible to tell ExtractXliff about other signatures, but it complicates things.
I did consider using an enumeration, but it didn't feel like it would make things a whole lot better. The other option is to use GetDynamicString, but that also complicates the extraction, basically turning it into a manual process, and these strings are not really "dynamic" in that sense.
The most appealing option was to actually make "fail-safe" overloads in L10nSharp itself to  handle this, but that felt like a fair bit of extra work for this one situation, and more importantly it wouldn't address the very real problem of a missing L10nSharp DLL (or one with an incompatible version). Of course, we'd like to hope that could never happen in a real-life installation, but then we'd like to hope that no fatal error could ever happen!
</blockquote></details>

Good points.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1148)* status: all files reviewed, 1 unresolved discussion (waiting on @ermshiperete and @tombogle)

___
*[DistFiles/Palaso.en.xlf, line 1 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-MzM5BbP6rkNjpZIsTLa:-MzM5BbP6rkNjpZIsTLb:biifvg) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca7d7447f2ec3614c3ce0f8768a276cedec541e/DistFiles/Palaso.en.xlf#L1)):*
> ```XML
> <?xml version="1.0" encoding="utf-8"?>
> ```

Why are we adding .xlf files now when we never have previously?

**Comment by tombogle** [comment]
___
*[DistFiles/Palaso.en.xlf, line 1 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-MzM5BbP6rkNjpZIsTLa:-MzM5mA-7uRIbfKsp6cP:b5e8lys) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca7d7447f2ec3614c3ce0f8768a276cedec541e/DistFiles/Palaso.en.xlf#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Why are we adding .xlf files now when we never have previously?
</blockquote></details>

Just to allow the TestApp to be able to use either one. Technically not required, of course, since the main purpose of tis is not to text L10nSharp, but rather to test libpalaso DLLs. But a) I had the new strings for the ExceptionReportingDialog in Spanish in the xliff format and I was too lazy to manually copy/convert them to TMX, and b) at some point, TMX is likely to get phased out anyway, and all the new work (e.g., new string translations in Crowdin) is likely to target xliff.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete)

___
*[DistFiles/Palaso.en.xlf, line 1 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1148#-MzM5BbP6rkNjpZIsTLa:-MzMF_6h1lANWuDKSpdv:ba8xjtl) ([raw file](https://github.com/sillsdev/libpalaso/blob/6ca7d7447f2ec3614c3ce0f8768a276cedec541e/DistFiles/Palaso.en.xlf#L1)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Just to allow the TestApp to be able to use either one. Technically not required, of course, since the main purpose of tis is not to text L10nSharp, but rather to test libpalaso DLLs. But a) I had the new strings for the ExceptionReportingDialog in Spanish in the xliff format and I was too lazy to manually copy/convert them to TMX, and b) at some point, TMX is likely to get phased out anyway, and all the new work (e.g., new string translations in Crowdin) is likely to target xliff.
</blockquote></details>

Ah. I wasn't realizing that the .tmx versions were committed.

**Pull request merged**
