### PR TITLE
Move Interop.WIA.x64.dll to x64/Interop.WIA.dll

### PR DESCRIPTION
**Pull request by papeh**
FieldWorks can't find it with the different name.
needed for https://jira.sil.org/browse/LT-21444

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1262)

### CODE REVIEW

**Comment by papeh** [comment]
Moving the DLL is technically breaking, but I'm unaware of any working clients since this DLL was introduced yesterday.

Changing the .targets isn't breaking since the Excluded files didn't exist before.

The other option I considered is packing `build64/Interop.WIA.dll`; this would not require updating the .targets file.

**Review by jasonleenaylor — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1262)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @papeh)

___
*[`SIL.Windows.Forms/SIL.Windows.Forms.csproj` line 35 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1262#-NZ22MPj5HeEgvdLm8pz:-NZ22MPj5HeEgvdLm8q-:b-4sdep8) ([raw file](https://github.com/sillsdev/libpalaso/blob/6650d967e6d972de71f419cadf279002880fe194/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L35)):*
> ```XML
> 
>   <ItemGroup>
>     <Reference Include="Interop.WIA">
> ```

Alternatively we could add a reference to the Interop.WIA.x64.dll here right?

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1262)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`SIL.Windows.Forms/SIL.Windows.Forms.csproj` line 35 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1262#-NZ22MPj5HeEgvdLm8pz:-NZ2XiO85GIRI5JrLGi8:b-n16ek8) ([raw file](https://github.com/sillsdev/libpalaso/blob/6650d967e6d972de71f419cadf279002880fe194/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L35)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Alternatively we could add a reference to the Interop.WIA.x64.dll here right?
</blockquote></details>

I can't get that to work.

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1262)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[`SIL.Windows.Forms/SIL.Windows.Forms.csproj` line 35 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1262#-NZ22MPj5HeEgvdLm8pz:-NZ2b7k79TS_JU5IRqrB:b-omxtf6) ([raw file](https://github.com/sillsdev/libpalaso/blob/6650d967e6d972de71f419cadf279002880fe194/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L35)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I can't get that to work.
</blockquote></details>

I've tried:
* removing the hint path (no change)
* changing the hint path to the .x64.dll (Palaso test app crashes loading the dialog)
* duplicating the hint path (Palaso test app crashes loading the dialog)
* duplicating the reference `<Reference include "Interop.WIA.x64` (no change)

**Review by jasonleenaylor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1262)* status: 1 of 3 files reviewed, all discussions resolved

___
*[`SIL.Windows.Forms/SIL.Windows.Forms.csproj` line 35 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1262#-NZ22MPj5HeEgvdLm8pz:-NZ2iVmW0X80h1BmJ4gi:b-xw2tzm) ([raw file](https://github.com/sillsdev/libpalaso/blob/6650d967e6d972de71f419cadf279002880fe194/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L35)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I've tried:
* removing the hint path (no change)
* changing the hint path to the .x64.dll (Palaso test app crashes loading the dialog)
* duplicating the hint path (Palaso test app crashes loading the dialog)
* duplicating the reference `<Reference include "Interop.WIA.x64` (no change)

</blockquote></details>

That's too bad, I'm guessing that it ends up picking one at build time and throwing out the other since they both provide the same references.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1262)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Pull request merged**
