### PR TITLE
Stop clearing script on ipa selection

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Addresses part of LT-20348

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/968)

### CODE REVIEW

**Review by ermshiperete — APPROVED** [review]

**Review by papeh — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/968)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs, line 1649 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/968#-MGJdTy909XKyu8aDvuZ:-MGJdTy909XKyu8aDvu_:bllud72) ([raw file](https://github.com/sillsdev/libpalaso/blob/177be2d5831873eb616e4dfcbaaa3224d0d6e196/SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs#L1649)):*
> ```Smalltalk
> 		{
> 			CurrentIsVoice = false;
> 			CurrentScriptCode = string.Empty;
> ```

if the user selects IPA in the course of editing, and the script is not dropped until later, the user may be confused.

**Comment by jasonleenaylor** [comment]
___
*[SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs, line 1649 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/968#-MGJdTy909XKyu8aDvuZ:-MGJuvXz7D7BjMWfDTba:b-jj5vfm) ([raw file](https://github.com/sillsdev/libpalaso/blob/177be2d5831873eb616e4dfcbaaa3224d0d6e196/SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs#L1649)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

if the user selects IPA in the course of editing, and the script is not dropped until later, the user may be confused.
</blockquote></details>

Your right Hasso, and after our conversation your suggestion for avoiding the bug is a better fix.

**Review by papeh — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/968#-:-MGK8SpCDldvEL5I6tWV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @papeh)

___
*[SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs, line 1668 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/968#-MGK86kW5YOWObjnc2_X:-MGK86kXA1VnHiCYb8ad:bf7xs4j) ([raw file](https://github.com/sillsdev/libpalaso/blob/79744331d1b0afac06aa20b098010176572e1587/SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs#L1668)):*
> ```Smalltalk
> 				CurrentScriptCode = CurrentDefinition.Script;
> 				CurrentIsVoice = CurrentDefinition.IsVoice;
> 				CurrentIpaStatus = IpaStatusChoices.NotIpa;
> ```

Does this silently clear the option on load?

**Comment by jasonleenaylor** [comment]
___
*[SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs, line 1668 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/968#-MGK86kW5YOWObjnc2_X:-MGKLjzS-Jxq7BySWbfd:b-u1aj9y) ([raw file](https://github.com/sillsdev/libpalaso/blob/79744331d1b0afac06aa20b098010176572e1587/SIL.Windows.Forms.WritingSystems/WritingSystemSetupModel.cs#L1668)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Does this silently clear the option on load?
</blockquote></details>

oops, how did that get back in there? :grimacing:

**Review by papeh — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/968)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
