### PR TITLE
HT-431: Added overload of SerializeToFileWithWriteThrough to simplify error handling

### PR DESCRIPTION
**Pull request by tombogle**
Also fixed a few spelling errors in comments

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1166)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1166)* status: all files reviewed, 2 unresolved discussions (waiting on @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[`CHANGELOG.md` line 43 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1166#-N2DBOX5CHqNRRCqIlwy:-N2DBOX5CHqNRRCqIlwz:b-gcffgc) ([raw file](https://github.com/sillsdev/libpalaso/blob/6f4b930a463d5e1e88aa0b9341ddc14f623f5922/CHANGELOG.md#L43)):*
> ```Markdown
>   (It is acceptable for implementers to just fill some parameters then call the original method)
>   `ConsoleErrorReporter` and `WinFormsErrorReporter` implement `IErrorReporter`'s new interface method
> - [SIL.Core] Added override of SerializeToFileWithWriteThrough to simplify error handling.
> ```

If we're doing strict semver, I think needs a semver:minor in the commit message.
___
*[`SIL.Core.Tests/Xml/XmlSerializationHelperTests.cs` line 496 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1166#-N2DAXNp3atYAzBTE-fY:-N2DAXNp3atYAzBTE-fZ:b-tqr2rf) ([raw file](https://github.com/sillsdev/libpalaso/blob/6f4b930a463d5e1e88aa0b9341ddc14f623f5922/SIL.Core.Tests/Xml/XmlSerializationHelperTests.cs#L496)):*
> ```Smalltalk
> 				RobustFile.Delete(path);
> 			}
> 		}
> ```

Should these new test methods be named with `SerializeToFileWithWriteThrough`?
(I'm guessing you changed your name about the name at some point.)



_Code quote:_
```Smalltalk
SerializeToFileWithWriteThrough
```

**Comment by tombogle** [comment]
*[`SIL.Core.Tests/Xml/XmlSerializationHelperTests.cs` line 496 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1166#-N2DAXNp3atYAzBTE-fY:-N2Decfs-W0TCaVX23V-:b4wpkxr) ([raw file](https://github.com/sillsdev/libpalaso/blob/6f4b930a463d5e1e88aa0b9341ddc14f623f5922/SIL.Core.Tests/Xml/XmlSerializationHelperTests.cs#L496)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should these new test methods be named with `SerializeToFileWithWriteThrough`?
(I'm guessing you changed your name about the name at some point.)
</blockquote></details>

Actually I copied the existing misnamed test...

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1166)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @andrew-polk, @ermshiperete, and @jasonleenaylor)

___
*[`CHANGELOG.md` line 43 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1166#-N2DBOX5CHqNRRCqIlwy:-N2Difs_6SeG55nx0J35:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/6f4b930a463d5e1e88aa0b9341ddc14f623f5922/CHANGELOG.md#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If we're doing strict semver, I think needs a semver:minor in the commit message.
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1166)* status: all files reviewed, 1 unresolved discussion (waiting on @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[`CHANGELOG.md` line 43 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1166#-N2DBOX5CHqNRRCqIlwy:-N2DmkCKDDItKdls7wFn:b-83xlh4) ([raw file](https://github.com/sillsdev/libpalaso/blob/6f4b930a463d5e1e88aa0b9341ddc14f623f5922/CHANGELOG.md#L43)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like it is supposed to be `+semver:minor` (not `+semver-minor` as you have).

Otherwise, LGTM

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1166)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @andrew-polk, @ermshiperete, and @jasonleenaylor)

___
*[`CHANGELOG.md` line 43 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1166#-N2DBOX5CHqNRRCqIlwy:-N2H5gqY8ZLntLoemv0N:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/6f4b930a463d5e1e88aa0b9341ddc14f623f5922/CHANGELOG.md#L43)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like it is supposed to be `+semver:minor` (not `+semver-minor` as you have).

Otherwise, LGTM
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1166)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete and @jasonleenaylor)

**Pull request merged**
