### PR TITLE
BL-5416 Improve RobustIO.LoadXElement NR path names

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/600)

### CODE REVIEW

**Comment by hatton** [comment]
Looks good, and I don't suppose these failed tests are related, but let's see if that gets sorted first.

I tend to think this method you fixed doesn't belong in this class, btw. But at least now it will be fixed.

**Comment by andrew-polk** [comment]
The failing tests were fixed in another PR. But if we want to see this PR build successfully, we need to rebase on that change.

**Comment by JohnThomson** [comment]
I believe I've successfully rebased the change...do we need to do something to start a new test build?

**Comment by andrew-polk** [comment]
They started automatically. And all relevant builds succeeded.

**Pull request merged**
