### PR TITLE
Changed REAP access protocol label from "Insite users" to "REAP users"

### PR DESCRIPTION
**Pull request by tombogle**
This is probably not a "breaking change" per se, but it likely requires downstream products to do a data migration to prevent data loss.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1229)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
I'm wondering if any data migration should also be handled by this library. Or at least facilitated by it.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-:-ND-mNlSBkCimOOwwYJZ:b2epkm0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`Palaso.sln.DotSettings` line 55 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-ND-kqs1C9HFBz8erPNj:-ND-kqs26b-j7nohERHZ:b-7afehv) ([raw file](https://github.com/sillsdev/libpalaso/blob/41b812a22120709b19ed1c47610cae79a7682d4c/Palaso.sln.DotSettings#L55)):*
> ```
> 	<s:Boolean x:Key="/Default/UserDictionary/Words/=Latn/@EntryIndexedValue">True</s:Boolean>
> 	<s:Boolean x:Key="/Default/UserDictionary/Words/=LDML/@EntryIndexedValue">True</s:Boolean>
> 	<s:Boolean x:Key="/Default/UserDictionary/Words/=libpalaso/@EntryIndexedValue">True</s:Boolean>
> ```

Not a problem, but I don't see anywhere in your added comments or code where libpalaso appears to want spell checking.



_Code quote:_
```
libpalaso/@EntryIndexedValue">True</s:Boolean>
```

**Review by jasonleenaylor — COMMENTED** [review]
Also, if you're working on a major version change related to archiving perhaps it is a good time to change the name of 'GetDocumentaionUri' to add the missing 't'?

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-:-ND-n0Ia56kft2hoitB1:b-p1bkvy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Review by tombogle — COMMENTED** [review]
I don't think the archiving code in libpalaso could do the DM or even know if DM is needed because it is not responsible for staring the access protocol. In SayMore, the code already handles the possibility that a session might store an access protocol that no longer exists, but that code just clears the information if it can't find a corresponding protocol, so the user would have to notice that it had been cleared and then manually reset it (assuming they could remember what it had been and/or figure out what the new value should be). So that is why I plan to add a little code in SayMore to facilitate the rename.
I did fix the name of GetDocumentationUri.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-:-ND2e58D0OSaSkaV2ZOv:bt5rph5)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @jasonleenaylor and @tombogle)

___
*[`Palaso.sln.DotSettings` line 55 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-ND-kqs1C9HFBz8erPNj:-ND2ydnP43rqe-hsO2zl:bm2tt77) ([raw file](https://github.com/sillsdev/libpalaso/blob/41b812a22120709b19ed1c47610cae79a7682d4c/Palaso.sln.DotSettings#L55)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Not a problem, but I don't see anywhere in your added comments or code where libpalaso appears to want spell checking.
</blockquote></details>

True. I just stumbled upon it somewhere in the code and added it. The fewer spurious spelling errors we have, the more likely we are (hopefully) to notice when we misspell a method name!

**Review by jasonleenaylor — APPROVED** [review]
One question about not using an annotation on a method, but otherwise :LGTM:

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-:-ND3FiclBhEU-iJ5V6-p:b-gsm5l)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`SIL.Archiving/Generic/AccessProtocol/AccessProtocolList.cs` line 185 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-ND3FL3q7WGZZlJNCW95:-ND3FL3q7WGZZlJNCW96:b9kzia3) ([raw file](https://github.com/sillsdev/libpalaso/blob/ac0444783168846a7feaa2f7d373f2ebd3737b77/SIL.Archiving/Generic/AccessProtocol/AccessProtocolList.cs#L185)):*
> ```Smalltalk
> 		/// Gets the path to the documentation for this access protocol 
> 		/// </summary>
> 		public string GetDocumentationUri(string programDirectory)
> ```

So this overload isn't part of the PublicAPI?

**Comment by tombogle** [comment]
*[`SIL.Archiving/Generic/AccessProtocol/AccessProtocolList.cs` line 185 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1229#-ND3FL3q7WGZZlJNCW95:-ND3JGx-ECyD-VaFJCn6:b-dsm6xf) ([raw file](https://github.com/sillsdev/libpalaso/blob/ac0444783168846a7feaa2f7d373f2ebd3737b77/SIL.Archiving/Generic/AccessProtocol/AccessProtocolList.cs#L185)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

So this overload isn't part of the PublicAPI?
</blockquote></details>

It is, but since it is used by the other overload above, Resharper already knows it it used. so it certainly could (and maybe should) have this attribute, but at least for the purpose of making Resharper not complain, it isn't strictly necessary

**Pull request merged**
