### PR TITLE
Lookup languages by country as well as name

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/489)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-:-Kiff08pi9CAcqL5MdoA:bnfp4nl)*

**Comment by glasseyes** [comment]
minor changes needed because there are no "?" countries any more

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[SIL.WritingSystems/LanguageLookup.cs, line 80 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-KihUvje3U6KaHvLjfUJ:-KihUvje3U6KaHvLjfUK:bfbgcwg) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebedcbd3ad27e8953016314ab66c2859b60b0959/SIL.WritingSystems/LanguageLookup.cs#L80)):*
> ```Smalltalk
> 				foreach (var country in language.Countries)
> 				{
> 					// About 37 languages currently have a single country called "?". This does not seem a useful way to find them.
> ```

This isn't true now

---

*[SIL.WritingSystems/LanguageLookup.cs, line 83 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-KihV0tuW6NiUeZFwNo4:-KihV0tuW6NiUeZFwNo5:b-kcftge) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebedcbd3ad27e8953016314ab66c2859b60b0959/SIL.WritingSystems/LanguageLookup.cs#L83)):*
> ```Smalltalk
> 					if (string.IsNullOrEmpty(country) || country == "?")
> 						continue;
> 					if (!string.IsNullOrEmpty(country))
> ```

why is this needed if that has already been checked and passed above?

---

*[SIL.WritingSystems.Tests/LanguageLookupTests.cs, line 218 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-KihVVY1FtoWHcMFVrpe:-KihVVY1FtoWHcMFVrpf:bnicyqi) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebedcbd3ad27e8953016314ab66c2859b60b0959/SIL.WritingSystems.Tests/LanguageLookupTests.cs#L218)):*
> ```Smalltalk
> 			Assert.That(languages, Has.No.Member(lookup.GetLanguageFromCode("qaa")));
> 			Assert.That(languages, Has.No.Member(lookup.GetLanguageFromCode("mn-Mong")));
> 		}
> ```

The search for "?" won't work now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-:-KihVckXHCtukzwy093L:b-qhwlbl)*

**Comment by JohnThomson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[SIL.WritingSystems/LanguageLookup.cs, line 80 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-KihUvje3U6KaHvLjfUJ:-KikqRdIRK1e6hCRC96k:ba3dfob) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebedcbd3ad27e8953016314ab66c2859b60b0959/SIL.WritingSystems/LanguageLookup.cs#L80)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

This isn't true now
</blockquote></details>

Removed

---

*[SIL.WritingSystems/LanguageLookup.cs, line 83 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-KihV0tuW6NiUeZFwNo4:-KikqTIgWK8755SdyOz2:blaff8e) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebedcbd3ad27e8953016314ab66c2859b60b0959/SIL.WritingSystems/LanguageLookup.cs#L83)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

why is this needed if that has already been checked and passed above?
</blockquote></details>

Was redundant, now needed since I removed the other check.

---

*[SIL.WritingSystems.Tests/LanguageLookupTests.cs, line 218 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-KihVVY1FtoWHcMFVrpe:-Kikr6q-rOevC6HfHK4M:b3ok8cn) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebedcbd3ad27e8953016314ab66c2859b60b0959/SIL.WritingSystems.Tests/LanguageLookupTests.cs#L218)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

The search for "?" won't work now
</blockquote></details>

Actually it was testing that question-mark does NOT find anything, which is still true though because of your changes rather than the check I took out. The test actually does pass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/489)*

**Comment by jasonleenaylor** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/489#-:-KiksEi3-g3A2e8hUKae:bnfp4nl)*

**Pull request merged**
