### PR TITLE
Added CanWriteToDirectories, CanWriteToDirectory and ReportDefenderProblem

### PR DESCRIPTION
**Pull request by tombogle**
This was derived/adapted from Bloom's [DefenderFolderProtectionCheck.cs](https://github.com/BloomBooks/BloomDesktop/blob/master/src/BloomExe/MiscUI/DefenderFolderProtectionCheck.cs) implementation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1263)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1263)* status: all files reviewed, 6 unresolved discussions (waiting on @tombogle)

___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f1_SBAM3TbDP56Bi:-NZ2f1_TEmV7hHyy5n7R:beracix) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L47)):*
> ```Smalltalk
> 		/// ransomware checking.
> 		/// </summary>
> 		/// <param name="report">Action to perform if a folder is found which is not writable
> ```

Won't this action be taken for every folder which is not writable?
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 71 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2eYmB5Hrv7XCSLMQz:-NZ2eYmB5Hrv7XCSLMR-:b6evms1) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L71)):*
> Leave as null to just return false to the caller without reporting the problem.

I don't see this logic implemented anywhere.
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2c_mdCGlKI8JIFtit:-NZ2c_mdCGlKI8JIFtiu:b-38h046) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L97)):*
> ```Smalltalk
> 		{
> 			if (!Platform.IsWindows)
>                 return true;
> ```

Starting here, there is a mix of indentation styles.
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 106 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f9H_6gXyoTqxMUiR:-NZ2f9H_6gXyoTqxMUiS:b4f9lmf) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L106)):*
> catch (Exception exc)

We recently had this catch a FileNotFound exception. Let me see what the fallout of that was... if we decided to enhance things.
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2dinI40Zuz9f2RYEc:-NZ2dinI40Zuz9f2RYEd:b-gmemt4) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L130)):*
> ```Smalltalk
>                 "other virus or malware protection. You can search online or contact a local " +
>                 "support person for help with configuring Windows Defender (and other antivirus " +
>                 "software) to allow this program to work.");
> ```

I've lost track of how these things work in libpalaso these days. Do these strings need to be added to an .xlf?
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 140 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2eGJ5-27Gtw464cjN:-NZ2eGJ5-27Gtw464cjO:b-yh91kz) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L140)):*
> ```Smalltalk
>             try
>             {
> 	            File.Delete(testPath);
> ```

`RobustFile.Delete`
Unless you're truly trying to not be robust. In that case, it is worth commenting.

**Comment by andrew-polk** [comment]
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 106 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f9H_6gXyoTqxMUiR:-NZ2fdjy10CkrOJM_1h7:b-sxv01n) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L106)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> catch (Exception exc)

We recently had this catch a FileNotFound exception. Let me see what the fallout of that was... if we decided to enhance things.
</blockquote></details>

Hm. Looks like it is still being analyzed.
https://issues.bloomlibrary.org/youtrack/issue/BL-12209

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 140 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2eGJ5-27Gtw464cjN:-NZ7_YLg4GgWgNiHfhKo:b-4zav3d) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L140)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

`RobustFile.Delete`
Unless you're truly trying to not be robust. In that case, it is worth commenting.
</blockquote></details>

I had thought about that, but since the comment already said not to try to hard, I was kind of ambivalent. But I went ahead and made the change now.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2dinI40Zuz9f2RYEc:-NZ7Y6wd-DchmN265dpv:b-dv3mn0) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L130)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I've lost track of how these things work in libpalaso these days. Do these strings need to be added to an .xlf?
</blockquote></details>

The English one shouldn't need to be checked in, but it should be updated in crowdin, so it can be localized. I'll work on that and do the Spanish localization.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2dinI40Zuz9f2RYEc:-NZ7cutY3ppQ27WgWe2D:b4791oy) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L130)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

The English one shouldn't need to be checked in, but it should be updated in crowdin, so it can be localized. I'll work on that and do the Spanish localization. 
</blockquote></details>

I see that I am not a manager for that Crowdin project (but you are!). So I can't update the English strings. I am a translator, so once they are updated, I can do the Spanish.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1263)* status: all files reviewed, 3 unresolved discussions (waiting on @tombogle)

___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f1_SBAM3TbDP56Bi:-NZ84fE0--8_LRFbePkK:bnuk3hn) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Won't this action be taken for every folder which is not writable?
</blockquote></details>

1. I'm not sure that's what we want.
2. If it is, it should be documented explicitly, methinks.
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 130 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2dinI40Zuz9f2RYEc:-NZ84Szw65qZtzV_W-LA:bk4vi2z) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L130)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I see that I am not a manager for that Crowdin project (but you are!). So I can't update the English strings. I am a translator, so once they are updated, I can do the Spanish.
</blockquote></details>

You're a manager now. : )
Sad to hear the process is currently so manual... but it is what it is.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f1_SBAM3TbDP56Bi:-NZ7On7w8N8hWmcz3-ZK:b-8ndk1r) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Won't this action be taken for every folder which is not writable?
</blockquote></details>

No, because it returns (false) once it finds a folder it can't write to.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1263)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 71 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2eYmB5Hrv7XCSLMQz:-NZ7TkwWB3MG2Cyz-crq:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L71)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> Leave as null to just return false to the caller without reporting the problem.

I don't see this logic implemented anywhere.
</blockquote></details>

Done.
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 97 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2c_mdCGlKI8JIFtit:-NZ7QfVG9lfyC6geJtGp:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L97)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Starting here, there is a mix of indentation styles.
</blockquote></details>

Done.
___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 106 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f9H_6gXyoTqxMUiR:-NZ7TujL4qoabg2gjhC0:b1tnv47) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L106)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. Looks like it is still being analyzed.
https://issues.bloomlibrary.org/youtrack/issue/BL-12209
</blockquote></details>

I have enhanced my version to ensure that folderToCheck exists. I think that if an app passes in a non-existent folder, that should be considered a programming error. Not sure that would result in a FileNotFoundException, though. What would happen if CreateAndGetPathButDontMakeTheFile were to retutrn a temp file name that just happened to be an existing file or folder in the folderToCheck? (Seems really unlikely, but it wouldn't end well, I'm sure.) I've added a check for that.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f1_SBAM3TbDP56Bi:-NZB2bvWAsv2IZzTwVrT:b44fchi) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L47)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

No, because it returns (false) once it finds a folder it can't write to.
</blockquote></details>

Grr... Just realized that I had a bunch of draft comments in Reviewable that didn't get published yesterday. Now I published them, but they are out of order (and in some cases out of date). I can easily make the comment more explicit. Why do you think we wouldn't want this and/or what do you think we would want? My thought is that if an app needs to write to two different locations, it could call this method with both folders. As soon as it discovers that there is a problem with writing to either folder, the problem could be reported and the user could take the necessary remedial action. I don't think there would be any likely benefit to the user to know about both problems, since the solution would generally be the same (at least in the case of Windows Defender, which is what's in focus here).

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs` line 47 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1263#-NZ2f1_SBAM3TbDP56Bi:-NZBwnxZ28a6PS-HDjCH:bhojiqx) ([raw file](https://github.com/sillsdev/libpalaso/blob/0e3d2c4bd1b5c42fb03fddd0087eb59d5202a142/SIL.Windows.Forms/Miscellaneous/WindowsUtilities.cs#L47)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Grr... Just realized that I had a bunch of draft comments in Reviewable that didn't get published yesterday. Now I published them, but they are out of order (and in some cases out of date). I can easily make the comment more explicit. Why do you think we wouldn't want this and/or what do you think we would want? My thought is that if an app needs to write to two different locations, it could call this method with both folders. As soon as it discovers that there is a problem with writing to either folder, the problem could be reported and the user could take the necessary remedial action. I don't think there would be any likely benefit to the user to know about both problems, since the solution would generally be the same (at least in the case of Windows Defender, which is what's in focus here).   
</blockquote></details>

Sorry; I meant I didn't think we want to report more than once. But yes, I misread the code.
Looks good.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
