### PR TITLE
Correct logic for initializing Windows Forms handlers by default if present

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/379)

### CODE REVIEW

**Comment by hatton** [comment]
Hi Andrew,
Can you describe what the previous logic was attempting, and why it's wrong?

**Comment by andrew-polk** [comment]
The ErrorHandler and ErrorReporter are initialized with the Console versions _unless_ SIL.Windows.Forms is referenced by the application. Then it attempts to use the Windows Forms versions. 

The incorrect logic was that it found the FirstOrDefault assembly _containing_ "SIL.Windows.Forms" rather than _equaling_ "SIL.Windows.Forms". This meant that other assemblies such as SIL.Windows.Forms.DblBundle could be found "First" and the Windows Forms versions were not being used.

The result was the the Console versions were being used in HearThis, for example. Thus, a failure to load a project, for example, was never reported to the user in any way.

**Comment by andrew-polk** [comment]
I don't think the test failures here are a problem with this code. The way the pull request build logic is currently working on TeamCity, the build includes 36 other changes besides this one in the lfmerge branch. The master branch build for precise64 built successfully.

**Comment by andrew-polk** [comment]
bump

**Comment by ermshiperete** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/379#-:-KKxtKkafGojLvvOSMOb:980077423)*

**Pull request merged**
