### PR TITLE
Fix a memory leak in ImageToolboxControl

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Note that setting ImageInfo.Disposed causes ImageInfo.Dispose() to return
immediately without freeing its resources.  Dispose() sets Disposed
when it is finished freeing everything.

### CODE REVIEW

**Comment by hatton** [comment]
Since this supposed to be an automatically generated file that undergoes no hand editing, what can you tell us? Was this problem introduced by hand editing, or automatically? Is there any chance of it coming back automatically? Can things be changed so that no by-hand material is even in there (that's normally the requirement).

**Comment by StephenMcConnel** [comment]
The  InitializeComponents() method and the list of member component variables are the only sections modified by Designer after the initial creation.  The Dispose() method is created initially, but it is allowed (and maybe even expected) to be edited by hand.  This problem was introduced by hand editing.

**Comment by hatton** [comment]
> The Dispose() method is created initially, but it is allowed (and maybe even expected) to be edited by hand. This problem was introduced by hand editing.

Hmm. Can you point me to a writeup of that?  I for one, have always done my disposing in the non-generated part. In most cases, this is a matter of adding the object you want to get disposed to the objects "Components" property. E.g. http://stackoverflow.com/a/5069426/723299

**Comment by jasonleenaylor** [comment]
LGTM

**Comment by hatton** [comment]
Dispose in these things appears to be a complicated issue: http://stackoverflow.com/questions/167602/how-do-i-add-dispose-functionality-to-a-c-sharp-usercontrol

But I'll merge this.

**Comment by tombogle** [comment]
As the one comment says, you can safely modify the generated Dispose method (and optionally move it to the non-Designer file). Although it is initially generated, it is never modified by Designer, which is why it’s not inside the

#region Windows Form Designer generated code

**Pull request merged**
