### PR TITLE
Save non-CC licenses properly in images

### PR DESCRIPTION
**Pull request by StephenMcConnel**
The change allows users to go from a CC license to a non-CC license for
images.  The reverse was already possible.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1071)

### CODE REVIEW

**Comment by hatton** [comment]
The problem here is that the original code didn't explain what the thinking was in a comment, so I'm finding it difficult to know that this doesn't fix the case at hand but break some other case?

**Comment by ermshiperete** [comment]
Maybe it would it be possible to add a unit test?

**Review by StephenMcConnel — COMMENTED** [review]
The code was originally written by @johnthomson  in commit 8570f8837 on July 8, 2014.  The commit title was "Replace exiftool with taglib#".  There was more detail following, but nothing specific to this function or these lines in the code.
A unit test has been added.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1071#-:-MYQS8ABD0QJ_-XN7o4_:bs3ukwo)* status: 0 of 2 files reviewed, all discussions resolved

**Review by ermshiperete — APPROVED** [review]

**Comment by hatton** [comment]
We have an unrelated test failing sometimes. I've created a card to fix it [here](https://issues.bloomlibrary.org/youtrack/issue/BL-9825), and will merge this.

**Pull request merged**
