### PR TITLE
Fix generation of LanguageDataIndex.json

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/594)

### CODE REVIEW

**Comment by papeh** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[LanguageData.Tests/LanguageDataIndexTests.cs, line 48 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/594#-L2Qzatffz3eu4t5ByUa:-L2QzatgOe_Mz7jt7cHZ:b-o9y1yj) ([raw file](https://github.com/sillsdev/libpalaso/blob/380fe35e9e1b0e9a1ca899c0cfa02d9ac3f997e0/LanguageData.Tests/LanguageDataIndexTests.cs#L48)):*
> ```Smalltalk
> 			_langIndex.WriteJson(jsonFile);
> 
> 			Assert.True(File.ReadAllText(jsonFile).Length > 0);
> ```

some test is better than no test, but wouldn't it be better to assert _something_ about the files contents (on the odd chance that the contents are simply an error or a newline).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/594#-:-L2QzyE0M-U3ZtcS1yR8:bnfp4nl)*

**Comment by papeh** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/594)*

**Comment by andrew-polk** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[LanguageData.Tests/LanguageDataIndexTests.cs, line 48 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/594#-L2Qzatffz3eu4t5ByUa:-L2REjaQNRkHjXshLba0:b6u5l08) ([raw file](https://github.com/sillsdev/libpalaso/blob/380fe35e9e1b0e9a1ca899c0cfa02d9ac3f997e0/LanguageData.Tests/LanguageDataIndexTests.cs#L48)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

some test is better than no test, but wouldn't it be better to assert _something_ about the files contents (on the odd chance that the contents are simply an error or a newline).
</blockquote></details>

Enhanced (slightly).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/594)*

**Comment by papeh** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/594)*

**Pull request merged**
