### PR TITLE
LT-21652: polish picture dialog

### PR DESCRIPTION
**Pull request by aror92**
Use the custom no border toolstrip renderer to eliminate the white border artifact in AquireImageControl. (Other part of [LT-21652](https://jira.sil.org/browse/LT-21652).)

Also set toolStrip1's RenderMode to Professional and reset back color to control from within the design view, which regenerated the designer & resx files.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1301)

### CODE REVIEW

**Review by mark-sil — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1301)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @aror92)

**Comment by andrew-polk** [comment]
What was the reason for changing the tab selection indicator?

Before:
image

After:
image

Also, this change didn't get an entry in the change log.

**Comment by jasonleenaylor** [comment]
@andrew-polk Hello, sorry about that. I thought you all had stopped using this. The intended UI change was only to remove the ugly line artifact. I didn't give it adequate review.

**Comment by andrew-polk** [comment]
Thanks. 
Yeah, we're still using it for now.
We've done some work on a react replacement, but it hasn't shipped yet.

**Pull request merged**
