### PR TITLE
PTX-21397 add ability to paste scripture ref in VerseControl

### PR DESCRIPTION
**Pull request by jwickberg**
Implementing a Paratext feature request to be able to paste a scripture reference into the verse control.

The reference can either be the short form: GEN 1:27

or a longer form that uses the localized book names: 2 Corinthians 3:18

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1153)

### CODE REVIEW

**Review by FoolRunning — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1153)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @FoolRunning and @jwickberg)

___
*[SIL.Windows.Forms.Scripture/VerseControl.cs, line 669 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1153#-MzuNKoE20ZwLlR5ozmr:-MzuNKoE20ZwLlR5ozms:b-26zr6) ([raw file](https://github.com/sillsdev/libpalaso/blob/7c049e36f940690c92bd77546d5a887bdfa94f97/SIL.Windows.Forms.Scripture/VerseControl.cs#L669)):*
> ```Smalltalk
> 		/// <param name="e">KeyDown event args. e.SuppessKeyPress will be set to true if control is updated</param>
> 		/// <returns>True if verse control has been updated</returns>
> 		private bool CanPasteScriptureRef(KeyEventArgs e)
> ```

This seems like a bad name for a method that actually does do the paste. Maybe something like **HandlePasteScriptureRef** would be better?
___
*[SIL.Windows.Forms.Scripture/VerseControl.cs, line 706 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1153#-MzuNt-mDY1C-x_ZMVG5:-MzuNt-mDY1C-x_ZMVG6:bfhx4s6) ([raw file](https://github.com/sillsdev/libpalaso/blob/7c049e36f940690c92bd77546d5a887bdfa94f97/SIL.Windows.Forms.Scripture/VerseControl.cs#L706)):*
> ```Smalltalk
> 
> 			// check for standard reference in form: GEN 1:27
> 			var match = Regex.Match(text, @"^([0-9A-Za-z]{3})\s*(\d+)[\p{Po}](\d+)$");
> ```

I would suggest either trimming the text or making the regular expressions more forgiving. It would be annoying to fail the paste just because you caught an extra space before or after the reference.

**Comment by jwickberg** [comment]
I changed the method name as requested and made my new code use the existing regular expression by making the string a constant.

I couldn't call the existing ParseRefString method since it gets the localized data a different way.

**Review by FoolRunning — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1153#-:-Mzywt3F9bNGef_0dkAN:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @jwickberg)

**Review by FoolRunning — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1153#-:-N-NwSWU9AARgGlhTGrT:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @jwickberg)

**Review by FoolRunning — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1153)* status: all files reviewed, 1 unresolved discussion (waiting on @jwickberg)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1153)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jwickberg)

**Pull request merged**
