### PR TITLE
Implement AudioRecorder class for Linux

### PR DESCRIPTION
**Pull request by StephenMcConnel**
(minimal implementation for Bloom)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/433)

### CODE REVIEW

**Comment by ermshiperete** [comment]
With Ubuntu using Pulse instead of Alsa now I wonder if it would be better to implement a pulse-based audio recorder. This might make a few things easier (like finding the default recording device). But that's probably a job for another time.

A few comments, but otherwise looks pretty good.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6oMhJ6JVJidwIiWdq:-Ka6oMhJ6JVJidwIiWdr:b-aa7qtr) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Copyright header missing

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 33 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka70O553qwnjoASgdKp:-Ka70O553qwnjoASgdKq:b-ox044v) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L33)):*
> Bloom.ToPalaso
This comment seems irrelevant now that it is in libpalaso

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 43 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6ly7Swng0KVmODQmC:-Ka6ly7TPOHN5VZ7U02N:b-xgeqpr) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L43)):*
> ```Smalltalk
> 		}
> 
> 		public virtual void Dispose()
> ```

IMO it would be better to follow the [dispose pattern](https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx) and implement a method `protected virtual void Dispose(bool disposing)` and make this method non-virtual: `public void Dispose()`

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 45 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6nCHQ2RYQkWMhbwDf:-Ka6nCHQ2RYQkWMhbwDg:bkdnxhi) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L45)):*
> ```Smalltalk
> 		public virtual void Dispose()
> 		{
> 			lock (this)
> ```

Best practices suggest not to [lock on `this`](http://stackoverflow.com/questions/251391/why-is-lockthis-bad) but use a private object instead.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 70 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6oDg7Jwzp1D6Nedvx:-Ka6oDg89KspfXh_cknz:bb6klmp) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L70)):*
> ```Smalltalk
> 		}
> 
> 		RecordingDevice _selectedDevice;
> ```

Move this field to the top of the class to the other fields?

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 70 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka72Fpa94retUhnrAyq:-Ka72Fpa94retUhnrAyr:b-i2d94h) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L70)):*
> _selectedDevice

`_selectedRecordingDevice` ?

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 102 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka71b0u97TNTHzXBiJs:-Ka71b0u97TNTHzXBiJt:b-q38n7n) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L102)):*
> ```Smalltalk
> 				RecordingState = SIL.Media.Naudio.RecordingState.Recording;
> 				_session = new AudioAlsaSession(waveFileName);
> 				var device = String.Format("plughw:{0}", SelectedDevice.DeviceNumber);
> ```

I think we can end up with `SelectedDevice == null` which would then crash here. To determine the selected device we read the available capture devices and try to find the default one. However, at least on my machine it seems (from looking at the files the code below reads) that we won't detect a default device. 

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 134 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6nskogw0fojwuAp8Z:-Ka6nskogw0fojwuAp8_:b-r9mqs9) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L134)):*
> ```Smalltalk
> 
> 		// TODO/REVIEW: I don't know that we can do anything with this on Linux.
> 		public virtual double MicrophoneLevel
> ```

Use auto property instead of `_microphoneLevel`?

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 140 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6nzfXv4CNPIwIhSqj:-Ka6nzfXv4CNPIwIhSqk:b-jhntl5) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L140)):*
> ```Smalltalk
> 		}
> 
> 		public virtual WaveFormat RecordingFormat
> ```

Use auto property?

---

*[SIL.Media/AlsaAudio/RecordingDevice.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6oQ6Qc6lZ2QdihHic:-Ka6oQ6Qc6lZ2QdihHid:b-aa7qtr) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/RecordingDevice.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Copyright header missing

---

*[SIL.Media/AlsaAudio/RecordingDevice.cs, line 138 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka72vOpEckC9Faf77MK:-Ka72vOpEckC9Faf77ML:bwzba42) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/RecordingDevice.cs#L138)):*
> ```Smalltalk
> 				if (list.Count == 0)
> 					DefaultDevice = null;
> 				return list;
> ```

It would be safer to check that we have a DefaultDevice set. If it's still `null` here maybe we could set it to the first item in the list?

---

*[SIL.Media/AlsaAudio/RecordingDevice.cs, line 175 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka73BgAXwIT0WUCuyOt:-Ka73BgAXwIT0WUCuyOu:bhe4av) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/RecordingDevice.cs#L175)):*
> ```Smalltalk
> 
> This is the only clue I've found in 2 days of searching to tell which card is
> assigned as the default (preferred) input device.
> ```

I don't know either how to find the default input device. However, this algorithm won't work on my machine because `subdevices_count` and `subdevices_avail` are equal for all capture devices.

---

*[SIL.Media/AlsaAudio/WaveFormat.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka7-qGnuJvUnlmbtJds:-Ka7-qGoZMjSH32HbxlE:b-aa7qtr) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/WaveFormat.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Copyright header missing

---

*[SIL.Media/Naudio/IAudioRecorder.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka7-xnXfJFZhT7DU41_:-Ka7-xnXfJFZhT7DU41a:b-aa7qtr) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/Naudio/IAudioRecorder.cs#L1)):*
> ```Smalltalk
> using System;
> ```

Copyright header missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-:-Ka747RO70y0mOH82rhM:b-1q1knc)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 6 files reviewed at latest revision, 14 unresolved discussions.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6oMhJ6JVJidwIiWdq:-Ka8SRTuUnedkomIstBK:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L1)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Copyright header missing
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 33 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka70O553qwnjoASgdKp:-Ka8SSYEz6n21EPClHaQ:b-p3xiyx) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L33)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

> Bloom.ToPalaso
This comment seems irrelevant now that it is in libpalaso
</blockquote></details>

Done.  Changed "Bloom.ToPalaso" to "Alsa"

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 43 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6ly7Swng0KVmODQmC:-Ka8VZMf9sc8BnbP8Ijw:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L43)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

IMO it would be better to follow the [dispose pattern](https://msdn.microsoft.com/en-us/library/b1yfkh5e(v=vs.110).aspx) and implement a method `protected virtual void Dispose(bool disposing)` and make this method non-virtual: `public void Dispose()`
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 45 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6nCHQ2RYQkWMhbwDf:-Ka8VWbAXvvvIH_xQBwL:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L45)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Best practices suggest not to [lock on `this`](http://stackoverflow.com/questions/251391/why-is-lockthis-bad) but use a private object instead.
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 70 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6oDg7Jwzp1D6Nedvx:-Ka8Vspp0LsvT4thxQdU:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L70)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Move this field to the top of the class to the other fields?
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 102 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka71b0u97TNTHzXBiJs:-Ka8Xsi-LTMI1zEMFKvq:bv7m998) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L102)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I think we can end up with `SelectedDevice == null` which would then crash here. To determine the selected device we read the available capture devices and try to find the default one. However, at least on my machine it seems (from looking at the files the code below reads) that we won't detect a default device. 
</blockquote></details>

I'm not sure that's the case, but I've changed the code to handle null for SelectedDevice.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 134 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6nskogw0fojwuAp8Z:-Ka8WIiMv1MDvdWMy4wF:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L134)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Use auto property instead of `_microphoneLevel`?
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 140 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6nzfXv4CNPIwIhSqj:-Ka8WI5dkVXAUC4mGUPA:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L140)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Use auto property?
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/RecordingDevice.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka6oQ6Qc6lZ2QdihHic:-Ka8Sb2hEn4rBz_lZ2T3:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/RecordingDevice.cs#L1)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Copyright header missing
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/RecordingDevice.cs, line 138 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka72vOpEckC9Faf77MK:-Ka8jSCdq2DizHWEvPsJ:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/RecordingDevice.cs#L138)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It would be safer to check that we have a DefaultDevice set. If it's still `null` here maybe we could set it to the first item in the list?
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/WaveFormat.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka7-qGnuJvUnlmbtJds:-Ka8SchOC6D5tom6N0rh:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/WaveFormat.cs#L1)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Copyright header missing
</blockquote></details>

Done.

---

*[SIL.Media/Naudio/IAudioRecorder.cs, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka7-xnXfJFZhT7DU41_:-Ka8So1CMb-DkpGXNpDQ:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/Naudio/IAudioRecorder.cs#L1)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Copyright header missing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/433)*

**Comment by ermshiperete** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 61 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-KaBKE99iglzKQGueQv3:-KaBKE99iglzKQGueQv4:b-ajlms9) ([raw file](https://github.com/sillsdev/libpalaso/blob/1cf180aad1a0c7fe85b26bcfa8fef8cf8dd74c35/SIL.Media/AlsaAudio/AudioRecorder.cs#L61)):*
> ```Smalltalk
> 			{
> 				Dispose(true);
> 				RecordingState = SIL.Media.Naudio.RecordingState.NotYetStarted;
> ```

It would be cleaner to set the RecordingState in the `Dispose(bool)` method.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 63 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-KaBK60minDcJ1HyIkI3:-KaBK60minDcJ1HyIkI4:b97xf6o) ([raw file](https://github.com/sillsdev/libpalaso/blob/1cf180aad1a0c7fe85b26bcfa8fef8cf8dd74c35/SIL.Media/AlsaAudio/AudioRecorder.cs#L63)):*
> ```Smalltalk
> 				RecordingState = SIL.Media.Naudio.RecordingState.NotYetStarted;
> 			}
> 		}
> ```

Should also call `GC.SuppressFinalize(this);`here.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 89 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-KaBKjDlGGpTUpTNo73R:-KaBKjDlGGpTUpTNo73S:bcekkd) ([raw file](https://github.com/sillsdev/libpalaso/blob/1cf180aad1a0c7fe85b26bcfa8fef8cf8dd74c35/SIL.Media/AlsaAudio/AudioRecorder.cs#L89)):*
> ```Smalltalk
> 			set
> 			{
> 				if (_selectedDevice != null && _selectedDevice.Equals(value))
> ```

Just noticing now: why do we need this `if` statement? Since `_selectedDevice` is a field I can't see anything bad happening by setting it to the same value again.

Could change into a auto property if we don't need the it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/433)*

**Comment by StephenMcConnel** [comment]
Review status: 5 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 70 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka72Fpa94retUhnrAyq:-KaD7qO9XQ6a-fezkIhN:b5cvlct) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/AudioRecorder.cs#L70)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

> _selectedDevice

`_selectedRecordingDevice` ?

</blockquote></details>

I've changed RecordingDevice to an auto property, so this field no longer exists.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 61 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-KaBKE99iglzKQGueQv3:-KaD7j9IJXeRRDPpkxrt:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/1cf180aad1a0c7fe85b26bcfa8fef8cf8dd74c35/SIL.Media/AlsaAudio/AudioRecorder.cs#L61)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It would be cleaner to set the RecordingState in the `Dispose(bool)` method.
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 63 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-KaBK60minDcJ1HyIkI3:-KaD7k6LGOhvFI9Xdp0z:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/1cf180aad1a0c7fe85b26bcfa8fef8cf8dd74c35/SIL.Media/AlsaAudio/AudioRecorder.cs#L63)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Should also call `GC.SuppressFinalize(this);`here.
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/AudioRecorder.cs, line 89 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-KaBKjDlGGpTUpTNo73R:-KaD7oWv0TvRH-vJ0Is7:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/1cf180aad1a0c7fe85b26bcfa8fef8cf8dd74c35/SIL.Media/AlsaAudio/AudioRecorder.cs#L89)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Just noticing now: why do we need this `if` statement? Since `_selectedDevice` is a field I can't see anything bad happening by setting it to the same value again.

Could change into a auto property if we don't need the it.
</blockquote></details>

Done.

---

*[SIL.Media/AlsaAudio/RecordingDevice.cs, line 175 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-Ka73BgAXwIT0WUCuyOt:-KaD849JQyKt8gweS2au:bgiduei) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b96cdccc4d033f996bebda2728749be526a445a/SIL.Media/AlsaAudio/RecordingDevice.cs#L175)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I don't know either how to find the default input device. However, this algorithm won't work on my machine because `subdevices_count` and `subdevices_avail` are equal for all capture devices.
</blockquote></details>

I've adjusted the code to use the first recording device listed if this algorithm fails to find anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/433)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-:-KaDLFrMqaFdWPJ4dz_y:bnfp4nl)*

**Comment by StephenMcConnel** [comment]
The continuous build failure looks totally bogus -- it was in an unrelated area of the code, failing to find Icu.

**Comment by ermshiperete** [comment]
> The continuous build failure looks totally bogus -- it was in an unrelated area of the code, failing to find Icu.

That's stupid TC trying to build with the PR merged into the wrong branch...

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/433#-:-KaDR61CICmp84q9p48Q:b-m4wuz)*

**Pull request merged**
