### PR TITLE
Fixed mistake in the references for the new version of NAudio.

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/626)

### CODE REVIEW

**Comment by andrew-polk** [comment]
*[SIL.Windows.Forms/SIL.Windows.Forms.csproj, line 391 at r1](https://beta.reviewable.io/reviews/sillsdev/libpalaso/626#-L6S3Esp3i2b5FcwhS9y:-L6S3Esp3i2b5FcwhS9z:b-y57326) ([raw file](https://github.com/sillsdev/libpalaso/blob/fecb26f4227c72624bc0a6b95e5bc1932a9ce6bb/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L391)):*
> ```XML
>     </Reference>
>     <Reference Include="Microsoft.VisualBasic" Condition="'$(OS)'=='Windows_NT'" />
>     <Reference Include="NAudio, Version=1.8.4.0, Culture=neutral, processorArchitecture=MSIL">
> ```

Doesn't this need to be removed?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/626)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms/SIL.Windows.Forms.csproj, line 391 at r1](https://beta.reviewable.io/reviews/sillsdev/libpalaso/626#-L6S3Esp3i2b5FcwhS9y:-L6S6b_vBRDouc0lYjmW:b-b88mpa) ([raw file](https://github.com/sillsdev/libpalaso/blob/fecb26f4227c72624bc0a6b95e5bc1932a9ce6bb/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L391)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Doesn't this need to be removed?
</blockquote></details>

Technically, I guess that would be preferable :-)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/626)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/626#-:-L6S9QVf-0muctaG1h1N:bnfp4nl)*

**Comment by glasseyes** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/626#-:-L6SCNTuyIO0exO2Q-h6:bnfp4nl)*

**Pull request merged**
