### PR TITLE
Fix non-deterministic unit test failure

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1033)

### CODE REVIEW

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1033)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by tombogle** [comment]
___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 72 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO4I9Lx3t0YkBjCJYqn:-MO4I9Lx3t0YkBjCJYqo:bn6fwbw) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L72)):*
> ```Smalltalk
> 			/// <param name="testName">A unique prefix for each test. Each test should have its prefix so that
> 			/// each test's data is independent</param>
> 			public TestEnvironment(string testPrefix)
> ```

This is probably okay, but might it be better to have the constructor generate a unique prefix rather than relying on the test to pass it in? That way if a unit test is copied (or multiple TestCases are ued), we won't have the problem of a future hard-to-track-down failure.

**Review by ermshiperete — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 72 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO4I9Lx3t0YkBjCJYqn:-MO5YzGu3H8c_kaGI_3D:b-uu8wz6) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L72)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

This is probably okay, but might it be better to have the constructor generate a unique prefix rather than relying on the test to pass it in? That way if a unit test is copied (or multiple TestCases are ued), we won't have the problem of a future hard-to-track-down failure.
</blockquote></details>

I agree. We should add a random part to the directoryname. If you think the `testPrefix` is useful we could append a random string, otherwise use a random string as directory name.
___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 150 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO5jTP-BQd8sunmAcTd:-MO5jTP-BQd8sunmAcTe:b-y3w2gf) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L150)):*
> ```Smalltalk
> 		public void PathToCollection_SameAsGiven()
> 		{
> 			using (var environment = new TestEnvironment("PathToCollection_SameAsGiven"))
> ```

Instead of hard coding the name of the test we could use `TestContext.CurrentContext.Test.Name` or `nameof(PathToCollection_SameAsGive)` (where I'd prefer the former).

**Comment by tombogle** [comment]
___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 150 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO5jTP-BQd8sunmAcTd:-MO6_IZD06fS-q4Qs2IG:b-idfl73) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L150)):*
> TestContext.CurrentContext.Test.Name
Should be able to use TestContext.CurrentContext.Test.Name inside the TestEnvironment constructor.

**Comment by tombogle** [comment]
___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 72 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO4I9Lx3t0YkBjCJYqn:-MO6_bA5-T2pCsc5Rmm_:b-8w9glz) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L72)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I agree. We should add a random part to the directoryname. If you think the `testPrefix` is useful we could append a random string, otherwise use a random string as directory name.
</blockquote></details>

Using TestContext.CurrentContext.Test.Name + TestParmeters we could perhaps generate a unique and meaningful name, with the caveats that we would need to consider filtering out invalid characters and avoiding excessively long paths.

**Review by ermshiperete — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 72 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO4I9Lx3t0YkBjCJYqn:-MO6eepv17EDvbbC8-Ut:b2vinsr) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L72)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Using TestContext.CurrentContext.Test.Name + TestParmeters we could perhaps generate a unique and meaningful name, with the caveats that we would need to consider filtering out invalid characters and avoiding excessively long paths.
</blockquote></details>

Not using a random part has the disadvantage that the tests might fail on CI if two jobs happen to run at the same time that execute the tests at the same time.

**Comment by tombogle** [comment]
___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 72 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO4I9Lx3t0YkBjCJYqn:-MO6jbqcCXi3QRziENJJ:b-c1yjtc) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L72)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Not using a random part has the disadvantage that the tests might fail on CI if two jobs happen to run at the same time that execute the tests at the same time.
</blockquote></details>

The random approach is probably just simpler as well.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1033)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ermshiperete and @tombogle)

___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 72 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO4I9Lx3t0YkBjCJYqn:-MO70lH57Xsci9QWu344:b6fy4ul) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L72)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

The random approach is probably just simpler as well.
</blockquote></details>

Added a prefix based on the test name (which I find convenient/more readable) as well as a random suffix to make it more reliable.
___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 150 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO5jTP-BQd8sunmAcTd:-MO70fUN6EZlB55ddYyt:bwx6ofw) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L150)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

> TestContext.CurrentContext.Test.Name
Should be able to use TestContext.CurrentContext.Test.Name inside the TestEnvironment constructor.
</blockquote></details>

Ah, good tip guys. Changed.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1033)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ermshiperete and @tombogle)

___
*[SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs, line 72 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-MO4I9Lx3t0YkBjCJYqn:-MO70temCgHgjWNlk16E:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/446817db7e8b61b860f5c3405f8828c5832093d0/SIL.WritingSystems.Tests/LdmlInFolderWritingSystemRepositoryTests.cs#L72)):*
<details><summary><i>Previously, sujeffreyl wrote…</i></summary><blockquote>

Added a prefix based on the test name (which I find convenient/more readable) as well as a random suffix to make it more reliable.
</blockquote></details>

Done.

**Review by ermshiperete — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1033#-:-MO7DJFS94QGAiUjMWB8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

**Comment by tombogle** [comment]
:lgtm:

**Pull request merged**
