### PR TITLE
Actually round trip unknown ldml content to global store

### PR DESCRIPTION
**Pull request by jasonleenaylor**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/722)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
The Save code in the global store would round trip unknown elements if there was an old file to use. The code in local store caused the old file to be deleted before the save. This change will copy the old file out of the way and move it back after the global store has been modified so that the save has access. I tried skipping the remove but the current Set logic depends on the file being gone. This seems to be the least drastic change if it isn't too ugly.

**Comment by andrew-polk** [comment]
Likely an acceptable amount of ugliness... : )
But deserves some comments in the code.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor and @ddaspit)

---

*[SIL.WritingSystems/GlobalWritingSystemRepository.cs, line 530 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/722#-LEu0kKJ2kL1ZvVe_51h:-LEu0kKJ2kL1ZvVe_51i:b-z1s8yn) ([raw file](https://github.com/sillsdev/libpalaso/blob/c70e9346de452343d9d62cb8d73e609e822925b6/SIL.WritingSystems/GlobalWritingSystemRepository.cs#L530)):*
> ```Smalltalk
> 			{
> 				_wsFile = wsFile;
> 				File.Copy(wsFile, wsFile + _localrepoupdate);
> ```

Consider using RobustFile here and below.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/722#-:-LEu0tmR2bCeVP9fK1Oq:b-9v7oxb)*

**Comment by jasonleenaylor** [comment]
Added comments.

---







*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/722#-:-LEujmGJ-Rg3c2uWkRMY:b-277h9n)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddaspit)

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/722#-:-LEukCU573_TW7pwMM1U:bnfp4nl)*

**Pull request merged**
