### PR TITLE
Add a simple font analytics class

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This has been developed and used by the Bloom project.

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1237)

### CODE REVIEW

**Comment by tombogle** [comment]
*[`SIL.Core/Reporting/FontAnalytics.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1237#-NI4BjdA2scE5Xgso_0d:-NI4BjdB5mOOr-jfl1i7:b-6ma9ic) ([raw file](https://github.com/sillsdev/libpalaso/blob/e1da2bb45c2fb585d7ca554a1a55a1277fbde171/SIL.Core/Reporting/FontAnalytics.cs#L27)):*
> ```Smalltalk
> 		}
> 
> 		public static void Report(string documentId, FontEventType fontEventType, string langTag, bool testOnly, string fontName, string  eventDetails = null) {
> ```

For the public Report methods, I think a <summary> comment block would be helpful. Specifically, it's not clear what a documentID is intended to be. I'm guessing it is probably an arbitrary ID whose exact format/meaning might be application specific. But that should be made clear. If there is a practical limit to how long it should be, that should also be indicated.

**Comment by tombogle** [comment]
*[`SIL.Core/Reporting/FontAnalytics.cs` line 21 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1237#-NI4CPCo7LvnTYdHqjne:-NI4CPCp8NgrMWGtilW-:b-9i8bsb) ([raw file](https://github.com/sillsdev/libpalaso/blob/e1da2bb45c2fb585d7ca554a1a55a1277fbde171/SIL.Core/Reporting/FontAnalytics.cs#L21)):*
> ```Smalltalk
> 			public string Value { get; private set; }
> 			private FontEventType(string value) { Value = value; }
> 			public static FontEventType ApplyFont  => new FontEventType( "apply-font");
> ```

Maybe two spaces is some kind of "normal" practice in Bloom, but it seems to be used kind of arbitrarily. Anyway, we don't usually do that in libpalaso code, so you can probably just do a global replacement.

**Review by tombogle — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1237)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @StephenMcConnel)

**Comment by tombogle** [comment]
I have not attempted to review the code in great detail. I assume it is working, so my feedback is merely on formatting and comments.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1237)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @tombogle)

*[a discussion](https://reviewable.io/reviews/sillsdev/libpalaso/1237#-NI4CzxQ0M_VV9v57Ko8:-NI4hb8i2GBQeO8wnSuj:b2nhktp) (no related file):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I have not attempted to review the code in great detail. I assume it is working, so my feedback is merely on formatting and comments.
</blockquote></details>

OK.

___
___
*[`SIL.Core/Reporting/FontAnalytics.cs` line 21 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1237#-NI4CPCo7LvnTYdHqjne:-NI4cIyM-Wu89MI81D3V:b-vqq18u) ([raw file](https://github.com/sillsdev/libpalaso/blob/e1da2bb45c2fb585d7ca554a1a55a1277fbde171/SIL.Core/Reporting/FontAnalytics.cs#L21)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Maybe two spaces is some kind of "normal" practice in Bloom, but it seems to be used kind of arbitrarily. Anyway, we don't usually do that in libpalaso code, so you can probably just do a global replacement.
</blockquote></details>

Done.  Probably inadvertent.
___
*[`SIL.Core/Reporting/FontAnalytics.cs` line 27 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1237#-NI4BjdA2scE5Xgso_0d:-NI4ehchCwdBDGJDscCQ:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/e1da2bb45c2fb585d7ca554a1a55a1277fbde171/SIL.Core/Reporting/FontAnalytics.cs#L27)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

For the public Report methods, I think a <summary> comment block would be helpful. Specifically, it's not clear what a documentID is intended to be. I'm guessing it is probably an arbitrary ID whose exact format/meaning might be application specific. But that should be made clear. If there is a practical limit to how long it should be, that should also be indicated.
</blockquote></details>

Done.

**Review by tombogle — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1237)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1237)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

___
*[`SIL.Core/SIL.Core.csproj` line 16 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1237#-NI83CFa88xVtDrTcgcC:-NI83CFa88xVtDrTcgcD:b-7d1p6v) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b377c51299319c4467ac06a131c909a1623b1c2/SIL.Core/SIL.Core.csproj#L16)):*
> ```XML
>     <PackageReference Include="SIL.ReleaseTasks" Version="2.5.0" PrivateAssets="All" />
>     <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
>     <PackageReference Include="System.Net.Http" Version="4.3.4" />
> ```

Careful work was done a few years ago to pull out `SIL.Core.Desktop` from `SIL.Core`. How do we know whether these packages (or ones which might be added in the future) might cause a problem for clients which consume `SIL.Core` but not `SIL.Core.Desktop`?
@hindlemail 

These seem safe intuitively, but how do we know definitively?

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1237)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

___
*[`SIL.Core/SIL.Core.csproj` line 16 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1237#-NI83CFa88xVtDrTcgcC:-NJCJdjqEzzsd7qDIq8J:b-jf1uzt) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b377c51299319c4467ac06a131c909a1623b1c2/SIL.Core/SIL.Core.csproj#L16)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Careful work was done a few years ago to pull out `SIL.Core.Desktop` from `SIL.Core`. How do we know whether these packages (or ones which might be added in the future) might cause a problem for clients which consume `SIL.Core` but not `SIL.Core.Desktop`?
@hindlemail 

These seem safe intuitively, but how do we know definitively?
</blockquote></details>

Hearing crickets, I'll move this forward.

**Pull request merged**
