### PR TITLE
Checked for disposed log box or caller-requested cancel in SafeInvoke

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1314)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1314)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`SIL.Windows.Forms/Progress/LogBox.cs` line 290 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1314#-Nu585HX4w1hdTcyMb5n:-Nu585HX4w1hdTcyMb5o:b3lr0k2) ([raw file](https://github.com/sillsdev/libpalaso/blob/063e317ea775e7f4461950b58e9aeb9f4692ba9d/SIL.Windows.Forms/Progress/LogBox.cs#L290)):*
> ```Smalltalk
> 		{
> 			if (box.IsDisposed || box.Disposing || CancelRequested)
> 				return;
> ```

It is not clear to me why you would not allow the code to add more messages after the operation is cancelled.
The obvious example where you would want to do so is to add a message stating the operation has been cancelled. But seems like there could be others.

But maybe this only applies to an error condition?
Still I'm not convinced you wouldn't want to log an error after the user cancelled.

At a more meta level, should a method named something as generic as "SafeInvoke" never complete because the user cancelled an operation?

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/Progress/LogBox.cs` line 290 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1314#-Nu585HX4w1hdTcyMb5n:-Nu5FjkWD2YQCfP27FT3:bp0tfpk) ([raw file](https://github.com/sillsdev/libpalaso/blob/063e317ea775e7f4461950b58e9aeb9f4692ba9d/SIL.Windows.Forms/Progress/LogBox.cs#L290)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

It is not clear to me why you would not allow the code to add more messages after the operation is cancelled.
The obvious example where you would want to do so is to add a message stating the operation has been cancelled. But seems like there could be others.

But maybe this only applies to an error condition?
Still I'm not convinced you wouldn't want to log an error after the user cancelled.

At a more meta level, should a method named something as generic as "SafeInvoke" never complete because the user cancelled an operation?
</blockquote></details>

Fair questions. At least in HearThis, the dialog box that contains the log box is getting disposed when the user cancels. But maybe that would not always be the case. Perhaps I should only do this if it's disposed or disposing.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1314)* status: all files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`SIL.Core/CommandLineProcessing/CommandLineRunner.cs` line 314 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1314#-NueA8JUCUAqZ0f2-hvW:-NueA8JUCUAqZ0f2-hvX:b-3tycuv) ([raw file](https://github.com/sillsdev/libpalaso/blob/37f55d3b7dd8ca64afad1612db6c77adafe125d2/SIL.Core/CommandLineProcessing/CommandLineRunner.cs#L314)):*
> ```Smalltalk
> 			// should always already know if the user cancelled, not sure there is any need to
> 			// raise an exception in this case.
> 			if (ExitCode == 0 || UserCancelled)
> ```

This seems like a logical change.
And the only users of this method (AFAICT via github) are HearThis and Bloom.

Do you need to do anything in HearThis to account for this? If so, Bloom does too as it looks like our calling code was copied from HearThis.

**Comment by tombogle** [comment]
*[`SIL.Core/CommandLineProcessing/CommandLineRunner.cs` line 314 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1314#-NueA8JUCUAqZ0f2-hvW:-Nue_ZRY6aaKsz5LxBiN:b-vpi1wk) ([raw file](https://github.com/sillsdev/libpalaso/blob/37f55d3b7dd8ca64afad1612db6c77adafe125d2/SIL.Core/CommandLineProcessing/CommandLineRunner.cs#L314)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This seems like a logical change.
And the only users of this method (AFAICT via github) are HearThis and Bloom.

Do you need to do anything in HearThis to account for this? If so, Bloom does too as it looks like our calling code was copied from HearThis.
</blockquote></details>

Good sleuthing. I'm making the change in order to try to prevent a current crashing bug in HearThis whenever the user cancels an export. I don't think I'll need to make any changes in HearThis itself, but I'm not 100% sure. Because it is a functional change that could theoretically break something, maybe it should be semver:major. I think it will already be part of a major version change when released.

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1314)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tombogle)

___
*[`SIL.Core/CommandLineProcessing/CommandLineRunner.cs` line 314 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1314#-NueA8JUCUAqZ0f2-hvW:-NuizVx_B1RO0enwOViC:b-iw92rm) ([raw file](https://github.com/sillsdev/libpalaso/blob/37f55d3b7dd8ca64afad1612db6c77adafe125d2/SIL.Core/CommandLineProcessing/CommandLineRunner.cs#L314)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Good sleuthing. I'm making the change in order to try to prevent a current crashing bug in HearThis whenever the user cancels an export. I don't think I'll need to make any changes in HearThis itself, but I'm not 100% sure. Because it is a functional change that could theoretically break something, maybe it should be semver:major. I think it will already be part of a major version change when released.
</blockquote></details>

Maybe I'm just being lazy or helping you be lazy, but I'm ok with it going as is.

**Pull request merged**
