### PR TITLE
fix l10n.proj

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1291)

### CODE REVIEW

**Comment by papeh** [comment]
😲 Just discovered that each run will add another `<note xml:lang="en">Not found in static scan of compiled code (version 0.0.0)</note>` to each applicable string. We should implement a cleanup step.

**Comment by tombogle** [comment]
*[`l10n/l10n.proj` line 41 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1291#-Nh29f4BBaVfN2Dm3pxC:-Nh29f4BBaVfN2Dm3pxD:b-pxlc7l) ([raw file](https://github.com/sillsdev/libpalaso/blob/4720c119159bef5056afe7d5412c2fe1edf03232/l10n/l10n.proj#L41)):*
> ```XML
> 	
>   <Target Name="UpdateCrowdinInternal" DependsOnTargets="GetVersion">
> 	
> ```

I know those lines are just informative. Are we removing them because they cause problems or are they actually incorrect? Maybe  the comment could be made a little more verbose to explain why we are removing them.

**Review by tombogle — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1291)* status: all files reviewed, 1 unresolved discussion (waiting on @ermshiperete, @jasonleenaylor, and @papeh)

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1291)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ermshiperete, @jasonleenaylor, and @tombogle)

___
*[`l10n/l10n.proj` line 41 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1291#-Nh29f4BBaVfN2Dm3pxC:-Nh2KutVDGnWfW4Tovc1:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4720c119159bef5056afe7d5412c2fe1edf03232/l10n/l10n.proj#L41)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I know those lines are just informative. Are we removing them because they cause problems or are they actually incorrect? Maybe  the comment could be made a little more verbose to explain why we are removing them.
</blockquote></details>

Done.

**Review by tombogle — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete and @jasonleenaylor)

**Pull request merged**
