### PR TITLE
Added option for alternate image metadata UI (BL-6259)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1147)

### CODE REVIEW

**Comment by tombogle** [comment]
___
*[SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs, line 365 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1147#-MysOqRqBpVdBVcEegwB:-MysOqRqBpVdBVcEegwC:b-ynvo5v) ([raw file](https://github.com/sillsdev/libpalaso/blob/241681b7f7c398ef4a9a3260359a296b542efe9e/SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs#L365)):*
> ```Smalltalk
> 			{
> 				EditMetadataActionOverride(_imageInfo.Metadata, SetNewImageMetadata);
> 				return;
> ```

Did you consider the possible merits of an event handler instead, with either an event args having a bool (Handled) that could be set or a bool return type indicating whether or not it was handled? This would allow the consumer to do something with the metadata (perhaps adjust it in some way) but still have it feed into the normal edit dialog. Depending on the current state of the metadata, it might be that a runtime decision should be made as to whether the custom editor would be required.

**Comment by tombogle** [comment]
___
*[SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs, line 349 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1147#-MysPzu12wf624442W5Q:-MysPzu12wf624442W5R:bvoarpd) ([raw file](https://github.com/sillsdev/libpalaso/blob/241681b7f7c398ef4a9a3260359a296b542efe9e/SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs#L349)):*
> ```Smalltalk
> 		/// <see cref="SetNewImageMetadata(Metadata)"/>
> 		/// </summary>
> 		public Action<Metadata, Action<Metadata>> EditMetadataActionOverride { get; set; }
> ```

In both cases, the same action is used to save the metadata. Would it be better to have the override merely return the updated metadata and let this method handle setting it? Though I suppose then, you would need to return a value indicating whether the edit had been cancelled. Of course, if a mutable copy of the metadata were passed in, then this still might be a cleaner interface.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1147)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @tombogle)

___
*[SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs, line 349 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1147#-MysPzu12wf624442W5Q:-MysRLKk730h2IuBfTsd:b-8y4h5j) ([raw file](https://github.com/sillsdev/libpalaso/blob/241681b7f7c398ef4a9a3260359a296b542efe9e/SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs#L349)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

In both cases, the same action is used to save the metadata. Would it be better to have the override merely return the updated metadata and let this method handle setting it? Though I suppose then, you would need to return a value indicating whether the edit had been cancelled. Of course, if a mutable copy of the metadata were passed in, then this still might be a cleaner interface.
</blockquote></details>

In our case, the "save" could be thought of as asynchronous. Basically, the new UI gets launched; then later when the user submits the new metadata, the save action is called.
Does that clear up the reason why this is needed? Perhaps I am the one not understanding.

**Comment by tombogle** [comment]
___
*[SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs, line 349 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1147#-MysPzu12wf624442W5Q:-MysSG4j-oYPSpMuQ5kY:bxxx4gf) ([raw file](https://github.com/sillsdev/libpalaso/blob/241681b7f7c398ef4a9a3260359a296b542efe9e/SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs#L349)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

In our case, the "save" could be thought of as asynchronous. Basically, the new UI gets launched; then later when the user submits the new metadata, the save action is called.
Does that clear up the reason why this is needed? Perhaps I am the one not understanding.
</blockquote></details>

That makes sense.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1147)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @tombogle)

___
*[SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs, line 365 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1147#-MysOqRqBpVdBVcEegwB:-MysUaGm6_MFk31Ax6mt:bxemv82) ([raw file](https://github.com/sillsdev/libpalaso/blob/241681b7f7c398ef4a9a3260359a296b542efe9e/SIL.Windows.Forms/ImageToolbox/ImageToolboxControl.cs#L365)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Did you consider the possible merits of an event handler instead, with either an event args having a bool (Handled) that could be set or a bool return type indicating whether or not it was handled? This would allow the consumer to do something with the metadata (perhaps adjust it in some way) but still have it feed into the normal edit dialog. Depending on the current state of the metadata, it might be that a runtime decision should be made as to whether the custom editor would be required. 
</blockquote></details>

Does understand the asynchronous nature of our use case clear this up, too? If not, we should discuss because I don't think I'm seeing it.

**Review by tombogle — APPROVED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1147)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
