### PR TITLE
Merge feature/LinuxSyslog into master

### PR DESCRIPTION
**Pull request by rmunn**
SyslogLogger will only run on Linux (and Linux-like systems such as OS X, as long as they have a libc library). It uses the syslog() API defined in libc to log messages to the local syslog program.

SyslogExceptionHandler likewise will only run on Linux, since it relies on SyslogLogger to log exceptions to syslog.

Since all the Unix-only code is contained in SIL.LinuxLogging.dll, there should be no problems on a Windows system, where we simply won't use that DLL.

This code has been used extensively for the past two months in the LfMerge project, and no bugs have been found so far. I believe it's ready to merge into master.

---

This change is [Review on Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/369)

### CODE REVIEW

**Comment by ddaspit** [comment]
Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[SIL.Linux.Logging/MarshallingHelper.cs, line 10 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNdxE1funZzE0PNudT:-KDNdxE1funZzE0PNudU:1971484018) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/MarshallingHelper.cs#L10)):*
These functions are only used by the SysLogger class. They can probably be moved there. 

---

*[SIL.Linux.Logging/SyslogLogger.cs, line 56 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNd1pOB_gH4lhZp5EK:-KDNd1pPK0NQEZCOyL1B:1180675399) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogLogger.cs#L56)):*
Did you check to see if these syslog functions have been implemented in Mono.Posix?

---

*[SIL.Linux.Logging/SyslogOption.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNdPO60MJIHVFRCRnn:-KDNdPO60MJIHVFRCRno:-1350313613) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogOption.cs#L7)):*
This can probably be made internal.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by ddaspit** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by rmunn** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[SIL.Linux.Logging/MarshallingHelper.cs, line 10 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNdxE1funZzE0PNudT:-KDRWiGfA52LTkVSKqaT:-1530771663) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/MarshallingHelper.cs#L10)):*
Agreed.

---

*[SIL.Linux.Logging/SyslogLogger.cs, line 56 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNd1pOB_gH4lhZp5EK:-KDRJxQmDX6ZC0wBeFKG:-2071637627) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogLogger.cs#L56)):*
I believe Mono.Posix isn't normally available on Windows unless you explicitly install it, right? When I first implemented this class, it was actually here:

https://github.com/emertechie/SyslogNet/pull/9

At the time, I didn't want to use Mono.Posix for that PR because it would have required changing their build process to build different DLLs for Windows and for Linux. That objection doesn't apply here, however, since I'm already building the SIL.Linux.Logging namespace as a separate assembly from the rest of libpalaso. So for our situation, there are really no drawbacks to using the Mono.Posix functions.

I'll rewrite the SIL.Linux.Logging class to use Syscall.syslog (et al.) from Mono.Posix instead; it means less custom code in libpalaso, and earlier failures if someone accidentally uses SIL.Linux.Logging.dll on Windows (e.g., it would fail at compile-time when Mono.Posix.dll can't be found, instead of at runtime when the P/Invoke call fails).

---

*[SIL.Linux.Logging/SyslogOption.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNdPO60MJIHVFRCRnn:-KDRRN5dTMVHzHGJVEDQ:-2012928852) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogOption.cs#L7)):*
While most users would just accept the default I've chosen (LogPid with no other flags), I could see some use cases where people might want to choose one of the other options as well, such as dual logging, to stderr as well as to syslog. So I'd prefer to keep this public to give people that option.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by ddaspit** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[SIL.Linux.Logging/SyslogOption.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNdPO60MJIHVFRCRnn:-KDSWFVp3ljCr-qEVHg5:-2061025229) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogOption.cs#L7)):*
I don't see anywhere where a caller can pass in the SyslogOption, unless I am mistaken.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by rmunn** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[SIL.Linux.Logging/SyslogLogger.cs, line 56 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNd1pOB_gH4lhZp5EK:-KDbOoGd6fciNyIO8W7r:1928086145) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogLogger.cs#L56)):*
Rewrite complete; SIL.Linux.Logging is now using the Mono.Posix DLL instead of our own P/Invoke.

---

*[SIL.Linux.Logging/SyslogOption.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNdPO60MJIHVFRCRnn:-KDbO_tSkiDAangnDlul:-596761815) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogOption.cs#L7)):*
You're right. I've revised the SyslogLogger constructor to accept a SyslogOption parameter now, defaulting to the most sensible value (LogPid alone).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by ddaspit** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[SIL.Linux.Logging/SyslogLogger.cs, line 56 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNd1pOB_gH4lhZp5EK:-KDbQarbB1Dm48XijjrU:-2118522737) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogLogger.cs#L56)):*
You can probably remove these pinvoke function declarations, since you no longer use them.

---

*[SIL.Linux.Logging/SyslogOption.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDbQx3KE2rHwBcz5oYp:-KDbQx3KE2rHwBcz5oYq:-637197942) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogOption.cs#L7)):*
Aren't these declared in Mono.Posix? Is there some reason why you can't use those?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by ddaspit** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by rmunn** [comment]
Hmm. I removed the SIL.Linux.* projects from the non-Mono configurations in Palaso.sln. Why did TeamCity still try to build SIL.Linux.Logging on Windows? It shouldn't have. I'll investigate.

**Comment by rmunn** [comment]
Ah, I see. I removed the SIL.Linux.* projects from the non-Mono configurations for the "Any CPU" platform, but missed the other platforms in Palaso.sln. Should be fixed now.

**Comment by rmunn** [comment]
Review status: 12 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[SIL.Linux.Logging/SyslogLogger.cs, line 56 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDNd1pOB_gH4lhZp5EK:-KDbm1esfUOm0LGT6es4:-184428523) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogLogger.cs#L56)):*
They've been removed now.

---

*[SIL.Linux.Logging/SyslogOption.cs, line 7 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/369#-KDbQx3KE2rHwBcz5oYp:-KDbm8M6uRhpR1lGXkLz:807624606) ([raw file](https://github.com/sillsdev/libpalaso/blob/e0d5a7b8b502a488cd811afaacdba884423ca9d4/SIL.Linux.Logging/SyslogOption.cs#L7)):*
The Mono.Posix enums have less-obvious names (like LOG_CONS instead of LogToConsoleIfErrorSendingToSyslog), and the Mono.Posix enum for SyslogFacility is actually incomplete (it's missing values 12 through 15, even though those do have meanings defined in the system `syslog.h` file). So I decided it would be better to use our own enums, copying the values from `syslog.h` to be sure they're correct.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by ddaspit** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/369)*

**Comment by rmunn** [comment]
Now superseded by PR #372, which is this PR's code (with all changes suggested by Damien during code review) squashed into a single commit for better Git history. This PR is now superseded by #372, so I'm closing this one without merging it.

**Pull request closed without merging**
