### PR TITLE
Improved the SafeInvoke method in response to JohnT's feedback

### PR DESCRIPTION
**Pull request by tombogle**
on PR #480 and added unit tests, which showed need for additional improvements to improve robustness and handle edge cases.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/486)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Nice piece of work. A few details that I think are worth improving...see what you think.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 107 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_n4sB22gYQpvlJ1NT:-Ki_n4sB22gYQpvlJ1NU:bnicvpc) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L107)):*
> ```Smalltalk
> 		/// destroyed, the action is dequeued, and an ObjectDisposedException is registered in the entry. That exception is available via
> 		/// EndInvoke, but since SafeInvoke does not return the IAsyncResult, this test cannot show that.
> 		/// Not that the first SafeInvoke in this test also tests the normal case of an action invoked asynchronously on a non-UI thread.
> ```

Not => Note?

---

*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 148 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_o1N8PA9ih06bfQ-f:-Ki_o1N9RgEvu5_RRvEm:bvmjsiw) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L148)):*
> ```Smalltalk
> 				Trace.WriteLine("SafeInvoke 1");
> 				ctrl.SafeInvoke(() => { textFromControl = ctrl.Text; ctrl.Text = "Final Text"; }, "Force synchronous.", forceSynchronous: true);
> 				Assert.AreEqual("Initial Text", textFromControl);
> ```

This surprises me. Isn't the meaning of forceSynchronous: true that the calling thread should block until the action has been done on the main thread? I would have expected this result...perhaps unreliably since a race condition is involved...with forceSynchronous:false. With it true, the action should actually take place before SafeInvoke returns on the background thread.
I don't see a test involving forceSynchronous false on a background thread...is it possible to write one that reveals the difference in behavior?

---

*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 138 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_uRohNIP_eQgY2hbn:-Ki_uRohNIP_eQgY2hbo:b-wfe0xd) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L138)):*
> ```Smalltalk
> 				// Technically, if forceSynchronous is false, we could call control.BeginInvoke, but then we'd need to wrap it in a
> 				// delegate (as above) to re-check to see if the control has been disposed. Probably not worth it. If we're already
> 				// on the UI thread, even if synchronous execution wasn't required, it should be okay.
> ```

It seems counter-intuitive to me that we would WANT the action delayed until some unpredictable later time when we're already on the thread that can perform it immediately. The purpose of forceSynchronous: false is so that a background thread doesn't have to wait for the UI thread if it doesn't matter what order things happen. If it's false, by definition the caller doesn't care whether action happens before or after SafeInvoke returns. So (unless the client has a bug) it is SURELY OK to do action() first.
So I'd make the comment something like, "Technically, if forceSynchronous is false, we could call control.BeginInvoke, but that just complicates our code (another chance for the control to get disposed before action() happens), and by definition the order in which things happen doesn't matter if we aren't forcing things to be synchronous"

---

*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 160 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_rQX2a8rr1tYetA7D:-Ki_rQX2a8rr1tYetA7E:b-sv2yzj) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L160)):*
> ```Smalltalk
> 				catch (InvalidOperationException e)
> 				{
> 					if (treatInvalidOperationExceptionAsObjectDisposedException)
> ```

This has me puzzled, so probably at least a comment is needed.
This flag is false while executing the original action, so the only way I can see for an exception to happen with it true is that control.Invoke() fails before it begins to execute the synchronousAction.
Presumably the only likely (possible?) scenario for this is that the control gets disposed between the time when we call Invoke and the time something on the UI thread attempts the action? And for some reason this produces an InvalidOperationException instead of ObjectDisposedException?

---

*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 163 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_sS-KphkMmsQzzJEy:-Ki_sS-KphkMmsQzzJEz:b-92pwe) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L163)):*
> ```Smalltalk
> 					{
> 						if (errorHandling == ErrorHandlingAction.Throw)
> 							throw new ObjectDisposedException("SafeInvoke called after the control was disposed. (" + nameForErrorReporting + ")", e);
> ```

If my understanding above is correct, technically, the problem isn't that SafeInvoke was called after the control was disposed...that would be caught above...but that the control was disposed (in a race condition) between the time SafeInvoke was called and the time the UI thread actually got around to the action.
Seems to me it is WELL worth calling out this difference in the error message...any clue to the nature of a race condition is to be treasured.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-:-Ki_tkER9ZPmq9l7I2LH:b-l2ivu0)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 107 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_n4sB22gYQpvlJ1NT:-KiaivK_YTIyMhR_fvyK:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L107)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Not => Note?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 148 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_o1N8PA9ih06bfQ-f:-Kiaj-_rPmYVlQakfNbV:b-slsyyw) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L148)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This surprises me. Isn't the meaning of forceSynchronous: true that the calling thread should block until the action has been done on the main thread? I would have expected this result...perhaps unreliably since a race condition is involved...with forceSynchronous:false. With it true, the action should actually take place before SafeInvoke returns on the background thread.
I don't see a test involving forceSynchronous false on a background thread...is it possible to write one that reveals the difference in behavior?
</blockquote></details>

If I understand your comment correctly, I think you mis-read the code. I've broken out the lines of the delegate to make it more readable. Hope that clears up the confusion. In the synchronous case, the action should be executed immediately before SafeInvoke returns, so the textFromControl variable will be set (to the *initial* value). The only "normal" test for asynchronous SafeInvoke was buried inside a non-normal test. I've broken it out into its  own unit test now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 138 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_uRohNIP_eQgY2hbn:-KiakzH5HeqtkTzBg_Tz:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L138)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It seems counter-intuitive to me that we would WANT the action delayed until some unpredictable later time when we're already on the thread that can perform it immediately. The purpose of forceSynchronous: false is so that a background thread doesn't have to wait for the UI thread if it doesn't matter what order things happen. If it's false, by definition the caller doesn't care whether action happens before or after SafeInvoke returns. So (unless the client has a bug) it is SURELY OK to do action() first.
So I'd make the comment something like, "Technically, if forceSynchronous is false, we could call control.BeginInvoke, but that just complicates our code (another chance for the control to get disposed before action() happens), and by definition the order in which things happen doesn't matter if we aren't forcing things to be synchronous"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 160 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_rQX2a8rr1tYetA7D:-Kial4HdcuVzEeFRreEH:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L160)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This has me puzzled, so probably at least a comment is needed.
This flag is false while executing the original action, so the only way I can see for an exception to happen with it true is that control.Invoke() fails before it begins to execute the synchronousAction.
Presumably the only likely (possible?) scenario for this is that the control gets disposed between the time when we call Invoke and the time something on the UI thread attempts the action? And for some reason this produces an InvalidOperationException instead of ObjectDisposedException?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 163 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_sS-KphkMmsQzzJEy:-KialAF1wURRDOyHbclh:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L163)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

If my understanding above is correct, technically, the problem isn't that SafeInvoke was called after the control was disposed...that would be caught above...but that the control was disposed (in a race condition) between the time SafeInvoke was called and the time the UI thread actually got around to the action.
Seems to me it is WELL worth calling out this difference in the error message...any clue to the nature of a race condition is to be treasured.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by JohnThomson** [comment]
Much improved...couple of suggestions if you patience isn't exhausted. If it is, I wouldn't strongly object to merging as-is.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 148 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_o1N8PA9ih06bfQ-f:-Kiern0eKJpdsiVvkN8m:bkhar5y) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L148)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

If I understand your comment correctly, I think you mis-read the code. I've broken out the lines of the delegate to make it more readable. Hope that clears up the confusion. In the synchronous case, the action should be executed immediately before SafeInvoke returns, so the textFromControl variable will be set (to the *initial* value). The only "normal" test for asynchronous SafeInvoke was buried inside a non-normal test. I've broken it out into its  own unit test now.
</blockquote></details>

Yes, I mis-read. See new comment for what I think threw me off.

---

*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 158 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Kier-DtQuBsn4AZAr6Z:-Kier-DtQuBsn4AZAr6_:bterpvm) ([raw file](https://github.com/sillsdev/libpalaso/blob/673c0871536ec5948b9c381b1f4fd8cea966930d/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L158)):*
> ```Smalltalk
> 				Trace.WriteLine("SafeInvoke 1");
> 				ctrl.SafeInvoke(() => { Trace.WriteLine("invoking 1"); textFromControl = ctrl.Text; ctrl.Text = "Final Text"; }, "Getting initial value and resetting control text.");
> 				Assert.IsNull(textFromControl);
> ```

This one is actually a race condition, isn't it? Nothing guarantees that the system won't choose to run the async block we are invoking before it returns control to our thread. Or does the way Invoke works prevents it from running until DoEvents()? If it's not a race condition a comment explaining how you know that would be nice. (Sorry to keep complaining after you already went out of your way to add this test after my mis-reading.)

---

*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 184 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Kiepcl6LZsqS0IQr8Mj:-Kiepcl6LZsqS0IQr8Mk:b-7wvle7) ([raw file](https://github.com/sillsdev/libpalaso/blob/673c0871536ec5948b9c381b1f4fd8cea966930d/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L184)):*
> ```Smalltalk
> 					ctrl.Text = "Final Text";
> 				}, "Force synchronous.", forceSynchronous: true);
> 				Assert.AreEqual("Initial Text", textFromControl, "Since the invoke was done synchronously, this should have been set before SafeInvoke returned.");
> ```

Hmm, I think the thing that threw me off is that the most obvious thing the SafeInvoke action does is set something to "Final Text" and here right afterwards you are testing that the value of something is "Initial Text". A test that something is "Initial" very strongly suggests testing that a change has NOT happened yet. The comment on the Assert helps. But you could equally (or as well) test that ctrl.Text Is.EqualTo("Final Text") which would be much more obviously looking for a change done by the safeInvoke.
Is there any way to be sure this passes because the synchronous call was properly forced rather then just because a race condition usually turns out the way we want? (I hate threading!)

---

*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 160 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_rQX2a8rr1tYetA7D:-KiesZMPqBKGCztLNllM:b-m2gq6) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L160)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice job, thanks.

---

*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 173 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-KiesseX5wZMSZwYOYWg:-KiesseX5wZMSZwYOYWh:b-z3doj7) ([raw file](https://github.com/sillsdev/libpalaso/blob/673c0871536ec5948b9c381b1f4fd8cea966930d/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L173)):*
> ```Smalltalk
> 						if (errorHandling == ErrorHandlingAction.Throw)
> 							throw new ObjectDisposedException("Control was disposed before " + (forceSynchronous ? "Invoke" : "BeginInvoke") +
> 								" could be called. To suppress this kind of race-condition error, call SafeInvoke with IgnoreIfDisposed. (" + nameForErrorReporting + ")", e);
> ```

Alternatively, you could avoid invoking code on controls you are about to dispose :-). (No, I don't think that needs to be said.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-:-Kiet57qlkS37oBPS_dJ:b-lm41bg)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 158 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Kier-DtQuBsn4AZAr6Z:-Kijkuk88AquVgJqS2Ps:b-1918dc) ([raw file](https://github.com/sillsdev/libpalaso/blob/673c0871536ec5948b9c381b1f4fd8cea966930d/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L158)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This one is actually a race condition, isn't it? Nothing guarantees that the system won't choose to run the async block we are invoking before it returns control to our thread. Or does the way Invoke works prevents it from running until DoEvents()? If it's not a race condition a comment explaining how you know that would be nice. (Sorry to keep complaining after you already went out of your way to add this test after my mis-reading.)
</blockquote></details>

Never fear. My patience is inexhaustible! :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 184 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Kiepcl6LZsqS0IQr8Mj:-KijrA2eOjK1uoP_zPX7:b-x9jufe) ([raw file](https://github.com/sillsdev/libpalaso/blob/673c0871536ec5948b9c381b1f4fd8cea966930d/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L184)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Hmm, I think the thing that threw me off is that the most obvious thing the SafeInvoke action does is set something to "Final Text" and here right afterwards you are testing that the value of something is "Initial Text". A test that something is "Initial" very strongly suggests testing that a change has NOT happened yet. The comment on the Assert helps. But you could equally (or as well) test that ctrl.Text Is.EqualTo("Final Text") which would be much more obviously looking for a change done by the safeInvoke.
Is there any way to be sure this passes because the synchronous call was properly forced rather then just because a race condition usually turns out the way we want? (I hate threading!)
</blockquote></details>

Done. I added an Assert check for both changes to avoid confusion, and put in a few Thread.Sleep calls in the invoked code to demonstrate that the synchronous call blocks both threads so that neither one can do anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-:-KikL4QbWkUqQKW0uSc7:bnfp4nl)*

**Comment by JohnThomson** [comment]
Wonder whether we should seek a review by someone like Eberhard or Damien that's smart about threading. Otherwise, I think you're good to merge.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-:-KikLBDjsMtkOm7RAWjN:b1e1pp2)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 173 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-KiesseX5wZMSZwYOYWg:-Kj5e74iJP-tTXkPSC4y:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/673c0871536ec5948b9c381b1f4fd8cea966930d/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L173)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Alternatively, you could avoid invoking code on controls you are about to dispose :-). (No, I don't think that needs to be said.)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms/Extensions/ControlExtensions.cs, line 160 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Ki_rQX2a8rr1tYetA7D:-Kj5eERe9M_EDGIcrv16:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/374a8489ff8b9cae7d800f277b52bd1e14e3d7a6/SIL.Windows.Forms/Extensions/ControlExtensions.cs#L160)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Nice job, thanks.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486)*

**Comment by JohnThomson** [comment]
:lgtm: with two very minor comment suggestions...Feel free to merge after (or even without) fixing them.

---

Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 187 at r4](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Kj8nfymOUy9_ARrJMjH:-Kj8nfynV8_JZ6wjQBql:b-swvql4) ([raw file](https://github.com/sillsdev/libpalaso/blob/b3b682b34ed533f9291887d50631af5a15760214/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L187)):*
> ```Smalltalk
> 			Assert.IsFalse(resultOfSafeInvokeCall.CompletedSynchronously, "Expected asynchronous invocation of action.");
> 			Assert.IsTrue(resultOfSafeInvokeCall.IsCompleted, "Asynchronous action should have completed.");
> 			Assert.IsNull(_threadException, "If this is not null, then the second call to SafeInvoke must have thrown an exception.");
> ```

Don't think we have a second call in this test?

---

*[SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs, line 220 at r4](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-Kj8npp1ULdxxKjUjYqJ:-Kj8npp2F_yGyVQIzRfh:b1vbhw1) ([raw file](https://github.com/sillsdev/libpalaso/blob/b3b682b34ed533f9291887d50631af5a15760214/SIL.Windows.Forms.Tests/Extensions/ControlExtensionsTests.cs#L220)):*
> ```Smalltalk
> 				Application.DoEvents(); // Even though the SafeInvoke call is synchronous, the worker thread obviously isn't, so we need to wait for it to finish.
> 			Assert.AreEqual("Final Text", _control.Text, "This just proves that we don't get here without having executed the worker thread's code.");
> 			Assert.IsNull(resultOfSafeInvokeCall, "When SafeInvoke results in a synchronous call, not IAsyncResult should be returned.");
> ```

not => no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/486#-:-Kj8pLPeeCM3IAeKTjkd:bf0hd3i)*

**Pull request merged**
