### PR TITLE
Changes need to get Bloom working again after merge

### PR DESCRIPTION
**Pull request by JohnThomson**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/305)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/305#-K29Npfu8p1xVWoL-FMY)** ([raw file](https://github.com/sillsdev/libpalaso/blob/7c33495d7036d3493f41ea2324a9dd36f274ebdd/SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs#L31)):</sup>
I'm surely just not seeing it, but are these two are equivalent? Where does the != idea go? Then again, the intention of the original code is not clear to me either. So it must be just me!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/305)

**Comment by hatton** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/305)

**Comment by JohnThomson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/305#-K29Npfu8p1xVWoL-FMY)** ([raw file](https://github.com/sillsdev/libpalaso/blob/7c33495d7036d3493f41ea2324a9dd36f274ebdd/SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs#L31)):</sup>
This change is a bug fix. It's not meant to be equivalent to the old code. Somewhere the old meaning of this method got lost, and no one realized because Bloom was (perhaps) the only client.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/305)

**Comment by JohnThomson** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/305#-K29Npfu8p1xVWoL-FMY)** ([raw file](https://github.com/sillsdev/libpalaso/blob/7c33495d7036d3493f41ea2324a9dd36f274ebdd/SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs#L31)):</sup>
Probably my fault for not creating unit tests when I (probably) first created the method. I'm surprised I didn't, but it was originally a quick hack to get access to a non-public data structure, IIRC. Now the relevant data is public. Maybe I should just delete it. But that might break some other client. OTOH, I don't feel very inclined to start making unit tests now for something I think is probably unused anywhere.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/305)

**Comment by hatton** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/305#-K29Npfu8p1xVWoL-FMY)** ([raw file](https://github.com/sillsdev/libpalaso/blob/7c33495d7036d3493f41ea2324a9dd36f274ebdd/SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs#L31)):</sup>
I think our options are add a unit test or delete it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/305)

**Comment by JohnThomson** [comment]
Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs, line 31 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/305#-K29Npfu8p1xVWoL-FMY)** ([raw file](https://github.com/sillsdev/libpalaso/blob/7c33495d7036d3493f41ea2324a9dd36f274ebdd/SIL.Windows.Forms.WritingSystems/LanguageLookupModel.cs#L31)):</sup>
I deleted it.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/305)

**Comment by hatton** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/305)

**Pull request merged**
