### PR TITLE
Use CLDR Numbering systems but allow for custom options

### PR DESCRIPTION
**Pull request by jasonleenaylor**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/724)

### CODE REVIEW

**Comment by JohnThomson** [comment]
Looks mostly OK...minor quibbles...except that moving a pre-existing thing into its own class (and changing a public method name) are breaking changes, so presumably we need a new major version number for LibPalaso?

---

Reviewed 23 of 23 files at r1.
Review status: all files reviewed, 17 unresolved discussions (waiting on @jasonleenaylor, @ddaspit, @mhosken, and @andrew-polk)

---

*[SIL.Windows.Forms.WritingSystems/WSKeyboardControl.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFN_Sn_CCmV9nP5Ru--:-LFN_Sn_CCmV9nP5Ru-0:b-u9hmj7) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.Windows.Forms.WritingSystems/WSKeyboardControl.cs#L51)):*
> ```Smalltalk
> 			if (LicenseManager.UsageMode != LicenseUsageMode.Designtime)
> 			{
> 				_keymanConfigurationLink.Visible &= KeyboardController.HasSecondaryKeyboardSetupApplication;
> ```

This is suspicious because the LHS seems much more keyman-specific than the RHS. Sure the name and behavior make sense?
Also: it's not obvious how this change relates to the purpose of the PR, which has to do with numbering systems.

---

*[SIL.WritingSystems/CLDRNumberingSystems.cs, line 18 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNaWOH8YyPx_h3_1tW:-LFNaWOI1vZxvi8PP8Yz:bpv5ghc) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/CLDRNumberingSystems.cs#L18)):*
> ```Smalltalk
> 	public static class CLDRNumberingSystems
> 	{
> 		private static readonly Dictionary<string, string> _numberingSystemsDictionary = new Dictionary<string, string>();
> ```

Deserves a comment indicating what the keys and values are. Or a better name (_mapDigitsToId?)

---

*[SIL.WritingSystems/CLDRNumberingSystems.cs, line 26 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNdMiGEJADd3ypNCYJ:-LFNdMiGEJADd3ypNCYK:bqqw14a) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/CLDRNumberingSystems.cs#L26)):*
> ```Smalltalk
> 		}
> 
> 		public static NumberingSystemDefinition Default { get; }
> ```

It feels odd that we use a NumberingSystemDefinition object for the default, but not for any of the other numbering systems.

---

*[SIL.WritingSystems/CLDRNumberingSystems.cs, line 44 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNb3gfAP3axSyCJH4F:-LFNb3gfAP3axSyCJH4G:b-n8z0tg) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/CLDRNumberingSystems.cs#L44)):*
> ```Smalltalk
> 		}
> 
> 		public static string GetDigitsForID(string id)
> ```

Any reason to think this needs good performance? If so it would be easy to add a dictionary the other way.
Do we expect this mapping to have unique keys and values? If not, does it matter which key we get for a value that has duplicate ones?

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 41 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNccev-VFj537MPCDh:-LFNccev-VFj537MPCDi:bqj3ida) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L41)):*
> ```Smalltalk
> 		/// That information is stored in the "VersionNumber" property.
> 		/// </summary>
> 		public const int CurrentLdmlLibraryVersion = 3;
> ```

This would be a breaking change requiring a new major version of LibPalaso, right? Should it be postponed until we have a number of such changes we want to push out?

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 688 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNglmU9bIGjVqQbU0P:-LFNglmU9bIGjVqQbU0Q:b4gsslp) ([raw file](https://github.com/sillsdev/libpalaso/blob/ae3492eea2106bcdef9cf0969ee71a19cf98e79c/SIL.WritingSystems/LdmlDataMapper.cs#L688)):*
> ```Smalltalk
> 					foreach (char charItem in digits)
> 						csd.Characters.Add(charItem.ToString(CultureInfo.InvariantCulture));
> 					ws.CharacterSets.Add(csd);
> ```

Is it a breaking change that a writing system's digits are no longer guaranteed to be one of its character sets?

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 702 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNe9Fj3FaTWx--rBPL:-LFNe9Fj3FaTWx--rBPM:b-98vn90) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L702)):*
> ```Smalltalk
> 					{
> 						ws.NumberingSystem = new NumberingSystemDefinition(cldrSysId);
> 					}
> ```

This logic ("Get me a NumberingSystemDefinition with these digits") feels to me as if it belongs in CLDRNumberingSystems

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 741 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNgCHK2z0cAIEjIOHn:-LFNgCHK2z0cAIEjIOHo:b16n0g6) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L741)):*
> ```Smalltalk
> 			}
> 			digits = parts[1];
> 			return true;
> ```

I guess this is OK, though I think it could be simpler and more robust with a Regex. This, for example, will happily parse something missing the final paren. Is white space definitely not allowed? because other ( 0123456789 ) would not parse...

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 1243 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNhm4iAMNUfmEdk7e6:-LFNhm4iAMNUfmEdk7e7:b-wm42k) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L1243)):*
> ```Smalltalk
> 		}
> 
> 		private void WriteNumbersElement(XElement numbersElem, WritingSystemDefinition ws)
> ```

This is an odd name for a method that does not appear to write the element anywhere but DOES modify it. Wants a better name, and a comment explaining what it is doing and why.

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 1248 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNjCHc7E2KvNCJMSpM:-LFNjCHc7E2KvNCJMSpN:b9ijc5i) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L1248)):*
> ```Smalltalk
> 			Debug.Assert(ws != null);
> 
> 			// Save off defaultNumberingSystem if it exists.
> ```

Is this comment still right? Seems we now remove it, not save it.

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 10 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNjhPD1zB2WPhV64rb:-LFNjhPD1zB2WPhV64rc:brsiuwo) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L10)):*
> ```Smalltalk
> {
> 	[DebuggerDisplay("{_id}:{_characters}")]
> 	public class NumberingSystemDefinition : DefinitionBase<NumberingSystemDefinition>,
> ```

class comment please

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 16 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNm7sr6s8Y_3MN0Nr6:-LFNm7sr6s8Y_3MN0Nr7:b9t5gmm) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L16)):*
> ```Smalltalk
> 
> 		public const string CustomNumbersMarker = "other";
> 		private string _characters;
> ```

Can this be made readonly too?

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 35 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNkPWxE1eGQakszBGx:-LFNkPWxE1eGQakszBGy:b15mxh6) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L35)):*
> ```Smalltalk
> 				throw new ArgumentException($"{id} is not defined in the CLDR", nameof(id));
> 			_id = id;
> 			_characters = CLDRNumberingSystems.GetDigitsForID(id);
> ```

_characters = digits?

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 45 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNkiqS03okc7XmTKDY:-LFNkiqT7k5A893IhdlW:b-bpgyb9) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L45)):*
> ```Smalltalk
> 		public string Id => IsCustom ? $"{CustomNumbersMarker}({_characters})" : _id;
> 
> 		public bool Equals(NumberingSystemDefinition other)
> ```

Unusual to do this and not override Equals(object) and GetHashCode() and make sure == and != will behave as expected?

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 64 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNlhY9ASyB55Pdr2gi:-LFNlhY9ASyB55Pdr2gj:b-id0q99) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L64)):*
> ```Smalltalk
> 		public override bool ValueEquals(NumberingSystemDefinition other)
> 		{
> 			return Id.Equals(other.Id);
> ```

Feels a bit fragile...what guarantees that nothing creates two of these with the same ID and different digits?

---

*[SIL.WritingSystems/WritingSystemDefinition.cs, line 176 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNmGyXB_ewdYpKpPN1:-LFNmGyXB_ewdYpKpPN2:bob6263) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/WritingSystemDefinition.cs#L176)):*
> ```Smalltalk
> 				_defaultCollation = _collations[ws._collations.IndexOf(ws._defaultCollation)];
> 			_characterSets = new KeyedBulkObservableList<string, CharacterSetDefinition>(ws._characterSets.CloneItems(), csd => csd.Type);
> 			_numberingSystem = new NumberingSystemDefinition(ws.NumberingSystem);
> ```

Why do we need a clone? Aren't NumberingSystemDefinitions immutable?

---

*[SIL.WritingSystems.Tests/CLDRNumberingSystemsTests.cs, line 34 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNmjnB51M9COc5hGey:-LFNmjnB51M9COc5hGez:b5zro1r) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems.Tests/CLDRNumberingSystemsTests.cs#L34)):*
> ```Smalltalk
> 		{
> 			Assert.AreEqual("0123456789", CLDRNumberingSystems.GetDigitsForID("latn"));
> 		}
> ```

Couldn't we have a couple of non-latin test cases?

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/724#-:-LFNoMIX96FAeZWTYAy_:b9lpf6w)*

**Comment by jasonleenaylor** [comment]
I'm reasonably confident the only thing that will break with this change is a test in WeSay, if I promise to fix it can we skip the major version bump?

---

Review status: 15 of 23 files reviewed, 17 unresolved discussions (waiting on @JohnThomson, @jasonleenaylor, @ddaspit, @mhosken, and @andrew-polk)

---

*[SIL.Windows.Forms.WritingSystems/WSKeyboardControl.cs, line 51 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFN_Sn_CCmV9nP5Ru--:-LFOUu6h6Hb0QFlamESc:bo8wm9q) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.Windows.Forms.WritingSystems/WSKeyboardControl.cs#L51)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is suspicious because the LHS seems much more keyman-specific than the RHS. Sure the name and behavior make sense?
Also: it's not obvious how this change relates to the purpose of the PR, which has to do with numbering systems.
</blockquote></details>

It isn't obvious in reviewable, but I've only added the condition. The _keymanConfigurationLink line predates this change. I needed to check the LicenseManager to allow the WritingSystemProperties dialog to work in the Designer.

---

*[SIL.WritingSystems/CLDRNumberingSystems.cs, line 18 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNaWOH8YyPx_h3_1tW:-LFOVQaF9tG56eHG2y1x:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/CLDRNumberingSystems.cs#L18)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Deserves a comment indicating what the keys and values are. Or a better name (_mapDigitsToId?)
</blockquote></details>

Done.

---

*[SIL.WritingSystems/CLDRNumberingSystems.cs, line 26 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNdMiGEJADd3ypNCYJ:-LFOj_WG435VS66owkU1:b-pulo2s) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/CLDRNumberingSystems.cs#L26)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It feels odd that we use a NumberingSystemDefinition object for the default, but not for any of the other numbering systems.
</blockquote></details>

True. This it is really just a convenience property but it seemed that this class should rightly declare what the default is. However moving the default to NumberingSystemDefinition its self makes this class responsible only for dealing with the CLDR data.

---

*[SIL.WritingSystems/CLDRNumberingSystems.cs, line 44 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNb3gfAP3axSyCJH4F:-LFOVaKr3vMJqtfVHTzw:bfs8jwo) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/CLDRNumberingSystems.cs#L44)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Any reason to think this needs good performance? If so it would be easy to add a dictionary the other way.
Do we expect this mapping to have unique keys and values? If not, does it matter which key we get for a value that has duplicate ones?
</blockquote></details>

It is unlikely there will ever be more than 20-30 items in the dictionary, so performance is a non-issue. The keys and values will be unique.

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 41 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNccev-VFj537MPCDh:-LFOVyD2AQZrDRIsgrui:b9sqvxk) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L41)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This would be a breaking change requiring a new major version of LibPalaso, right? Should it be postponed until we have a number of such changes we want to push out?
</blockquote></details>

Technically yes, but practically no.  In all our sillsdev repos only a single WeSay test accesses this property.

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 688 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNglmU9bIGjVqQbU0P:-LFOk2-j7BB0f8MgDbQo:b-wfr869) ([raw file](https://github.com/sillsdev/libpalaso/blob/ae3492eea2106bcdef9cf0969ee71a19cf98e79c/SIL.WritingSystems/LdmlDataMapper.cs#L688)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is it a breaking change that a writing system's digits are no longer guaranteed to be one of its character sets?
</blockquote></details>

I wouldn't consider it breaking since it was always an optional field. FieldWorks is the only program that would even look for it, and it gracefully handled the absence. I have a FieldWorks change to work with this new code about ready to go.

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 702 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNe9Fj3FaTWx--rBPL:-LFOpcVSC4S04iA0OLc7:b3u0fsk) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L702)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This logic ("Get me a NumberingSystemDefinition with these digits") feels to me as if it belongs in CLDRNumberingSystems
</blockquote></details>

I respectfully disagree, I've moved the Default from CLDRNumberingSystems to NumberingSystemDefinition.

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 741 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNgCHK2z0cAIEjIOHn:-LFSkiUj2KDVULtUH7Iv:b-as69z2) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L741)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I guess this is OK, though I think it could be simpler and more robust with a Regex. This, for example, will happily parse something missing the final paren. Is white space definitely not allowed? because other ( 0123456789 ) would not parse...
</blockquote></details>

Whitespace is not generated by us, and we expect noone else to generate this particular content. Written as a Regex now.

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 1243 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNhm4iAMNUfmEdk7e6:-LFOrOIs-0n5EDTIDW2o:b-jrdzxg) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L1243)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is an odd name for a method that does not appear to write the element anywhere but DOES modify it. Wants a better name, and a comment explaining what it is doing and why.
</blockquote></details>

Well, it does match all the other Write*Element methods in this file. I'll add the comment. Then someone can use my comment for this method to understand the rest of the file. :-)

---

*[SIL.WritingSystems/LdmlDataMapper.cs, line 1248 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNjCHc7E2KvNCJMSpM:-LFShEIt5i8uTLchjew9:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/LdmlDataMapper.cs#L1248)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this comment still right? Seems we now remove it, not save it.
</blockquote></details>

Done.

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 10 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNjhPD1zB2WPhV64rb:-LFShXO50p9vhihlMaew:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

class comment please
</blockquote></details>

Done.

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 16 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNm7sr6s8Y_3MN0Nr6:-LFShXfo3ldhbewWrFoZ:b-24z6ma) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L16)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Can this be made readonly too?
</blockquote></details>

Not with the way that the custom definition is currently implemented.

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 35 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNkPWxE1eGQakszBGx:-LFSiUR8-mZIz3WJAKbS:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L35)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

_characters = digits?
</blockquote></details>

Done.

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 45 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNkiqS03okc7XmTKDY:-LFSienaDE4cEpcsYZbQ:b-quqsm0) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L45)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Unusual to do this and not override Equals(object) and GetHashCode() and make sure == and != will behave as expected?
</blockquote></details>

I only added it because a test of the WritingSystemDefinition clone needed it, but I may as well.

---

*[SIL.WritingSystems/NumberingSystemDefinition.cs, line 64 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNlhY9ASyB55Pdr2gi:-LFOgM-zBqMhAD3ArLbl:b-ifh998) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/NumberingSystemDefinition.cs#L64)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Feels a bit fragile...what guarantees that nothing creates two of these with the same ID and different digits?
</blockquote></details>

I'm counting on the CLDR folk to pitch a fit and reject any such proposal.

---

*[SIL.WritingSystems/WritingSystemDefinition.cs, line 176 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNmGyXB_ewdYpKpPN1:-LFOfkiQC-mz85Nb_lAX:bgp5ok5) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems/WritingSystemDefinition.cs#L176)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why do we need a clone? Aren't NumberingSystemDefinitions immutable?
</blockquote></details>

Almost. The custom NumberingSystemDefinitions *are* mutable.

---

*[SIL.WritingSystems.Tests/CLDRNumberingSystemsTests.cs, line 34 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/724#-LFNmjnB51M9COc5hGey:-LFOg5dlASQcwLXEsqZp:bvvj2ka) ([raw file](https://github.com/sillsdev/libpalaso/blob/c804244644379b4a8c17dc5cf582154f1108c9bb/SIL.WritingSystems.Tests/CLDRNumberingSystemsTests.cs#L34)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Couldn't we have a couple of non-latin test cases?
</blockquote></details>

We could, but it verifies nothing extra here. There are some non-latin test cases in the LDML round tripping which I think suffice.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/724#-:-LFOjCUuAXQgjpn_kvyN:b518yfy)*

**Comment by JohnThomson** [comment]
:lgtm:. You get (most of) the flak if you break something :-)

---

Review status: 15 of 23 files reviewed, all discussions resolved (waiting on @JohnThomson, @ddaspit, @mhosken, and @andrew-polk)

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/724#-:-LFTUeqbANkt1mPzZfYl:beh0xqz)*

**Comment by JohnThomson** [comment]
However, I'll let you take a look at the failing checks before merging. And looks like it needs rebasing.

**Pull request merged**
