### PR TITLE
Remove alternative names from language chooser

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/476)

### CODE REVIEW

**Comment by megahirt** [comment]
It looks like this PR includes commits from PR 475 as well.  Can these be separated?

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/476#-:-Khz3D8-c-In_b2D3S0f:b-y4q4ga)*

**Comment by glasseyes** [comment]
Reviewed 4 of 6 files at r1.
Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/476)*

**Comment by JohnThomson** [comment]
Will rebase/redo when the previous PRs are merged. If I simply separate them they will have to be rebased anyway since the same files are changed.

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/476#-:-Ki0ZGYSA8vKSaBHEkWj:bgb0mzh)*

**Comment by JohnThomson** [comment]
Don't merge...needs rework following https://github.com/sillsdev/libpalaso/pull/478

**Comment by JohnThomson** [comment]
Replaced with https://github.com/sillsdev/libpalaso/pull/491

**Pull request closed without merging**
