### PR TITLE
If the IGO option is chosen for a CC license, use version number "3.0"

### PR DESCRIPTION
**Pull request by hatton**
Also specify what we think a version number should look like, regardless of locale. Sorry, kinda two-in-one here, but both version related.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/417)

### CODE REVIEW

**Comment by gmartin7** [comment]
LGTM.

**Comment by StephenMcConnel** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/417#-:-KXfoifWdHufLlH5e7IQ:bnfp4nl)*

**Comment by ermshiperete** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs, line 15 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/417#-KXfrq2WERQqZLxEnt_x:-KXfrq2WERQqZLxEnt_y:bs0uuyt) ([raw file](https://github.com/sillsdev/libpalaso/blob/bad02f496db0477a94e18f0283a986cc7b6af733/SIL.Windows.Forms.Tests/ClearShare/CreativeCommonsLicenseTests.cs#L15)):*
> ```Smalltalk
> 		public void Setup()
> 		{
> 			Thread.CurrentThread.CurrentCulture = new CultureInfo("sv-SE"); //sweden, which uses commas for decimal  point (regression test)
> ```

It might be better to set [`[SetCulture("sv-SE")]`](http://www.nunit.org/index.php?p=setCulture&r=2.6.4) on the fixture. That way the culture gets reset after this test fixture runs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/417)*

**Comment by StephenMcConnel** [comment]
This pull request does appear to fix http://issues.bloomlibrary.org/youtrack/issue/BL-4040 satisfactorily.

**Pull request merged**
