### PR TITLE
Upgraded to Naudio 1.8.4

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/623)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Media/SIL.Media.csproj, line 301 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/623#-L6MuDtw5hk9XU0v4S-P:-L6MuDtw5hk9XU0v4S-Q:b-6aljct) ([raw file](https://github.com/sillsdev/libpalaso/blob/2c1afd6fc53d86d516faa24dc1c3dc1d9dc873b1/SIL.Media/SIL.Media.csproj#L301)):*
> ```XML
>     <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
>   </PropertyGroup>
>   <ItemGroup Condition="'$(Configuration)' == 'Debug' Or '$(Configuration)' == 'DebugStrongName'">
> ```

This used to be conditional on Debug or DebugStrongName even though the same version was used for Release.

But without another change, Release is still using 1.8.3. I assume you can just take out the conditions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623)*

**Comment by tombogle** [comment]
*[SIL.Media/SIL.Media.csproj, line 301 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/623#-L6MuDtw5hk9XU0v4S-P:-L6MxMEJL-MML_C23Klc:b-kfuxu3) ([raw file](https://github.com/sillsdev/libpalaso/blob/2c1afd6fc53d86d516faa24dc1c3dc1d9dc873b1/SIL.Media/SIL.Media.csproj#L301)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This used to be conditional on Debug or DebugStrongName even though the same version was used for Release.

But without another change, Release is still using 1.8.3. I assume you can just take out the conditions.
</blockquote></details>

Nuget/VS made that change automatically. I'm thinking maybe that conditional logic was to prevent referencing NAudio on Linux builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623#-:-L6MyzYGxxqPA_kKzCAl:bnfp4nl)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623)*

**Comment by glasseyes** [comment]
*[SIL.Windows.Forms/SIL.Windows.Forms.csproj, line 389 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/623#-L6QYfXKGVAzc-S6zjru:-L6QYfXLCqsmZjcb97Oc:bsmiuek) ([raw file](https://github.com/sillsdev/libpalaso/blob/279848e7879fe19fc45282a46ef83b0997c217dd/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L389)):*
> ```XML
>     <Reference Include="Microsoft.VisualBasic" Condition="'$(OS)'=='Windows_NT'" />
>     <Reference Include="NAudio, Version=1.8.4.0, Culture=neutral, processorArchitecture=MSIL">
>       <HintPath>..\packages\NAudio.1.8.4\lib\net35\NAudio.dll</HintPath>
> ```

Why was this moved from the Windows specific references to the general references? Now it is going to be pulled into Linux builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623)*

**Comment by glasseyes** [comment]
*[SIL.Windows.Forms/SIL.Windows.Forms.csproj, line 328 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/623#-L6QZ0uVOC2zi7I0RjH8:-L6QZ0uVOC2zi7I0RjH9:bdcp57d) ([raw file](https://github.com/sillsdev/libpalaso/blob/279848e7879fe19fc45282a46ef83b0997c217dd/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L328)):*
> ```XML
>     </Reference>
>     <Reference Include="NAudio">
>       <HintPath>..\packages\NAudio.1.8.3\lib\NAudio.dll</HintPath>
> ```

This one is still here so it may cause confusion/problems

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623)*

**Comment by andrew-polk** [comment]
@glasseyes, good catch(es). @tombogle, I assume you've been notified of his comments?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623#-:-L6RaeS14WXrgUJJl4PR:bhe81p1)*

**Comment by tombogle** [comment]
*[SIL.Windows.Forms/SIL.Windows.Forms.csproj, line 389 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/623#-L6QYfXKGVAzc-S6zjru:-L6S-5r3b7rlAHxWgNCB:bwdh1vh) ([raw file](https://github.com/sillsdev/libpalaso/blob/279848e7879fe19fc45282a46ef83b0997c217dd/SIL.Windows.Forms/SIL.Windows.Forms.csproj#L389)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

Why was this moved from the Windows specific references to the general references? Now it is going to be pulled into Linux builds.
</blockquote></details>

oops! I'll fix it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/623)*

**Comment by tombogle** [comment]
New PR to fix the things DG caught: https://github.com/sillsdev/libpalaso/pull/626

**Pull request merged**
