### PR TITLE
Move common properties to Directory.Build.props

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1074)

### CODE REVIEW

**Review by papeh — CHANGES_REQUESTED** [review]
> Reviewed 50 of 50 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1074)* status: all files reviewed, 3 unresolved discussions (waiting on @ermshiperete)

___
*[SIL.WritingSystems/Sldr.cs, line 212 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZndnNNBqyo63_Fk7Gw:-MZndnNNBqyo63_Fk7Gx:b-a3dyql) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/SIL.WritingSystems/Sldr.cs#L212)):*
> `out tempString`

`out _`
___
*[SIL.WritingSystems.Tests/SldrTests.cs, line 271 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZniqno8RPgLy84-0TP:-MZniqnpC49jvIvOZLN-:bgv6uue) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/SIL.WritingSystems.Tests/SldrTests.cs#L271)):*
> ```Smalltalk
> 			if (sldrStatus == SldrStatus.UnableToConnectToSldr)
> 				Assert.Ignore("Ignored because SLDR is offline.");
> 			// Call a second time, this should use the Cache now. However, this still reports it as FromSldr
> ```

this seems worth investigating
___
*[TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj, line 9 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZnjYu30-h2ynJdHhQW:-MZnjYu30-h2ynJdHhQX:b-9bazk7) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj#L9)):*
> ```XML
>     <Description>SIL.Windows.Forms.TestApp test app</Description>
>     <OutputPath>../../output/$(Configuration)</OutputPath>
>     <SignAssembly>false</SignAssembly>
> ```

should other test apps be unsigned, too?

**Review by ermshiperete — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1074)* status: all files reviewed, 3 unresolved discussions (waiting on @jasonleenaylor and @papeh)

___
*[SIL.WritingSystems/Sldr.cs, line 212 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZndnNNBqyo63_Fk7Gw:-MZroH2C6l95lpON1EL0:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/SIL.WritingSystems/Sldr.cs#L212)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

> `out tempString`

`out _`
</blockquote></details>

Done.
___
*[SIL.WritingSystems.Tests/SldrTests.cs, line 271 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZniqno8RPgLy84-0TP:-MZrpmJ-9OgDJKub4TMp:b-7ugeww) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/SIL.WritingSystems.Tests/SldrTests.cs#L271)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

this seems worth investigating
</blockquote></details>

This comment got added in commit [64c68401cb5f6405f6e427792ec31228a1e6bc5f](https://github.com/sillsdev/libpalaso/commit/64c68401cb5f6405f6e427792ec31228a1e6bc5f) (February 2020), but I don't see the cache working that way. AFAICT the code intentionally returns `FromSldr`, so I'm not sure what to do about this comment and assert. Maybe @jasonleenaylor  could take a look if he remembers why he added `Assert.That(sldrStatus, Is.EqualTo(SldrStatus.FromCache));`
___
*[TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj, line 9 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZnjYu30-h2ynJdHhQW:-MZrou_wC20tsb_sOTrY:b-7j1bai) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj#L9)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

should other test apps be unsigned, too?
</blockquote></details>

No. This one has to be unsigned because it depends on SIL.Media which is unsiged itself because it depends on irrKlang.NET4.dll which is a mixed-mode assembly. In general it's better (i.e. more widely usable) to sign if possible.

**Review by papeh — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1074)* status: all files reviewed, 1 unresolved discussion (waiting on @jasonleenaylor)

___
*[TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj, line 9 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZnjYu30-h2ynJdHhQW:-MZxPE0e1dKVBFl7e3C4:bp7vbga) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/TestApps/SIL.Windows.Forms.TestApp/SIL.Windows.Forms.TestApp.csproj#L9)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

No. This one has to be unsigned because it depends on SIL.Media which is unsiged itself because it depends on irrKlang.NET4.dll which is a mixed-mode assembly. In general it's better (i.e. more widely usable) to sign if possible.
</blockquote></details>

sounds good.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 13 of 50 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1074)* status: 49 of 50 files reviewed, 1 unresolved discussion (waiting on @ermshiperete and @papeh)

___
*[SIL.WritingSystems.Tests/SldrTests.cs, line 271 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-MZniqno8RPgLy84-0TP:-MeQAL_BEU0TzXs6E5Mz:bl5r7kw) ([raw file](https://github.com/sillsdev/libpalaso/blob/88eb1bb12dfa715f56ac1081dcca3526ef0cc56d/SIL.WritingSystems.Tests/SldrTests.cs#L271)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

This comment got added in commit [64c68401cb5f6405f6e427792ec31228a1e6bc5f](https://github.com/sillsdev/libpalaso/commit/64c68401cb5f6405f6e427792ec31228a1e6bc5f) (February 2020), but I don't see the cache working that way. AFAICT the code intentionally returns `FromSldr`, so I'm not sure what to do about this comment and assert. Maybe @jasonleenaylor  could take a look if he remembers why he added `Assert.That(sldrStatus, Is.EqualTo(SldrStatus.FromCache));`
</blockquote></details>

So I just looked at it and it does look like this assertion is invalid. I suspect that I was trying to find a way to make the test more robust and because this test doesn't run on team city my half baked efforts made it through.

The test was fragile because the test data at the top would go stale every time the SLDR is updated. The goal is to verify that if you request a file and the data in the SLDR has not changes since you got the file that it would not download the file. I don't think that is easily tested with the current code.

**Review by papeh — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1074#-:-MeQwbGw0kv1akDAycKf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete)

**Pull request merged**
