### PR TITLE
Bugfix/missing norwegian

### PR DESCRIPTION
**Pull request by glasseyes**
These are fixes for WS-505. Norwegian wasn't appearing because it is a macrolanguage and neither of the Norwegian languages are in Ethnologue

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/605)

### CODE REVIEW

**Comment by papeh** [comment]
Why can't we include this languages in the resource file instead of hard-coding?

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/605#-:-L5Fd5eOEzrPd34RnNtf:b8rfuxr)*

**Comment by jasonleenaylor** [comment]
So on the ethnologue site there is a macrolanguage mapping page. I wonder if the best fix would be to pull that, add it to our data files, and use the mapping properly.

**Comment by glasseyes** [comment]
@hasso If you mean including the languages in LanguageIndex.txt then that is another thing that you have to remember about and keep changing when there is a new LanguageIndex.txt.

@Jason I can't find the ethnologue macrolanguage mapping page. This way of doing it was a hack for libpalaso-2.6. libpalaso-3.1 and master know what are macrolanguages from the ianaSubtagRegistry.txt though not the mapping

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/605#-:-L5H79olKlsok7jF3ilB:ba0idzv)*

**Comment by ermshiperete** [comment]
Maybe the commit message and/or the code should have a comment that this is a hack for libpalaso-2.6 that's not needed on newer versions because those support macro languages. Then nobody has to wonder if we have to re-do that change on the newer branches.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/605#-:-L5rGKJOyukVwRJ9SAqk:b-h0kzw4)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/605#-:-L6X3MZUPbCUO1RBrOiG:bnfp4nl)*

**Comment by glasseyes** [comment]
Good point. I'll mention that in the merge commit and hopefully that is enough for someone to find

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/605#-:-L6X4xl_WXVOeCT-KOO4:b-sbtuir)*

**Pull request merged**
