### PR TITLE
HT-407: Added a CheckedComboBox control and some code to test it in the TestApp

### PR DESCRIPTION
**Pull request by tombogle**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1167)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Wants a +semver:minor and an addition in the changelog

Note: I didn't bother carefully reviewing the new files because a) they are just a new component and therefore low/no risk and b) you grabbed the code from elsewhere.

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-:-N2SjsSN6FZBOfQj366z:bdzksk1)* status: all files reviewed, 3 unresolved discussions (waiting on @ermshiperete and @tombogle)

___
*[`SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-N2ShnQH2jJhjz7uZobe:-N2ShnQI-r7mjPqL4Bzx:bwxpb9f) ([raw file](https://github.com/sillsdev/libpalaso/blob/b6c45b2c97074238807a5ac9753c3b36aff334f2/SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs#L12)):*
> ```Smalltalk
> using static System.String;
> 
> namespace SIL.Windows.Forms.CheckedComboBox
> ```

Maybe not worth a change, but there are a mix of indentation styles in the two new files. (Reviewable highlights that pretty well...)
___
*[`SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs` line 88 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-N2SintHA62AiD3rsgyx:-N2SintHA62AiD3rsgyy:b65394s) ([raw file](https://github.com/sillsdev/libpalaso/blob/b6c45b2c97074238807a5ac9753c3b36aff334f2/SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs#L88)):*
> ```Smalltalk
> 	                }
> 
> 	                // If no Enter or Esc keys presses, let the base class handle it.
> ```

technically, enter, esc, or delete

Could probably just remove the comment



_Code quote:_
```Smalltalk
If no Enter or Esc keys presses
```
___
*[`TestApps/SIL.Windows.Forms.TestApp/ModalChildForm.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-N2SjnGR3kmrjEkIJYRa:-N2SjnGR3kmrjEkIJYRb:b-kznm32) ([raw file](https://github.com/sillsdev/libpalaso/blob/b6c45b2c97074238807a5ac9753c3b36aff334f2/TestApps/SIL.Windows.Forms.TestApp/ModalChildForm.cs#L34)):*
> ```Smalltalk
> 
> 			// Set a separator for how the checked items will appear in the Text portion.
> 			cboWhiteSpaceCharacters.ValueSeparator = ", ";
> ```

worth adding to the comment that this is unnecessary because it is the default?

**Comment by tombogle** [comment]
Done. In fairness, I did do a bit of tweaking to the downloaded code to get it to work as desired and to make the formatting more compatible with our usual style.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1167)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @ermshiperete)

___
*[`SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-N2ShnQH2jJhjz7uZobe:-N2TO3cr923oeCkKXUXd:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/b6c45b2c97074238807a5ac9753c3b36aff334f2/SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe not worth a change, but there are a mix of indentation styles in the two new files. (Reviewable highlights that pretty well...)
</blockquote></details>

Done.
___
*[`SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs` line 88 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-N2SintHA62AiD3rsgyx:-N2TO36zCD2Ux9tpb1-Z:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/b6c45b2c97074238807a5ac9753c3b36aff334f2/SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

technically, enter, esc, or delete

Could probably just remove the comment
</blockquote></details>

Done.
___
*[`TestApps/SIL.Windows.Forms.TestApp/ModalChildForm.cs` line 34 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-N2SjnGR3kmrjEkIJYRa:-N2TO1qMAmL8Z744ViJ0:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/b6c45b2c97074238807a5ac9753c3b36aff334f2/TestApps/SIL.Windows.Forms.TestApp/ModalChildForm.cs#L34)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

worth adding to the comment that this is unnecessary because it is the default?
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ermshiperete)

___
*[`SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs` line 12 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1167#-N2ShnQH2jJhjz7uZobe:-N2XPGZx924TG5gc5Icj:b-wagv2v) ([raw file](https://github.com/sillsdev/libpalaso/blob/b6c45b2c97074238807a5ac9753c3b36aff334f2/SIL.Windows.Forms/CheckedComboBox/CheckedComboBox.cs#L12)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Also the other new file (`CheckedComboBoxItem`)
Otherwise, LGTM

**Pull request merged**
