### PR TITLE
Fixes needed for flatpak packages such as org.sil.Bloom (20220811)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1209)

### CODE REVIEW

**Review by jasonleenaylor — COMMENTED** [review]
It looks good to the eyes of a windows developer.

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-:-N9CzhXLCvQp-bVmhpiw:bkv0yc8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1209)* status: all files reviewed, 3 unresolved discussions (waiting on @StephenMcConnel)

___
*[`CHANGELOG.md` line 22 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-N9D6t_rEz32RI-vSmS8:-N9D6t_sBi-TE_g9ABGx:b9vms37) ([raw file](https://github.com/sillsdev/libpalaso/blob/a6b3ef187d6b6a46932b16c4511e961ece079b5b/CHANGELOG.md#L22)):*
> ```Markdown
> 
> ### Added
> - [SIL.Core] Added SIL.PlatformUtilities.Platform.IsFlatpak property.
> ```

I believe this means the commit comment should include `semver:minor`
___
*[`SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.cs` line 64 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-N9D5hAQ4eHYWtnQDse3:-N9D5hAQ4eHYWtnQDse4:b-hgh2sv) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b5f5ef49648e712ec7be151b3072eaad00f2385/SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.cs#L64)):*
> ```Smalltalk
> 		{
> 			DialogResult = DialogResult.Cancel;
> 			_imageToolboxControl.Closing();
> ```

Could you give a brief explanation of why these calls are not needed/helpful?
___
*[`SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-N9D650DCIEj3VzWybXL:-N9D650DCIEj3VzWybXM:b5cf3sn) ([raw file](https://github.com/sillsdev/libpalaso/blob/a6b3ef187d6b6a46932b16c4511e961ece079b5b/SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs#L62)):*
> ```Smalltalk
> 					.CombineForPath("SIL", "ImageCollections");
> 			if (!Directory.Exists(ImageCollectionsFolder) && SIL.PlatformUtilities.Platform.IsFlatpak)
> 				ImageCollectionsFolder = "/app/share/SIL/ImageCollections";
> ```

If you do the Flatpak check first, we don't need to check for the existence of the directory for most cases.

**Comment by marksvc** [comment]
Okay. I'm sorry that I didn't first get libpalaso-6.0 merged in, tho it looks like there was only a minor overlap, with Platform.IsFlatpak.
I see that in one place, you want ~/.local/share instead of the XDG_DATA_HOME. Note that I handled this by distinguishing between an XDG_DATA_HOME and a new environment variable of USER_DATA_HOME. Tho I don't think you need to change what you have.

**Comment by marksvc** [comment]
Oh, you might want to check if /app/foo exists _before_ checking if /usr/foo exists, so that flatpak-packaged resources are used before checking/using resources outside of the flatpak.

**Review by StephenMcConnel — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1209)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @jasonleenaylor)

___
*[`CHANGELOG.md` line 22 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-N9D6t_rEz32RI-vSmS8:-N9E8-9o4L3HFU_X3DsS:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/a6b3ef187d6b6a46932b16c4511e961ece079b5b/CHANGELOG.md#L22)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I believe this means the commit comment should include `semver:minor`
</blockquote></details>

Done.
___
*[`SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.cs` line 64 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-N9D5hAQ4eHYWtnQDse3:-N9E6Ty23V0TrjYGgCF4:b3zr36v) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b5f5ef49648e712ec7be151b3072eaad00f2385/SIL.Windows.Forms/ImageToolbox/ImageToolboxDialog.cs#L64)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Could you give a brief explanation of why these calls are not needed/helpful?
</blockquote></details>

I'm still not sure they're needed, but a (not so) quick test shows that this change isn't needed for the flatpak work, so I'm removing this change.
___
*[`SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs` line 62 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-N9D650DCIEj3VzWybXL:-N9E6hZF0ZXI4t8gGlOK:b4q1f4) ([raw file](https://github.com/sillsdev/libpalaso/blob/a6b3ef187d6b6a46932b16c4511e961ece079b5b/SIL.Windows.Forms/ImageToolbox/ImageGallery/ImageCollectionManager.cs#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If you do the Flatpak check first, we don't need to check for the existence of the directory for most cases.
</blockquote></details>

I've been thinking of changing how Art of Reading is handled in flatpak, to make it a separate add-on package which may end up in the sandboxed /usr.  (I'm not sure whether that would work, and whether the effort is worthwhile if it does.)  But I'd like to leave the possibility open for flatpak finding art of reading in /usr.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1209)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Review by marksvc — COMMENTED** [review]
I'm good with the changes from r1 to r2.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1209#-:-N9J6-0u9thQ_ps1Z29u:b-ezciab)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @StephenMcConnel)

**Pull request merged**
