### PR TITLE
get packages from nuget instead of checked in (libpalaso-3.1)

### PR DESCRIPTION
**Pull request by glasseyes**
get NAudio, Commons.Xml.RelaxNG, Moq, Rhino.Mocks from nuget
all closest versions to what is currently in the repo

upgrade Commons.Xml.RelaxNG to 3.2.3 from 2.0.0
upgrade Rhino.Mocks to 3.6.1 from 3.5
upgrade Moq from 4.0.812 to 4.0.10827
use consistent version of icu.net and upgrade to 2.2.0
upgrade to NDesk.DBus 1.5.0
don't include dbus or ibus project targets in windows builds nor icu dlls in linux builds

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/583)

### CODE REVIEW

**Comment by glasseyes** [comment]
libpalaso-3.1 windows builds on teamcity are currently failing because it can't clean the build checkout directory - investigating

**Comment by ermshiperete** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[SIL.Lift.Tests/SIL.Lift.Tests.csproj, line 172 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi468P_Tmpv0ALEm2F:-Kwi468P_Tmpv0ALEm2G:b5anrit) ([raw file](https://github.com/sillsdev/libpalaso/blob/cbb785bf0280f3b898b0a8dd232eff8090087da9/SIL.Lift.Tests/SIL.Lift.Tests.csproj#L172)):*
> ```XML
>   </PropertyGroup>
>   <ItemGroup>
>     <Reference Include="Moq, Version=4.0.812.4, Culture=neutral, PublicKeyToken=69f491c39445e920, processorArchitecture=MSIL">
> ```

Something doesn't look right here: We add the Moq nuget package, yet the reference to Moq got deleted

---

*[SIL.Media.Tests/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi6au56UJsrBiIZb6o:-Kwi6au56UJsrBiIZb6p:bjb4fpp) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Media.Tests/packages.config#L4)):*
> ```XML
> <packages>
>   <package id="NUnit" version="2.6.4" targetFramework="net40" />
>   <package id="NAudio" version="1.8.3" />
> ```

Don't we have to change the .csproj file as well?

---

*[SIL.Windows.Forms/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi6k0_ZkhNhpitCqbP:-Kwi6k0_ZkhNhpitCqbQ:b7c8gk3) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms/packages.config#L4)):*
> ```XML
> <packages>
>   <package id="MarkdownDeep.NET" version="1.5" targetFramework="net40-Client" />
>   <package id="Icu4c.Win.Min" version="54.1.31" targetFramework="net40" />
> ```

I wonder that we need Icu4c.Win.Min but don't need icu.net.

---

*[SIL.Windows.Forms/packages.config, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi5-e3EBR0J-hVRWSp:-Kwi5-e3EBR0J-hVRWSq:b-cmq48j) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms/packages.config#L7)):*
> ```XML
>   <package id="NAudio" version="1.8.3" />
>   <package id="NDesk.DBus" version="0.15.0" targetFramework="net40-client" />
> </packages>
> ```

I'd expect some changes in the corresponding .csproj file - or did I miss that?

---

*[SIL.Windows.Forms.Keyboarding.Tests/packages.config, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi5Q47uKd-VxbY2HkF:-Kwi5Q47uKd-VxbY2HkG:b-e0u4xt) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms.Keyboarding.Tests/packages.config#L6)):*
> ```XML
>   <package id="NDesk.DBus" version="0.15.0" targetFramework="net40" />
>   <package id="NUnit" version="2.6.4" targetFramework="net40" />
> </packages>
> ```

Should add Moq here since it's referenced in the .csproj file.

---

*[SIL.Windows.Forms.WritingSystems.Tests/packages.config, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi5wC-psujP8ZYh2T6:-Kwi5wC-psujP8ZYh2T7:b-31xnh4) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms.WritingSystems.Tests/packages.config#L6)):*
> ```XML
>   <package id="NDesk.DBus" version="0.15.0" targetFramework="net40" />
>   <package id="NUnit" version="2.6.4" targetFramework="net40" />
> </packages>
> ```

Should add Moq

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/583)*

**Comment by glasseyes** [comment]
Review status: 28 of 43 files reviewed at latest revision, 6 unresolved discussions.

---

*[SIL.Lift.Tests/SIL.Lift.Tests.csproj, line 172 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi468P_Tmpv0ALEm2F:-Kwiekr3uK97qsj-crf8:b5l17hc) ([raw file](https://github.com/sillsdev/libpalaso/blob/cbb785bf0280f3b898b0a8dd232eff8090087da9/SIL.Lift.Tests/SIL.Lift.Tests.csproj#L172)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Something doesn't look right here: We add the Moq nuget package, yet the reference to Moq got deleted
</blockquote></details>

Done. Added reference back since it is used in SIL.Lift.Tests

---

*[SIL.Media.Tests/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi6au56UJsrBiIZb6o:-Kwih6jFvA8iaiU8-M3h:b-w2t0nj) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Media.Tests/packages.config#L4)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Don't we have to change the .csproj file as well?
</blockquote></details>

Done. Thanks, I did miss that.

---

*[SIL.Windows.Forms/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi6k0_ZkhNhpitCqbP:-KwitQu0TpMwrcc0ov2m:bmw03vh) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms/packages.config#L4)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I wonder that we need Icu4c.Win.Min but don't need icu.net.
</blockquote></details>

Done. Removed, not needed

---

*[SIL.Windows.Forms.Keyboarding.Tests/packages.config, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi5Q47uKd-VxbY2HkF:-KwitW9mFwELaZfBGTTs:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms.Keyboarding.Tests/packages.config#L6)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Should add Moq here since it's referenced in the .csproj file.
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.WritingSystems.Tests/packages.config, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi5wC-psujP8ZYh2T6:-KwitXHuuOaOxn3dIzA5:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms.WritingSystems.Tests/packages.config#L6)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Should add Moq
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/583)*

**Comment by ermshiperete** [comment]
Reviewed 1 of 38 files at r1, 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Windows.Forms/packages.config, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi5-e3EBR0J-hVRWSp:-Kwj1qJnVp7X_zs7mOby:b-wimr2g) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms/packages.config#L7)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I'd expect some changes in the corresponding .csproj file - or did I miss that?
</blockquote></details>

Do we need these packages? Looks they are not referenced in the .csproj file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/583)*

**Comment by glasseyes** [comment]
Review status: 39 of 43 files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Windows.Forms/packages.config, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-Kwi5-e3EBR0J-hVRWSp:-KwmbltF8gH_JWr_kbNn:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/4bc381f6933b33c0c286ba6066de9401822f59e3/SIL.Windows.Forms/packages.config#L7)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Do we need these packages? Looks they are not referenced in the .csproj file.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/583)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/583#-:-KwnZdPe4P_FVpK-RoST:bnfp4nl)*

**Pull request merged**
