### PR TITLE
+semver:major Added LocalizationIncompleteDlg and its view model

### PR DESCRIPTION
**Pull request by tombogle**
Added additional optional parameters and logic to ToolStripExtensions.InitializeWithAvailableUILocales to support automatic display of the new dialog box.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1180)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
I'm not seeing what is making this a major (breaking) change.

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-:-N4EtGt53YSW-65Qf6do:b-xpyx6x)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton, @JohnThomson, and @tombogle)

___
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.cs` line 19 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4EtiyU8pHQ3f8y3c34:-N4EtiyU8pHQ3f8y3c35:bgdd7o5) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.cs#L19)):*
> ```Smalltalk
> 		public LocalizationIncompleteDlg(LocalizationIncompleteViewModel localizationViewModel)
> 		{
> 			_localizationViewModel = localizationViewModel;
> ```

doesn't matter, but I think I would call both of these variables simply "model"



_Code quote:_
```Smalltalk
_localizationViewModel = localizationViewModel
```
___
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 121 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4ErNA20gNAK7noYoo3:-N4ErNA20gNAK7noYoo4:b42x1ak) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L121)):*
> ```Smalltalk
> 			this.l10NSharpExtender1.SetLocalizationComment(this._lblLocalizationIncomplete, "Param 0: Localization Manager name (usually the same as the application name); Pa" +
>         "ram 1: Name of the selected user interface language.");
> 			this.l10NSharpExtender1.SetLocalizingId(this._lblLocalizationIncomplete, "DialogBoxes.LocalizationIncompleteDlg.LocalizationIncompleteDlg._lblLocalizationI" +
> ```

repeated `LocalizationIncompleteDlg`.

Here and elsewhere



_Code quote:_
```Smalltalk
LocalizationIncompleteDlg.LocalizationIncompleteDlg
```
___
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 128 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4EpqwY81FVOKS2JBQP:-N4EpqwY81FVOKS2JBQQ:b9myjz7) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L128)):*
> ```Smalltalk
> 			this._lblLocalizationIncomplete.Size = new System.Drawing.Size(562, 51);
> 			this._lblLocalizationIncomplete.TabIndex = 2;
> 			this._lblLocalizationIncomplete.Text = resources.GetString("_lblLocalizationIncomplete.Text");
> ```

Maybe this works just fine, but I don't remember seeing a string localized by the l10nsharptExtender in the resources file before.

There are 2 typos there. "enail" and "{0} int {1} "
___
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 170 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4EqzoY0KkvmuUgnUXX:-N4EqzoY0KkvmuUgnUXY:bx4ud7n) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L170)):*
> ```Smalltalk
> 			this._lblUsers.Size = new System.Drawing.Size(566, 33);
> 			this._lblUsers.TabIndex = 5;
> 			this._lblUsers.Text = "Approximately how many users or teams do you know of who would benefit from havin" +
> ```

That answer could be pretty different depending on if you're answering users or teams.
I would be frustrated by this question if I knew of 3 team, each with 10 people, for example.



_Code quote:_
```Smalltalk
Approximately how many users or teams
```
___
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 238 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4Ers4e0hVs6eEijXLM:-N4Ers4e0hVs6eEijXLN:b-7ilvgp) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L238)):*
> ```Smalltalk
> 			// _lblMoreInromationEmail
> 			// 
> 			this._lblMoreInromationEmail.Anchor = System.Windows.Forms.AnchorStyles.Left;
> ```

typo 



_Code quote:_
```Smalltalk
_lblMoreInromationEmail
```
___
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 261 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4Es-HR5cqRJNcyASbF:-N4Es-HR5cqRJNcyASbG:b-d0hgae) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L261)):*
> ```Smalltalk
> 			this.l10NSharpExtender1.SetLocalizableToolTip(this._btnCopy, "Copy email address to clipboard");
> 			this.l10NSharpExtender1.SetLocalizationComment(this._btnCopy, null);
> 			this.l10NSharpExtender1.SetLocalizingId(this._btnCopy, "DialogBoxes.LocalizationIncompleteDlg.button1");
> ```

I would suggest a better l10n ID



_Code quote:_
```Smalltalk
button1
```

**Comment by tombogle** [comment]
The change to the signature of the method to add the menu items. If the optional parameters were all passed in order (not named), it would no longer compile.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 121 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4ErNA20gNAK7noYoo3:-N4FLotB1Oyd7Sic46Qz:b-bh5gyj) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L121)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

repeated `LocalizationIncompleteDlg`.

Here and elsewhere
</blockquote></details>

Yeah, I don't especially like that either, but it does follow an established pattern (e.g., FolderBrowserControl). Because the namespace corresponds to the subfolder and the subfolder is named the same thing as the class, this is needed to disambiguate. I could change the folder to just be LocalizationIncomplete, but I'm not sure that is as meaningful.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 128 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4EpqwY81FVOKS2JBQP:-N4FMWKoEctRRbVEew6L:bj4783k) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L128)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Maybe this works just fine, but I don't remember seeing a string localized by the l10nsharptExtender in the resources file before.

There are 2 typos there. "enail" and "{0} int {1} "
</blockquote></details>

Fixed the typos. VS automatically puts longer strings into the .resx file instead of having them hardcoded in the .cs file. No idea what the actual rationale is for that, but L10nSharp is okay with it.

**Comment by tombogle** [comment]
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 170 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4EqzoY0KkvmuUgnUXX:-N4FMsOS37QW06SIQdgw:b-rmajjx) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L170)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

That answer could be pretty different depending on if you're answering users or teams.
I would be frustrated by this question if I knew of 3 team, each with 10 people, for example.
</blockquote></details>

Yeah, I'm kind of iffy on the overall UX with this, but Bryan thought we should ask. I considered a couple radio buttons so they could choose "users" or "teams" but the question (and the information we're trying to gather) is already kind of vague and mushy. Another alternative would be to make it a text box and then they could type "10 users", "two teams", "everybody in PNG", etc.

**Review by tombogle — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1180)* status: 9 of 12 files reviewed, 4 unresolved discussions (waiting on @andrew-polk, @hatton, and @JohnThomson)

___
*[`SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs` line 261 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1180#-N4Es-HR5cqRJNcyASbF:-N4FOcEPBBrqmHJI2xRd:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/7317dfa89408f9f0189181e1fae54169ce43eb6d/SIL.Windows.Forms/LocalizationIncompleteDlg/LocalizationIncompleteDlg.Designer.cs#L261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would suggest a better l10n ID
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1180)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton and @JohnThomson)

**Pull request merged**
