### PR TITLE
Replace MarkdownDeep with Markdig

### PR DESCRIPTION
**Pull request by ArmorBearer**
In order to replace MarkdownDeep, which doesn't seem to be maintained and hasn't had an update in a very long time, Todd Hoatson has revised the ShowReleaseNotesDialog form by using the signed version of Markdig.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/990)

### CODE REVIEW

**Review by ermshiperete — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/990)* status: all files reviewed, 2 unresolved discussions (waiting on @ArmorBearer)

___
*[SIL.Windows.Forms/packages.config, line 10 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/990#-MLOQMd630Hv7HKYccrU:-MLOQMd630Hv7HKYccrV:b-pxt68n) ([raw file](https://github.com/sillsdev/libpalaso/blob/516f664637ca463a2c34008c98893ead19ce3455/SIL.Windows.Forms/packages.config#L10)):*
> ```XML
>   <package id="GtkSharp-signed" version="3.22.24.37" requireReinstallation="true" />
>   <package id="L10NSharp" version="4.1.0-beta0036" targetFramework="net461" />
>   <package id="MarkdownDeep.NET.Patched" version="1.5.0.2" targetFramework="net461" />
> ```

We probably should add `Markdig.Signed` here as well.
___
*[SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj, line 126 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/990#-MLOQS-B30v_YTAJuA8p:-MLOQS-B30v_YTAJuA8q:b-yobptt) ([raw file](https://github.com/sillsdev/libpalaso/blob/516f664637ca463a2c34008c98893ead19ce3455/SIL.Windows.Forms/SIL.Windows.Forms-Designer.csproj#L126)):*
> ```XML
>       <HintPath>..\packages\MarkdownDeep.NET.Patched.1.5.0.2\lib\net35\MarkdownDeep.dll</HintPath>
>       <Private>True</Private>
>     </Reference>
> ```

We probably should reference `Markdig.Signed` here as well.

**Comment by ArmorBearer** [comment]
@ermshiperete, the 2 files you mentioned:

packages.config
SIL.Windows.Forms-Designer.csproj

are typically maintained by Visual Studio and not manually changed.  I noticed that Visual Studio had removed the MarkdownDeep package references from these files and had not replaced them with Markdig.  But the library built successfully, and I was able to run TestApp successfully (as well as the unit tests), so I assumed that Visual Studio must have known what it is doing.

Would you like me to manually edit these files?

**Review by ermshiperete — COMMENTED** [review]
Yes, please. Either edit the files manually, or open the SIL.Windows.Forms-Designer project in VS (under DesignerProjects in the Palaso.sln) and add the nuget package there.

The designer projects will hopefully be obsolete soon, but in the past it wasn't possible to open winforms files in the designer if the csproj file was using the new sdk-style format. As a workaround we added the designer project (which still use the old csproj format).

With .NET 5 it will be possible to use the designer with sdk-style projects - I have a PR open for that, but last time I tried there were still some problems so that it didn't work for all files. Until then we should keep the designer projects up-to-date.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/990#-:-MLRknXbEfYqb-8gQJjj:bzb65cq)* status: all files reviewed, 2 unresolved discussions (waiting on @ArmorBearer)

**Comment by ArmorBearer** [comment]
@ermshiperete, I have changed the 2 files using the Nuget Package Manager in Visual Studio.  It has also added some other prerequisite packages, as well.  Hope this is now correct.

**Review by ermshiperete — APPROVED** [review]
:lgtm: - once it build successfully on TC

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/990#-:-MLlgfY408oD3yv4ykHw:ba6a8sh)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ermshiperete** [comment]
Superseded by #994

**Pull request closed without merging**
