### PR TITLE
flatpak: keyboarding: query preload-engines via spawn

### PR DESCRIPTION
**Pull request by marksvc**
commit-id:5d6599a0

---

**Stack**:
- #1150
- #1149 ⬅

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, line 97 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1149#-MzRnNdD9G-tFpy7XSgd:-MzRnNdD9G-tFpy7XSge:bwx9fke) ([raw file](https://github.com/sillsdev/libpalaso/blob/256e037181e33304111e7ac9f409f2d386cd9249/SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs#L97)):*
> ```Smalltalk
> 		/// </summary>
> 		internal static List<string> ParseIbusEnginesList(string keyboardList)
> 		{
> ```

I don't know if this works, but if it does it's cleaner. :smile: 
`return JArray.Parse(keyboardList).ToObject<List<string>>()?`



_Code quote:_
```Smalltalk
			return keyboardList
				.Split(new string[] {", "}, StringSplitOptions.RemoveEmptyEntries)
				.Select((string item) => item.Trim("[]', \n".ToCharArray()))
				.Where((string item) => !string.IsNullOrWhiteSpace(item))
				.ToList<string>();
```

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1149)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs, line 97 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1149#-MzRnNdD9G-tFpy7XSgd:-MzVm3Qo95wdQUuc6jeo:biogv5t) ([raw file](https://github.com/sillsdev/libpalaso/blob/b387efa08b221774fe6ecf11f8a9048a3b83851f/SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardRetrievingAdaptor.cs#L97)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I don't know if this works, but if it does it's cleaner. :smile: 
`return JArray.Parse(keyboardList).ToObject<List<string>>()?`
</blockquote></details>

Much better. Thank you. Done.

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding.Tests/CombinedIbusKeyboardRetrievingAdaptorTests.cs, line 5 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1149#-MzX0qyW4y5E-wQJOlXl:-MzX0qyW4y5E-wQJOlXm:b-atus0e) ([raw file](https://github.com/sillsdev/libpalaso/blob/cceda4bbf4f9f2eb96b45a8829092fa65939aa6c/SIL.Windows.Forms.Keyboarding.Tests/CombinedIbusKeyboardRetrievingAdaptorTests.cs#L5)):*
> ```Smalltalk
> 
> using System;
> using System.Collections.Generic;
> ```

Probably unneeded now.



_Code quote:_
```Smalltalk
using System.Collections.Generic;
```

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1149)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[SIL.Windows.Forms.Keyboarding.Tests/CombinedIbusKeyboardRetrievingAdaptorTests.cs, line 5 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1149#-MzX0qyW4y5E-wQJOlXl:-Mz_f3rR6TcH-L9WROFg:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/903657d46dfeebea72b9504127aa65fdde5080ff/SIL.Windows.Forms.Keyboarding.Tests/CombinedIbusKeyboardRetrievingAdaptorTests.cs#L5)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Probably unneeded now.
</blockquote></details>

Done.

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1149)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @marksvc)

**Pull request merged**
