### PR TITLE
+semver:minor Added constructor to make a DblMetadataCopyright object…

### PR DESCRIPTION
**Pull request by tombogle**
…from a string and implementations of ToString. This is to support PG-771.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1022)

### CODE REVIEW

**Review by ermshiperete — APPROVED** [review]
:lgtm:

**Review by ermshiperete — CHANGES_REQUESTED** [review]
This :lgtm:, but CI builds failing...

**Comment by tombogle** [comment]
I didn't see any connection to the build failure and my code change, so I kicked it off again...

**Review by andrew-polk — APPROVED** [review]

**Review by ermshiperete — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1022)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tombogle)

**Pull request merged**
