### PR TITLE
BL-12665 Detect Win11 in error reports

### PR DESCRIPTION
**Pull request by gmartin7**
* include entire VersionString

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
Please add a line to Changelog.md

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292#-:-NgVNLzi-ATvs3z5HDSP:b-qz8qp3)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`SIL.Core/Reporting/ErrorReport.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1292#-NgVNgk53Cm-vmIPaUJL:-NgVNgk53Cm-vmIPaUJM:b52pdbw) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b2daae21ea0d0c0761c444e9488d6e82ee10363/SIL.Core/Reporting/ErrorReport.cs#L470)):*
> ```Smalltalk
> 						}
> 						return version.Label + " (" + Environment.OSVersion.VersionString + ")";
> 					}
> ```

I would be hesitant about changing the existing strings, particularly removing the ServicePack info.

So I would either report the VersionString as a separate prop altogether
or do something like

```
                    if (version.Match(Environment.OSVersion))
                    {
                        if (version.Label \== "Windows 10")
                        {
                            // From: https://stackoverflow.com/questions/69038560/detect\-windows\-11\-with\-net\-framework\-or\-windows\-api
                            if (Environment.OSVersion.Version.Build \>= 22000)
                            {
                                return "Windows 11+" + " (" + Environment.OSVersion.VersionString + ")";
                            }
                            return version.Label + " (" + Environment.OSVersion.VersionString + ")";
                        }
                        return version.Label + " " + Environment.OSVersion.ServicePack + " (" + Environment.OSVersion.VersionString + ");
                    }
```
(ServicePack probably only applies to <10? Otherwise, we can just always include it.)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`SIL.Core/Reporting/ErrorReport.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1292#-NgVNgk53Cm-vmIPaUJL:-NgVSFAV0wHGtUIa3pt2:b-tvg679) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b2daae21ea0d0c0761c444e9488d6e82ee10363/SIL.Core/Reporting/ErrorReport.cs#L470)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I would be hesitant about changing the existing strings, particularly removing the ServicePack info.

So I would either report the VersionString as a separate prop altogether
or do something like

```
                    if (version.Match(Environment.OSVersion))
                    {
                        if (version.Label \== "Windows 10")
                        {
                            // From: https://stackoverflow.com/questions/69038560/detect\-windows\-11\-with\-net\-framework\-or\-windows\-api
                            if (Environment.OSVersion.Version.Build \>= 22000)
                            {
                                return "Windows 11+" + " (" + Environment.OSVersion.VersionString + ")";
                            }
                            return version.Label + " (" + Environment.OSVersion.VersionString + ")";
                        }
                        return version.Label + " " + Environment.OSVersion.ServicePack + " (" + Environment.OSVersion.VersionString + ");
                    }
```
(ServicePack probably only applies to <10? Otherwise, we can just always include it.)
</blockquote></details>

Service Pack is included in VersionString.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)* status: all files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`SIL.Core/Reporting/ErrorReport.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1292#-NgVNgk53Cm-vmIPaUJL:-NgVUkeOA9LAOpgEq56i:b-tzlyr6) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b2daae21ea0d0c0761c444e9488d6e82ee10363/SIL.Core/Reporting/ErrorReport.cs#L470)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Service Pack is included in VersionString.
</blockquote></details>

Ah.
Then all we need is the Changelog entry. 
Thanks

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`SIL.Core/Reporting/ErrorReport.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1292#-NgVNgk53Cm-vmIPaUJL:-NgVZ6qBBx-b1NGgYVxq:b-8fx2u7) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b2daae21ea0d0c0761c444e9488d6e82ee10363/SIL.Core/Reporting/ErrorReport.cs#L470)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Ah.
Then all we need is the Changelog entry. 
Thanks
</blockquote></details>

:+1:

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @gmartin7)

___
*[`SIL.Core/Reporting/ErrorReport.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1292#-NgVNgk53Cm-vmIPaUJL:-NgVhiNYCIQ17FlkkyYg:b-w2z0qy) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b2daae21ea0d0c0761c444e9488d6e82ee10363/SIL.Core/Reporting/ErrorReport.cs#L470)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

As discussed, let's use Version rather than VersionString

**Review by gmartin7 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`SIL.Core/Reporting/ErrorReport.cs` line 470 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1292#-NgVNgk53Cm-vmIPaUJL:-NgVj0-7B2LFflx4_-J-:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/2b2daae21ea0d0c0761c444e9488d6e82ee10363/SIL.Core/Reporting/ErrorReport.cs#L470)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

As discussed, let's use Version rather than VersionString
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gmartin7)

**Pull request merged**
