### PR TITLE
Removed some compiler warnings caused by code not being CLS compliant.

### PR DESCRIPTION
**Pull request by mikelothers**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/516)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Core/Annotations/Annotation.cs, line 41 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/516#-Kjy9NLOOZr8yrHA4qfL:-Kjy9NLOOZr8yrHA4qfM:bfhvawy) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbcee7133e7a801e1c1fa80fd2ce2609a88f02de/SIL.Core/Annotations/Annotation.cs#L41)):*
> ```Smalltalk
> 			set { _annotation = value; }
> 		}
> ```

I think simply

    protected Annotation Annotation;

would be simpler and thus preferred in all of these situations, rather than using a backing field or even ````{get; set;}````

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/516)*

**Comment by andrew-polk** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Core/Annotations/Annotation.cs, line 41 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/516#-Kjy9NLOOZr8yrHA4qfL:-KjyD70eosGsOURHj_NS:b-nzec79) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbcee7133e7a801e1c1fa80fd2ce2609a88f02de/SIL.Core/Annotations/Annotation.cs#L41)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think simply

    protected Annotation Annotation;

would be simpler and thus preferred in all of these situations, rather than using a backing field or even ````{get; set;}````
</blockquote></details>

I can't remember the arguments now, but in the past Tom has convinced me 
```
protected Annotation Annotation {get; set;}
```
is preferred to
```
protected Annotation Annotation;
```
But I agree it would be better to get rid of the backing fields.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/516)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Core/Annotations/Annotation.cs, line 41 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/516#-Kjy9NLOOZr8yrHA4qfL:-KjyE5LXY9BL3ixdYKS7:b-jgf3dv) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbcee7133e7a801e1c1fa80fd2ce2609a88f02de/SIL.Core/Annotations/Annotation.cs#L41)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I can't remember the arguments now, but in the past Tom has convinced me 
```
protected Annotation Annotation {get; set;}
```
is preferred to
```
protected Annotation Annotation;
```
But I agree it would be better to get rid of the backing fields.
</blockquote></details>

The arguments that I know of are not compelling; they fall into the category of the way we programmers start to think in what-if's that get us divorced from reality. In short, that API's in libpalaso can't change. 
 Spelled out: 

1) someone subclasses the class, in an external project
2) someone modified the original class to add code to the get or set
3) the subclassing project gets the latest palaso, build fails, and...
4) the world falls apart.

or 

1) someone subclasses the class, in an external project, and needs a way to change the behavior of get/set.
2) they find that they would have to go back into libpalaso to make this possible
3) the world falls apart.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/516)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/516#-:-KkBQxozNoOYB6riuuEf:bnfp4nl)*

**Pull request merged**
