### PR TITLE
Add Palaso.BuildTasks.AWS

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/529)

### CODE REVIEW

**Comment by gmartin7** [comment]
Reviewed 1 of 7 files at r1.
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Palaso.MSBuildTasks.AWS/S3BuildPublisher.cs, line 42 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0GEjDpHFqEJLFcvVE:-Kl0GEjEnsuDPhb2ZPNH:bmgtnd) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/S3BuildPublisher.cs#L42)):*
> ```Smalltalk
> 		/// Gets or sets if the files should be publically readable
> 		/// </summary>
> 		public bool PublicRead { get; set; }
> ```

PublicRead doesn't sound like a boolean to me. How about CanPublicRead, or even CanRead? On the other hand, it looks like you're just moving John's code?

---

*[Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0GpHDTd3imIRZY4Re:-Kl0GpHDTd3imIRZY4Rf:b-xftcl6) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs#L7)):*
> ```Smalltalk
> // set of attributes. Change these attribute values to modify the information
> // associated with an assembly.
> [assembly: AssemblyTitle("Palaso.BuildTasks.AWS")]
> ```

You would know better than I whether we want Palaso or SIL here, I suppose.

---

*[Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs, line 10 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0HLgn82XArHN3uOux:-Kl0HLgo6HKk-IVaCGp9:bfonawy) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs#L10)):*
> ```Smalltalk
> [assembly: AssemblyDescription("")]
> [assembly: AssemblyConfiguration("")]
> [assembly: ComVisible(false)]
> ```

Need any Acknowledgements? :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by andrew-polk** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[Palaso.MSBuildTasks.AWS/S3BuildPublisher.cs, line 42 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0GEjDpHFqEJLFcvVE:-Kl0IhYwUbKGqVMUgrSc:b-ut5r5c) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/S3BuildPublisher.cs#L42)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

PublicRead doesn't sound like a boolean to me. How about CanPublicRead, or even CanRead? On the other hand, it looks like you're just moving John's code?
</blockquote></details>

Yes, mostly moving code (which was John's but previously someone else's. But I'm all for improving it. I'll take a look at how to make it more readable. Perhaps IsPublicReadable?

---

*[Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs, line 7 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0GpHDTd3imIRZY4Re:-Kl0Ir_wko94pK35bhJi:b-6ati8f) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs#L7)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

You would know better than I whether we want Palaso or SIL here, I suppose.
</blockquote></details>

I wasn't sure. The existing one is Palaso.BuildTasks, so I wanted to make it consistent, but I really wanted SIL.

I'll put something on FlowDock. Maybe since v4.0 is still fresh we can move both of them.

---

*[Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs, line 10 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0HLgn82XArHN3uOux:-Kl0J3Wx5ODUfxNzBIG-:bbso3de) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs#L10)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Need any Acknowledgements? :)
</blockquote></details>

Hm. Yep. For some reason, I was thinking I didn't, but I forgot about the AWS dependency. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by andrew-polk** [comment]
Review status: 1 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs, line 10 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0HLgn82XArHN3uOux:-Kl0LclaV_LiyjWLIL7Q:bxp8jcv) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Hm. Yep. For some reason, I was thinking I didn't, but I forgot about the AWS dependency. Thanks.
</blockquote></details>

Actually, I'm reconsidering this. I went to add it and realized it was going to add a dependency on SIL.Core.
But probably more importantly, I was thinking that this assembly will only be used in the build process, not in the app. Am I correct in thinking that means an acknowledgement here will never get used? If that's true, we may consider removing the acknowledgements from Palaso.BuildTasks which also added a dependency on SIL.Core.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by gmartin7** [comment]
Review status: 1 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs, line 10 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0HLgn82XArHN3uOux:-Kl0NVkU4KiwaRY2RAg0:b-gdtdof) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/Palaso.MSBuildTasks.AWS/Properties/AssemblyInfo.cs#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Actually, I'm reconsidering this. I went to add it and realized it was going to add a dependency on SIL.Core.
But probably more importantly, I was thinking that this assembly will only be used in the build process, not in the app. Am I correct in thinking that means an acknowledgement here will never get used? If that's true, we may consider removing the acknowledgements from Palaso.BuildTasks which also added a dependency on SIL.Core.
</blockquote></details>

Yeah, that sounds right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by JohnThomson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs, line 2 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-KlQJ47Egb1cSAv9fn9o:-KlQJ47F_cEThM7OAOYV:bohky17) ([raw file](https://github.com/sillsdev/libpalaso/blob/3029cf3f76cd02d6d7674cd775c2a66b8a6c77bd/SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs#L2)):*
> ```Smalltalk
> /*
>  * Original code from https://github.com/JohnThomson/Snowcode.S3BuildPublisher
> ```

I think we should acknowledge the original author rather than me...maybe John Thomson's fork of ...? I didn't change much, most of the code here is probably his unchanged work.

---

*[SIL.BuildTasks.AWS/S3/S3Helper.cs, line 79 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-KlQK95iHm8e3B_UiRhS:-KlQK95iHm8e3B_UiRhT:b-y46xgr) ([raw file](https://github.com/sillsdev/libpalaso/blob/3029cf3f76cd02d6d7674cd775c2a66b8a6c77bd/SIL.BuildTasks.AWS/S3/S3Helper.cs#L79)):*
> ```Smalltalk
> 		#region Private Methods
> 
> 		private void CreateBucketIfNeeded(string bucketName)
> ```

Wonder if we'd actually be better off without this? It would simplify the code further, and I don't see any reason we need to publish files without manually creating the destination bucket, and if this code can't be used to create buckets there is one less way anyone who compromises our security can use it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by andrew-polk** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks.AWS/Properties/AssemblyInfo.cs, line 10 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-Kl0HLgn82XArHN3uOux:-KlTaSkWRxysPz-LCxTH:b-bdn9zn) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ec01c0ba15f54f9b0c7af568f046fad51c362a7/SIL.BuildTasks.AWS/Properties/AssemblyInfo.cs#L10)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Yeah, that sounds right.
</blockquote></details>

Ok, I'll leave it off, then.

---

*[SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs, line 2 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-KlQJ47Egb1cSAv9fn9o:-KlTaW6Mgr0C2c8FK4nH:b-wa401z) ([raw file](https://github.com/sillsdev/libpalaso/blob/3029cf3f76cd02d6d7674cd775c2a66b8a6c77bd/SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs#L2)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think we should acknowledge the original author rather than me...maybe John Thomson's fork of ...? I didn't change much, most of the code here is probably his unchanged work.
</blockquote></details>

Yeah... I struggled with how to do this. Your fork, of course, references the original source, so someone could follow the chain. In a situation in which I didn't know the middle man, I would just reference where I obtained it, and anyone who wanted to know could follow the chain.
But I understand your point.
One thing which is confusing is that the link to the original you gave doesn't even work. It appears they archived their stuff on Google code, so this is really the only useful link remaining: https://code.google.com/archive/p/snowcode/.
Another point of confusion is that link now says license is MIT but yours says Ms-PL. So I have no idea how to handle that.

I suppose I could just put (similar to your suggestion):

Original code from John Thomson's fork of https://code.google.com/archive/p/snowcode/
License: MIT (http://www.opensource.org/licenses/mit-license.php)

The code has been modified (mostly in the authentication area) and greatly simplified (extracting only the bits we are using).

How does that look?

---

*[SIL.BuildTasks.AWS/S3/S3Helper.cs, line 79 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-KlQK95iHm8e3B_UiRhS:-KlTdJ7f2Z09sS_koZos:bbx8uz4) ([raw file](https://github.com/sillsdev/libpalaso/blob/3029cf3f76cd02d6d7674cd775c2a66b8a6c77bd/SIL.BuildTasks.AWS/S3/S3Helper.cs#L79)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Wonder if we'd actually be better off without this? It would simplify the code further, and I don't see any reason we need to publish files without manually creating the destination bucket, and if this code can't be used to create buckets there is one less way anyone who compromises our security can use it.
</blockquote></details>

Hm, good point. I'll look to remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by JohnThomson** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs, line 2 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-KlQJ47Egb1cSAv9fn9o:-KlTewrywpUo8IEssfkJ:b-kpn9u3) ([raw file](https://github.com/sillsdev/libpalaso/blob/3029cf3f76cd02d6d7674cd775c2a66b8a6c77bd/SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs#L2)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah... I struggled with how to do this. Your fork, of course, references the original source, so someone could follow the chain. In a situation in which I didn't know the middle man, I would just reference where I obtained it, and anyone who wanted to know could follow the chain.
But I understand your point.
One thing which is confusing is that the link to the original you gave doesn't even work. It appears they archived their stuff on Google code, so this is really the only useful link remaining: https://code.google.com/archive/p/snowcode/.
Another point of confusion is that link now says license is MIT but yours says Ms-PL. So I have no idea how to handle that.

I suppose I could just put (similar to your suggestion):

Original code from John Thomson's fork of https://code.google.com/archive/p/snowcode/
License: MIT (http://www.opensource.org/licenses/mit-license.php)

The code has been modified (mostly in the authentication area) and greatly simplified (extracting only the bits we are using).

How does that look?
</blockquote></details>

LGTM. I can't imagine any reason I would have done a license other than MIT unless they had. So we can consider mine changed to that and follow along.
Actually we could just regard this new project as a team effort and not mention me at all...just 

Original code from https://code.google.com/archive/p/snowcode/
License: MIT (http://www.opensource.org/licenses/mit-license.php)

(etc)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by JohnThomson** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by andrew-polk** [comment]
Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs, line 2 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-KlQJ47Egb1cSAv9fn9o:-KlThla6lqTDXnmey8ep:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3029cf3f76cd02d6d7674cd775c2a66b8a6c77bd/SIL.BuildTasks.AWS/S3/S3BuildPublisher.cs#L2)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

LGTM. I can't imagine any reason I would have done a license other than MIT unless they had. So we can consider mine changed to that and follow along.
Actually we could just regard this new project as a team effort and not mention me at all...just 

Original code from https://code.google.com/archive/p/snowcode/
License: MIT (http://www.opensource.org/licenses/mit-license.php)

(etc)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529)*

**Comment by JohnThomson** [comment]
:lgtm:

---

Reviewed 3 of 13 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/529#-:-KlTl8uiM41C6smZaNYf:bnfp4nl)*

**Pull request merged**
