### PR TITLE
Allow private language tags and related improvements

### PR DESCRIPTION
**Pull request by JohnThomson**
This is a partial fix for BL-9004, a crash that was happening if you open the scripts and variants control again after entering a private use language code other than qaa.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/973)

### CODE REVIEW

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/973)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jasonleenaylor)

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/973)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, line 340 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/973#-MJYC0Z27QSQECR322av:-MJYC0Z27QSQECR322aw:b39q5su) ([raw file](https://github.com/sillsdev/libpalaso/blob/2905d6e68ab75bfeb0bd2eeea6daf176efd7dad5/SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs#L340)):*
> ```
> if (_model.LanguageTagContainsScriptRegionVariantInfo || !_model.MatchingLanguages.Contains(_model.SelectedLanguage))
> ```
This is the only line in this PR that gives me pause.

I wonder if there is a better way this work. It feels too permissive. Is there another way to check if the SelectedLanguage code is a custom unknown?

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/973)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @jasonleenaylor)

___
*[SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, line 340 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/973#-MJYC0Z27QSQECR322av:-MJbzckG0g4kNY-eoNxG:b-rfdz83) ([raw file](https://github.com/sillsdev/libpalaso/blob/2905d6e68ab75bfeb0bd2eeea6daf176efd7dad5/SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs#L340)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

> ```
> if (_model.LanguageTagContainsScriptRegionVariantInfo || !_model.MatchingLanguages.Contains(_model.SelectedLanguage))
> ```
This is the only line in this PR that gives me pause.

I wonder if there is a better way this work. It feels too permissive. Is there another way to check if the SelectedLanguage code is a custom unknown?
</blockquote></details>

I changed it to make explicit that only custom language codes are to be shown

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/973)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/973)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
