### PR TITLE
Add some useful classes to SIL.ObjectModel namespace

### PR DESCRIPTION
**Pull request by ddaspit**
* added various comparers and equality comparers
* added UnorderedTuple
* added NullableValue

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/371)

### CODE REVIEW

**Comment by regnrand** [comment]
Can you add tests?

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/371#-:-KDTZQyoLo2EUZJrOoeB:-311602829)*

**Comment by ddaspit** [comment]
Which of the classes do you think need unit tests? They are all very simple classes that are provided for convenience purposes. The comparer classes are all simple wrappers for delegates or .NET calls. The SequenceCompare extension method is probably the most complicated bit of code. I could add a unit test for that. I am all for unit tests, I just don't want to do them just to do them.

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/371#-:-KDW5WYnWxsmvVjpBSlE:-1478886054)*

**Comment by ddaspit** [comment]
I added some unit tests for SequenceCompare, NullableValue, and UnorderedTuple. These needed unit tests. There isn't much to test for the comparer classes, so I didn't add any tests for those.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/371#-:-KDWJqSwDMVrY97337Ew:-2146934903)*

**Comment by regnrand** [comment]
I never actually looked at any of the new code, but I saw none of it had any tests. The fact that there were test failures, when added, proved that code was not so 'simple', after all. Tests demonstrate the new code actually does what is expected from the start, as well as make sure they still work after other changes are made.

Are you satisfied that nobody will use '==', unless they want reference equals checking, which they could do using a more explicit method? Again, I only glanced at some random new code for use of that operator.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/371#-:-KDZ6lOcQ6YrFBfHH7oA:14102112)*

**Comment by ddaspit** [comment]
Yeah, I acknowledged that the code that I wrote unit tests for needed unit tests. I just wasn't sure about the comparer classes. All of this was code that I just copied over from somewhere else, because I thought it might be generally useful. It didn't have any unit tests before. I think I'm okay with the equality checking.

I think I addressed all of your comments, so I am going to go ahead and merge this PR.

---

Review status: 0 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/371#-:-KDaOkw93zH5PdajK274:-200789416)*

**Pull request merged**
