### PR TITLE
Remove old CC IGO license option from UI

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1278)

### CODE REVIEW

**Comment by andrew-polk** [comment]
FWIW, Bloom users still want this option.
It doesn't matter too much since we have moved to a new UI.
But I think this deserves a major version number bump.

**Comment by andrew-polk** [comment]
Hm. Actually, it does matter in the sense that the IntergovernmentalOriganizationQualifier property is still actively used in Bloom code.
So, if you're going to mark it obsolete due to the misspelling, we still need a new property spelled correctly (and the major version bump).

**Comment by papeh** [comment]
I didn't see it in the Bloom UI, but if you're still using it, we can keep the property.

**Comment by papeh** [comment]
Looks like Bloom is the only client in all of GitHub that specifically references the IGO license, so we should safely be able to remove the UI but keep the property.

Just curious, do you know if or why the IGO version is still needed now that 4.0 is out? If it really is needed, perhaps it should be left in the UI.

**Comment by hatton** [comment]
> Just curious, do you know if or why the IGO version is still needed now that 4.0 is out?

Use of IGO was required by the publisher at the time the books were published. We don't retroactively change publisher's licenses.

**Comment by papeh** [comment]
> Use of IGO was required by the publisher at the time the books were published. We don't retroactively change publisher's licenses.

Thanks! So, not something we expect users to need to edit.

**Comment by papeh** [comment]
@andrew-polk @hatton can this be merged?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 5 of 5 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1278)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @papeh)

___
*[`SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs` line 374 at r4](https://reviewable.io/reviews/sillsdev/libpalaso/1278#-N_uFtmv5kxhoih4xWQG:-N_uFtmv5kxhoih4xWQH:b-8ckv0r) ([raw file](https://github.com/sillsdev/libpalaso/blob/465620bd8d658cdda416c5139bb3b07d1f738607/SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs#L374)):*
> ```Smalltalk
> 		}
> 
> 		public bool IntergovernmentalOrganizationQualifier
> ```

Worth a comment stating that while the libpalaso UI doesn't use this, we keep it for legacy reasons?
And probably even worth an explicit mention that Bloom does still use/display it for legacy reasons?
___
*[`SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs` line 384 at r4](https://reviewable.io/reviews/sillsdev/libpalaso/1278#-N_uFMHk5-p_GuzIizaR:-N_uFMHk5-p_GuzIizaS:btaf202) ([raw file](https://github.com/sillsdev/libpalaso/blob/4b260d0f78754c6603b7171f1f6a8d89637f361f/SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs#L384)):*
> ```Smalltalk
> 			this._L10NSharpExtender.SetLocalizableToolTip(this._useIGOLicenseVersion, null);
> 			this._L10NSharpExtender.SetLocalizationComment(this._useIGOLicenseVersion, null);
> 			this._L10NSharpExtender.SetLocalizingId(this._useIGOLicenseVersion, "MetadataEditor.CreativeCommons.Intergovernmental");
> ```

I'm not sure what the correct procedure for localization is these days in libpalaso. Does this string removal warrant any other changes in localization files?

**Review by andrew-polk — COMMENTED** [review]
I added a couple minor things. Feel free to merge when you believe they are sufficiently dealt with.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1278#-:-N_uGNog38Iy4icjO74m:bajkfa0)* status: all files reviewed, 2 unresolved discussions (waiting on @hatton and @papeh)

**Review by papeh — COMMENTED** [review]
> Dismissed @andrew-polk from a discussion.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1278)* status: 11 of 15 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @hatton)

___
*[`SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs` line 374 at r4](https://reviewable.io/reviews/sillsdev/libpalaso/1278#-N_uFtmv5kxhoih4xWQG:-N_uNdfa0DvMoqBpSWdU:bb6un1j) ([raw file](https://github.com/sillsdev/libpalaso/blob/465620bd8d658cdda416c5139bb3b07d1f738607/SIL.Windows.Forms/ClearShare/CreativeCommonsLicense.cs#L374)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Worth a comment stating that while the libpalaso UI doesn't use this, we keep it for legacy reasons?
And probably even worth an explicit mention that Bloom does still use/display it for legacy reasons?
</blockquote></details>

Done
___
*[`SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs` line 384 at r4](https://reviewable.io/reviews/sillsdev/libpalaso/1278#-N_uFMHk5-p_GuzIizaR:-N_uNhP72fu3jrmphp87:b-agdglq) ([raw file](https://github.com/sillsdev/libpalaso/blob/4b260d0f78754c6603b7171f1f6a8d89637f361f/SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs#L384)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm not sure what the correct procedure for localization is these days in libpalaso. Does this string removal warrant any other changes in localization files?
</blockquote></details>

Thanks for thinking of this.
L10NSharp reads and writes xlf files that are uploaded to and downloaded from Crowdin.com. Extra strings are not a problem (apart from creating extra work for translators).
I've updated the source files here and in Crowdin.

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1278)* status: 10 of 15 files reviewed, 1 unresolved discussion (waiting on @andrew-polk, @hatton, and @jasonleenaylor)

___
*[`SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs` line 384 at r4](https://reviewable.io/reviews/sillsdev/libpalaso/1278#-N_uFMHk5-p_GuzIizaR:-N_uRgZO9mSMpoq7psJW:bqwiyr5) ([raw file](https://github.com/sillsdev/libpalaso/blob/4b260d0f78754c6603b7171f1f6a8d89637f361f/SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs#L384)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Thanks for thinking of this.
L10NSharp reads and writes xlf files that are uploaded to and downloaded from Crowdin.com. Extra strings are not a problem (apart from creating extra work for translators).
I've updated the source files here and in Crowdin.
</blockquote></details>

Actually, the checked-in xlf files seem to be outdated; perhaps @jasonleenaylor can help next week. There are added strings in my next PR.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
