### PR TITLE
LT-21140: Don't duplicate URLs

### PR DESCRIPTION
**Pull request by papeh**
To prevent duplicate URLs in LDML files, store URLs in Sets instead of Lists.

FieldWorks users have found unpredictable situations that
exponentially replicate Keyboard URLs in LDML files:
https://jira.sil.org/browse/LT-21140

+semver: major

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1231)

### CODE REVIEW

**Comment by papeh** [comment]
If this weren't already a public API, we could simply make these URL lists Sets instead. Perhaps we still should.

Following feedback, I plan to implement the remaining List methods. I also plan to use SortedSetList for other URL lists in LDML files.

**Comment by jasonleenaylor** [comment]
*[`SIL.TestUtilities/FluentAssertXml.cs` line 174 at r4](https://reviewable.io/reviews/sillsdev/libpalaso/1231#-NEBgujb-CqV-GKXepg6:-NEBgujb-CqV-GKXepg7:b18a0in) ([raw file](https://github.com/sillsdev/libpalaso/blob/61109c7861eca2b57932570f652e540d7951b290/SIL.TestUtilities/FluentAssertXml.cs#L174)):*
> ```Smalltalk
> 		/// </summary>
> 		public void HasSpecifiedNumberOfMatchesForXpath(int count, string xpath, XmlNamespaceManager nameSpaceManager = null)
> 		{
> ```

This isn't needed for these sets of changes, and I'd rather you not.

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 3 files at r3, 7 of 7 files at r4, 5 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1231)* status: all files reviewed, 1 unresolved discussion (waiting on @papeh)

___
*[`SIL.WritingSystems.Tests/LdmlDataMapperTests.cs` line 1640 at r7](https://reviewable.io/reviews/sillsdev/libpalaso/1231#-NEC98w9-ghJNAq0x-96:-NEC98w9-ghJNAq0x-97:b-h1oyag) ([raw file](https://github.com/sillsdev/libpalaso/blob/3826c7938ba4e8716a9d2d48beb82ef676bad987/SIL.WritingSystems.Tests/LdmlDataMapperTests.cs#L1640)):*
> ```Smalltalk
> 			// SUT
> 			dataMapper.Read(tempFile.Path, ws);
> 			Assert.That(ws.Fonts[0].Urls.Count, Is.EqualTo(2), string.Join(Environment.NewLine, ws.Fonts[0].Urls));
> ```

I would have expected 1, but I suppose there were two to begin with and you duplicated the first one...should we do a set-up assertion to show that the xml has 3 items?



_Code quote:_
```Smalltalk
2
```

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1231)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @jasonleenaylor)

___
*[`SIL.WritingSystems.Tests/LdmlDataMapperTests.cs` line 1640 at r7](https://reviewable.io/reviews/sillsdev/libpalaso/1231#-NEC98w9-ghJNAq0x-96:-NECX1ah8g7aM4kpNSDM:bb6un1j) ([raw file](https://github.com/sillsdev/libpalaso/blob/3826c7938ba4e8716a9d2d48beb82ef676bad987/SIL.WritingSystems.Tests/LdmlDataMapperTests.cs#L1640)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I would have expected 1, but I suppose there were two to begin with and you duplicated the first one...should we do a set-up assertion to show that the xml has 3 items?
</blockquote></details>

Done
___
*[`SIL.TestUtilities/FluentAssertXml.cs` line 174 at r4](https://reviewable.io/reviews/sillsdev/libpalaso/1231#-NEBgujb-CqV-GKXepg6:-NECTyCz5608EA72ML9Q:b-ys5k3k) ([raw file](https://github.com/sillsdev/libpalaso/blob/61109c7861eca2b57932570f652e540d7951b290/SIL.TestUtilities/FluentAssertXml.cs#L174)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This isn't needed for these sets of changes, and I'd rather you not.
</blockquote></details>

Undone

**Review by jasonleenaylor — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1231)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Pull request merged**
