### PR TITLE
(auto publish l10n; auto download l10n)

### PR DESCRIPTION
**Pull request by papeh**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1286)

### CODE REVIEW

**Comment by tombogle** [comment]
*[`DistFiles/Palaso.en.xlf` line 5 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfw1y7K9KeIQsUPeCmC:-Nfw1y7K9KeIQsUPeCmD:btdrn3m) ([raw file](https://github.com/sillsdev/libpalaso/blob/244547fcc5befbfc8ddd430fae2553b47c878119/DistFiles/Palaso.en.xlf#L5)):*
> ```XML
>   <file source-language="en" product-version="12.0.1" original="Palaso.dll" datatype="plaintext">
>     <body>
>       <trans-unit id="AboutDialog.BuiltOnDate">
> ```

Might be worth a little more explanation in the readme file as to why this empty shell is needed. (I'm guessing the only useful thing it actually supplies is the "original" attribute, right?

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1286)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @tombogle)

___
*[`DistFiles/Palaso.en.xlf` line 5 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfw1y7K9KeIQsUPeCmC:-NfwCWTMCvhN6MqTfC6p:bcvwdho) ([raw file](https://github.com/sillsdev/libpalaso/blob/244547fcc5befbfc8ddd430fae2553b47c878119/DistFiles/Palaso.en.xlf#L5)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Might be worth a little more explanation in the readme file as to why this empty shell is needed. (I'm guessing the only useful thing it actually supplies is the "original" attribute, right?
</blockquote></details>

Turns out it was needed only to locate DistFiles. Instead, SIL.Windows.Forms.TestApp now uses the XLF file for the chosen locale.

**Comment by tombogle** [comment]
*[`.gitignore` line 45 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-NfwEMpD7bUd-pc44MuI:-NfwEMpD7bUd-pc44MuJ:brzw9bb) ([raw file](https://github.com/sillsdev/libpalaso/blob/225bb1ba23602f62a7d0f3e65f49f4a57eec092d/.gitignore#L45)):*
> ```ignore
> /SIL.Windows.Forms/bin-Designer/**
> launchSettings.json
> DistFiles/*.xlf
> ```

If there are no .xlf files checked in anywhere, maybe it would be best to just have *.xlf

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1286)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @tombogle)

___
*[`.gitignore` line 45 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-NfwEMpD7bUd-pc44MuI:-NfwH2fi-DhPE2HRJwlW:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/225bb1ba23602f62a7d0f3e65f49f4a57eec092d/.gitignore#L45)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

If there are no .xlf files checked in anywhere, maybe it would be best to just have *.xlf
</blockquote></details>

Done.

**Comment by tombogle** [comment]
*[`SIL.Core.Tests/CommandLineProcessing/CommandLineRunnerTests.cs` line 55 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfy1vzJErV2VANg2M4v:-Nfy1vzK6t29Zoq4OmeN:b-ywfmh9) ([raw file](https://github.com/sillsdev/libpalaso/blob/757bfef9e72e75c61a0978e6a631bb235a265c35/SIL.Core.Tests/CommandLineProcessing/CommandLineRunnerTests.cs#L55)):*
> ```Smalltalk
> 			var bldr = new StringBuilder();
> 			CommandLineRunner.Run(App, "CommandLineRunnerTest", null, string.Empty, 100,
> 				progress, s => bldr.AppendLine($"{++linesReceivedAsynchronously}: '{s}'"), null, true);
> ```

Does this actually succeed on Linux now?

**Comment by tombogle** [comment]
*[`TestApps/SIL.Windows.Forms.TestApp/Program.cs` line 41 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfy2r0oCtgWZaTDAPC7:-Nfy2r0oCtgWZaTDAPC8:bfwaoq5) ([raw file](https://github.com/sillsdev/libpalaso/blob/757bfef9e72e75c61a0978e6a631bb235a265c35/TestApps/SIL.Windows.Forms.TestApp/Program.cs#L41)):*
> ```Smalltalk
> 				else
> 				{
> 					// Test command-line runner's ability to read console output and time out.
> ```

I really don't understand what is being tested here. Maybe a more robust comment is in order. Since you're now doing this before the LM is created, if the timeout happens, is there an error dialog or error message that appears that we might have wanted to be displayed in French?

**Review by tombogle — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 5 of 5 files at r2, 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1286)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @papeh)

___
*[`DistFiles/Palaso.en.xlf` line 5 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfw1y7K9KeIQsUPeCmC:-NfwFEQqCBkUckwF38-5:b-8n7cmw) ([raw file](https://github.com/sillsdev/libpalaso/blob/244547fcc5befbfc8ddd430fae2553b47c878119/DistFiles/Palaso.en.xlf#L5)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Turns out it was needed only to locate DistFiles. Instead, SIL.Windows.Forms.TestApp now uses the XLF file for the chosen locale.
</blockquote></details>

If you didn't already, check to be sure that the generated original attribute is

**Review by papeh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1286)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @tombogle)

___
*[`DistFiles/Palaso.en.xlf` line 5 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfw1y7K9KeIQsUPeCmC:-Ng066WB159X595ChhzV:b2w0uwb) ([raw file](https://github.com/sillsdev/libpalaso/blob/244547fcc5befbfc8ddd430fae2553b47c878119/DistFiles/Palaso.en.xlf#L5)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

If you didn't already, check to be sure that the generated original attribute is
</blockquote></details>

You mean Palaso.en.xlf? I tested, and that's not required for the app to run in English on Windows. I haven't tested on Linux.
___
*[`SIL.Core.Tests/CommandLineProcessing/CommandLineRunnerTests.cs` line 55 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfy1vzJErV2VANg2M4v:-Ng04UGNA0Fr9eC0g59L:b-tmltqy) ([raw file](https://github.com/sillsdev/libpalaso/blob/757bfef9e72e75c61a0978e6a631bb235a265c35/SIL.Core.Tests/CommandLineProcessing/CommandLineRunnerTests.cs#L55)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

Does this actually succeed on Linux now?
</blockquote></details>

Yes; it succeeds on TeamCity.
___
*[`TestApps/SIL.Windows.Forms.TestApp/Program.cs` line 41 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfy2r0oCtgWZaTDAPC7:-Ng054mNCAYoEQI70_ja:b-5zjvdw) ([raw file](https://github.com/sillsdev/libpalaso/blob/757bfef9e72e75c61a0978e6a631bb235a265c35/TestApps/SIL.Windows.Forms.TestApp/Program.cs#L41)):*
<details><summary><i>Previously, tombogle (Tom Bogle) wrote…</i></summary><blockquote>

I really don't understand what is being tested here. Maybe a more robust comment is in order. Since you're now doing this before the LM is created, if the timeout happens, is there an error dialog or error message that appears that we might have wanted to be displayed in French?
</blockquote></details>

Maybe more robust code is in order. I'm going to move this to its own test app.

**Comment by tombogle** [comment]
*[`DistFiles/Palaso.en.xlf` line 5 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1286#-Nfw1y7K9KeIQsUPeCmC:-Ng0FieOCIHEdj_lqO3J:b-1p1rh0) ([raw file](https://github.com/sillsdev/libpalaso/blob/244547fcc5befbfc8ddd430fae2553b47c878119/DistFiles/Palaso.en.xlf#L5)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

You mean Palaso.en.xlf? I tested, and that's not required for the app to run in English on Windows. I haven't tested on Linux.
</blockquote></details>

Oops. Looks like I never finished writing that sentence. I was going to (and now have) check to see how the code worked. It looks like l10n.proj does correctly specify the extension in the -o parameter when calling ExtractXliff, so everything should be fine.

**Review by tombogle — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1286)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @papeh)

**Pull request merged**
