### PR TITLE
Fix bug where PalasoImage disposes of its Image prematurely

### PR DESCRIPTION
**Pull request by sujeffreyl**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1067)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1067)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs, line 107 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1067#-MWjUWuk5avopslgsLth:-MWjUWuk5avopslgsLti:bgo10r9) ([raw file](https://github.com/sillsdev/libpalaso/blob/17d246913b22fd697452723ea2af899cd22be219/SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs#L107)):*
> ```Smalltalk
> 				// This test checks for if the PalasoImage's Image member has been disposed of,
> 				// not whether or not the PalasoImage is disposed of.
> 				Assert.AreNotEqual("**** Disposed by palasoImage", pi.Image.Tag);
> ```

Thinking out loud... This string could easily (however unlikely) be changed at some point which would make the verification invalid.
Could we instead directly determine if it is disposed by trying to do something with it and verifying we don't get `ObjectDisposedException`?

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1067)* status: all files reviewed, 1 unresolved discussion (waiting on @sujeffreyl)

___
*[SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs, line 107 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1067#-MWjUWuk5avopslgsLth:-MWjWD_57uD8B3xjrOii:b-frnn09) ([raw file](https://github.com/sillsdev/libpalaso/blob/17d246913b22fd697452723ea2af899cd22be219/SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs#L107)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Thinking out loud... This string could easily (however unlikely) be changed at some point which would make the verification invalid.
Could we instead directly determine if it is disposed by trying to do something with it and verifying we don't get `ObjectDisposedException`?
</blockquote></details>

Of course, it would also be simple to make the string in question a public const. But that seems a little silly.

**Comment by jasonleenaylor** [comment]
___
*[SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs, line 107 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1067#-MWjUWuk5avopslgsLth:-MWjaZNn1OzDQyA_rWPi:b-dfn4z3) ([raw file](https://github.com/sillsdev/libpalaso/blob/17d246913b22fd697452723ea2af899cd22be219/SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs#L107)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Of course, it would also be simple to make the string in question a public const. But that seems a little silly.
</blockquote></details>

I just reviewed the entire PalasoImage file and the thing is a bit of a mess. I'm guessing it hasn't had any love in a few years time, and probably won't see any again in the near future. It should be obvious to whoever makes the change that they broke this test and the odds of that  could be improved by adding a hint in the failure message.

**Review by sujeffreyl — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1067)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs, line 107 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1067#-MWjUWuk5avopslgsLth:-MWjiWNZ6ZJQZntjOCyU:b-eop43h) ([raw file](https://github.com/sillsdev/libpalaso/blob/17d246913b22fd697452723ea2af899cd22be219/SIL.Windows.Forms.Tests/ImageToolbox/PalasoImageTests.cs#L107)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I just reviewed the entire PalasoImage file and the thing is a bit of a mess. I'm guessing it hasn't had any love in a few years time, and probably won't see any again in the near future. It should be obvious to whoever makes the change that they broke this test and the odds of that  could be improved by adding a hint in the failure message.
</blockquote></details>

Jason, unfortunately if the string is modified, the test will continue to succeed, and if there's a regression, the test would then fail to catch it :( :( :(

(that's why I was looking into pi.Disposed instead, but was disappointed it didn't work)
Andrew's idea about an exception looks like it works. (The exception isn't ObjectDisposedException, but whatever)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1067)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Review by StephenMcConnel — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1067#-:-MWk9rH_3FoNZyHFoP7C:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sujeffreyl)

**Pull request merged**
