### PR TITLE
Enable the reading of the new information in metadata version 2

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/586)

### CODE REVIEW

**Comment by andrew-polk** [comment]
This is a bit of a work in progress, but I wanted to get it out there in front of Tom for review. Please do not merge.

**Comment by andrew-polk** [comment]
Ok, I think this is as ready as it is going to be (before it gets picked apart in review)...

**Comment by jasonleenaylor** [comment]
*[SIL.DblBundle/Text/DblTextMetadata.cs, line 477 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/586#-L-8nFKI6CFOKg0P2ys_:-L-8nFKI6CFOKg0P2ysa:b-l68lix) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebf1389da8787b5b32516211eab7e8c1fd3d045d/SIL.DblBundle/Text/DblTextMetadata.cs#L477)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// Prevents Code_DeprecatedXml from being serialized
> ```

Is this summary comment correct? I don't see anything in this book class that deals with Code_DeprecatedXml

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/586)*

**Comment by jasonleenaylor** [comment]
*[SIL.DblBundle/Text/DblTextMetadata.cs, line 477 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/586#-L-8nFKI6CFOKg0P2ys_:-L-8nb-zZwSquyCZuYzO:b-l8t3mx) ([raw file](https://github.com/sillsdev/libpalaso/blob/ebf1389da8787b5b32516211eab7e8c1fd3d045d/SIL.DblBundle/Text/DblTextMetadata.cs#L477)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Is this summary comment correct? I don't see anything in this book class that deals with Code_DeprecatedXml
</blockquote></details>

Looks like the comment was just copied from above, it should be updated for the real purpose here in this class.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/586)*

**Comment by andrew-polk** [comment]
We decided this is not a good approach (though we still don't have a good one...)

**Pull request closed without merging**
