### PR TITLE
Changed SIL.Core to no longer reference certain problematic DLLs

### PR DESCRIPTION
**Pull request by FoolRunning**
Changed SIL.Core to no longer reference System.Drawing, System.Management, or System.Configuration to aid some work being done by Tom Hindle. This resulted in moving 4 classes to a new DLL (SIL.Core.Desktop)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/504)

### CODE REVIEW

**Comment by andrew-polk** [comment]
I don't see any problems with your changes.
Some thoughts:
- We ought to make a deliberate decision about namespace for the new assembly after weighing pros and cons.
- Depending on the order in which this and other outstanding PRs are merged, we need to be careful to do proper clean up. For example, if this gets merged before the .NET 4.6.1 change, these new dlls will need to be moved to .NET 4.6.1 in that PR. If that gets merged first, they need to be change to .NET 4.6.1 in this PR.

---

Reviewed 49 of 49 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Core.Tests/IO/FileUtilsTests.cs, line 95 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-KjiF3ozhTlU2n7KW3jQ:-KjiF3ozhTlU2n7KW3jR:b-ykwn0d) ([raw file](https://github.com/sillsdev/libpalaso/blob/5e670bbff1119fb3c0b3d92badc9d027f6c655c9/SIL.Core.Tests/IO/FileUtilsTests.cs#L95)):*
> ```Smalltalk
> 				// Since UsbDriveInfo was moved to SIL.Core.Desktop, we need to use reflection to access 
> 				// the drives since we can't add a reference to SIL.Core.Desktop.
> 				Assembly coreDesktopAssembly = Assembly.Load("SIL.Core.Desktop");
> ```

Not a requirement, but you could probably simplify this code with ReflectionHelper

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-:-KjiFSsP_bLJLJtg8kXX:bljxgqn)*

**Comment by FoolRunning** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Core.Tests/IO/FileUtilsTests.cs, line 95 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-KjiF3ozhTlU2n7KW3jQ:-KjiHFmvYLMMk1F5Qj12:b-yxqab4) ([raw file](https://github.com/sillsdev/libpalaso/blob/5e670bbff1119fb3c0b3d92badc9d027f6c655c9/SIL.Core.Tests/IO/FileUtilsTests.cs#L95)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Not a requirement, but you could probably simplify this code with ReflectionHelper
</blockquote></details>

No I can't, unfortunately, because ReflectionHelper is in SIL.Windows.Forms. :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/504)*

**Comment by FoolRunning** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Core.Tests/IO/FileUtilsTests.cs, line 95 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-KjiF3ozhTlU2n7KW3jQ:-KjiLcRIbexUz_afhjyb:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/5e670bbff1119fb3c0b3d92badc9d027f6c655c9/SIL.Core.Tests/IO/FileUtilsTests.cs#L95)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

No I can't, unfortunately, because ReflectionHelper is in SIL.Windows.Forms. :(
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/504)*

**Comment by andrew-polk** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[SIL.Core.Desktop.Tests/NoUITest.cs, line 7 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-KjnbQHLMPY4DzbZquyb:-KjnbQHLMPY4DzbZquyc:bu6wls4) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Desktop.Tests/NoUITest.cs#L7)):*
> NoUITest

How about ValidateReferencesTests?
Same for other assembly.

---

*[SIL.Core.Desktop.Tests/NoUITest.cs, line 10 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-KjnbX3_yOKm0azbUx9Q:-KjnbX3_yOKm0azbUx9R:b-htcvsp) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Desktop.Tests/NoUITest.cs#L10)):*
> TestForNoUIRefs

How about EnsureNoReferenceToWindowsForms or EnsureNoWindowsFormsReference?

---

*[SIL.Core.Tests/NoUITest.cs, line 10 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-Kjnc94FccJ4B-Nf9h7a:-Kjnc94FccJ4B-Nf9h7b:b-d98ojo) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Tests/NoUITest.cs#L10)):*
> TestForNoUIRefs

How about EnsureNoUIReferences?

---

*[SIL.Core.Tests/NoUITest.cs, line 18 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-Kjnbzwv_RGRndJRWRxa:-KjnbzwwKYS1NsqIESah:bsaf1g3) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Tests/NoUITest.cs#L18)):*
> ```Smalltalk
> 			{
> 				// If this test fails, then make sure you didn't add a reference to one of the following DLLs
> 				// Any code that depends on these should be added to SIL.Core.Desktop.
> ```

This would be a good place to document why we don't want those references in this project.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/504)*

**Comment by FoolRunning** [comment]
Review status: 31 of 35 files reviewed at latest revision, 4 unresolved discussions.

---

*[SIL.Core.Desktop.Tests/NoUITest.cs, line 7 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-KjnbQHLMPY4DzbZquyb:-Kjndc19lpqGq2eVrO8C:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Desktop.Tests/NoUITest.cs#L7)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> NoUITest

How about ValidateReferencesTests?
Same for other assembly.
</blockquote></details>

Done.

---

*[SIL.Core.Desktop.Tests/NoUITest.cs, line 10 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-KjnbX3_yOKm0azbUx9Q:-KjndeFmmeNArQ7Ktk4N:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Desktop.Tests/NoUITest.cs#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> TestForNoUIRefs

How about EnsureNoReferenceToWindowsForms or EnsureNoWindowsFormsReference?
</blockquote></details>

Done.

---

*[SIL.Core.Tests/NoUITest.cs, line 10 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-Kjnc94FccJ4B-Nf9h7a:-KjndfjdJn5Lh49Fof7C:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Tests/NoUITest.cs#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> TestForNoUIRefs

How about EnsureNoUIReferences?
</blockquote></details>

Done.

---

*[SIL.Core.Tests/NoUITest.cs, line 18 at r2](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-Kjnbzwv_RGRndJRWRxa:-Kjndgb1omp1y97ZXzlo:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3b1af6c1e5ff42aaf2019c01af90276812d50d0d/SIL.Core.Tests/NoUITest.cs#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This would be a good place to document why we don't want those references in this project.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/504)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/504#-:-KjnnbtxlnfHZAC6X7NF:bnfp4nl)*

**Pull request merged**
