### PR TITLE
Change framework version 4.6.1

### PR DESCRIPTION
**Pull request by JamesPrabu**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/484)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Doesn't this need to coincide with a version number change? 4.0?

**Comment by hatton** [comment]
We are currently discussing whether to put this in a new libpalaso 4.0 branch, or to put the current libpalaso into a 3.x branch.

**Comment by andrew-polk** [comment]
Need to investigate build failures

**Comment by hatton** [comment]
@JamesPrabu I think this PR needs fixing; it is trying to merge other people's commits in, not just yours.

**Comment by JamesPrabu** [comment]
Fixing linux build failures. We will clear the errors before our next commit.

**Comment by JamesPrabu** [comment]
We updated pull request based on latest master branch.

**Pull request closed without merging**
