### PR TITLE
[API]Windows Keyboarding Overhaul

### PR DESCRIPTION
**Pull request by jasonleenaylor**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/669)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
There is still some work to be done here, but it is ready for at least an initial review.

**Comment by ermshiperete** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs, line 153 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HRYoo_j6AyD8sOb7D:-L8HRYopwwgpwwElpJd-:b-9vr42l) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs#L153)):*
> ```Smalltalk
> 		}
> 
> 		public virtual string GetKeyboardSetupApplication(out string arguments)
> ```

Why do we need both methods? Can this one be made `protected`?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HWol3uBcHusov27ft:-L8HWol3uBcHusov27fu:bda4wfo) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L13)):*
> ```Smalltalk
> namespace SIL.Windows.Forms.Keyboarding.Windows
> {
> 	internal class WindowsKeyboardSwitchingAdapter : IKeyboardSwitchingAdaptor
> ```

A comment might be helpful that mentions what api we now use for keyboard switching. Especially when comparing this to the previous implementation one wonders how it's done now (I no longer see the `ITfInputProcessor*` variables, so I guess it's done differently). Also, I guess we no longer support XP and therefore removed the code for that?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 23 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8H_q6KsKcGip38YGQQ:-L8H_q6KsKcGip38YGQR:bz9gzby) ([raw file](https://github.com/sillsdev/libpalaso/blob/de6b5e98404415f086e54314e31b3fd746c7426c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L23)):*
> ITfInputProcessorProfiles

I didn't check where this (and related interfaces/structs) are defined, but I wonder if it's in our code and we could get rid of some of the definitions if we no longer use them.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 106 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HTkvCdl1UqM79euuq:-L8HTkvCdl1UqM79euur:b-tg2rxh) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L106)):*
> ```Smalltalk
> 			{
> 				// Users can switch the keyboards without switching fields, don't save unrelated IME status
> 				return;
> ```

I probably don't understand why this is needed, but if a user manually switches the keyboard in a field, wouldn't we still want to save the IME status so that when he switches back he will get the same status again?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 155 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HUnSKwlSdqU5dMx6P:-L8HUnSKwlSdqU5dMx6Q:b-q8bgp8) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L155)):*
> ```Smalltalk
> 			{
> 				Win32.ImmSetConversionStatus(contextHandle, winKeyboard.ConversionMode, winKeyboard.SentenceMode);
> 				Timer.Stop();
> ```

We don't have to stop the timer in the else case?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 163 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HUwxL5tOTFC77YBWM:-L8HUwxM_x5WEpwJ9Mxq:b-vl6ar7) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L163)):*
> ```Smalltalk
> 
> 		/// <summary>
> 		/// Implementation is not required because this is not the primary (Type System) adapter.
> ```

This is surprising. I'd have thought that this _is_ the primary adapter. If this is not what else is?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 300 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HWIzviLLmDF3j2ADM:-L8HWIzviLLmDF3j2ADN:b-uwlopt) ([raw file](https://github.com/sillsdev/libpalaso/blob/de6b5e98404415f086e54314e31b3fd746c7426c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L300)):*
> ```Smalltalk
> 
> 			// TSF disabled, so we have to fall back to Windows messages
> 			_tfLanguageProfileNotifySink.RegisterWindowsMessageHandler(e.Control);
> ```

We no longer support TSF being disabled? Or we don't need that anymore?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 340 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HWWWZjj6o2eCGlqya:-L8HWWWZjj6o2eCGlqyb:bd937us) ([raw file](https://github.com/sillsdev/libpalaso/blob/de6b5e98404415f086e54314e31b3fd746c7426c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L340)):*
> ```Smalltalk
> 			}
> 
> 			Timer?.Dispose();
> ```

Wouldn't we still need a Dispose method to dispose the timer and to make sure we don't leave it running when the app exits?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 354 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HVzpy4TxImK_HIQg3:-L8HVzpy4TxImK_HIQg4:b-d02a8y) ([raw file](https://github.com/sillsdev/libpalaso/blob/de6b5e98404415f086e54314e31b3fd746c7426c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L354)):*
> ```Smalltalk
> 		/// e.g. on Windows XP.
> 		/// </summary>
> 		private class TfLanguageProfileNotifySink : ITfLanguageProfileNotifySink
> ```

I guess removing this class means we get the input method change notifications a different way now and that works reliable enough?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 35 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HXrV2qtBRIbsdHsZ9:-L8HXrV2qtBRIbsdHsZA:bzdf5ej) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L35)):*
> ```Smalltalk
> 			var curKeyboards = KeyboardController.Instance.Keyboards.OfType<WinKeyboardDescription>().ToDictionary(kd => kd.Id);
> 
> 			foreach (InputLanguage inputLanguage in InputLanguage.InstalledInputLanguages)
> ```

So, `InputLanguage.InstalledInputLanguages` returns what we need now? And also works with older Keyman versions and on older Windows versions?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 123 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HY_INtN9NTC3d8Hj_:-L8HY_IOmHvUP4wQbKfR:b-1nkcgy) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L123)):*
> ```Smalltalk
> 		}
> 
> 		private string GetKeyboardSetupApplication(out string arguments)
> ```

Inline this method?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs, line 25 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HZTzos2pK3KLsJRWw:-L8HZTzp2JodsfYXfs7L:bdrumiu) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs#L25)):*
> ```Smalltalk
> 
> 		/// <summary/>
> 		internal WinKeyboardDescription(string id, string name, string layout, string locale, bool isAvailable,
> ```

It might make sense to rename the parameters to the same names as the overload uses. Makes it easier to see the difference between the two c'tors. And I like the new parameter names better than the short ones on this c'tor :smile: 

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs, line 26 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HYm8nyfSHqaxV_08B:-L8HYm8nyfSHqaxV_08C:ba51dqu) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs#L26)):*
> ```Smalltalk
> 		/// <summary/>
> 		internal WinKeyboardDescription(string id, string name, string layout, string locale, bool isAvailable,
> 			IInputLanguage inputLanguage, WinKeyboardAdaptor engine, TfInputProcessorProfile profile)
> ```

We no longer need the localized name? It still works the same when a user with an English Windows and a user with an Non-English Windows share their writing systems? (It's quite possible that it does, or that it never really worked, just wondering why we had that parameter and why we no longer have it).

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs, line 33 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8H_6nO2pQ4540lVOcG:-L8H_6nO2pQ4540lVOcH:b-le40wp) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs#L33)):*
> ```Smalltalk
> 		}
> 
> 		internal WinKeyboardDescription(string keyboardId, string localizedKeyboardName, string inputLanguageLayoutName,
> ```

Why do we need two c'tors? Why don't we add a default value of `null` to `profile` in the first c'tor?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/669)*

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs, line 153 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HRYoo_j6AyD8sOb7D:-L8IVbA9dExskhqv9NX-:b-seltml) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs#L153)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Why do we need both methods? Can this one be made `protected`?
</blockquote></details>

We don't, it was just the quickest refactor. I'll clean up after myself now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/669)*

**Comment by jasonleenaylor** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs, line 153 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HRYoo_j6AyD8sOb7D:-L8IXA9zmQavbUYpNvB8:b-94o92p) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Linux/IbusKeyboardRetrievingAdaptor.cs#L153)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

We don't, it was just the quickest refactor. I'll clean up after myself now.
</blockquote></details>

After looking at how the linux keyboard adapters worked I decided not to remove it completely but made it protected and used it a bit differently.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HWol3uBcHusov27ft:-L8IYv2YwsF7gO8n-qpR:bdpsyfl) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L13)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

A comment might be helpful that mentions what api we now use for keyboard switching. Especially when comparing this to the previous implementation one wonders how it's done now (I no longer see the `ITfInputProcessor*` variables, so I guess it's done differently). Also, I guess we no longer support XP and therefore removed the code for that?
</blockquote></details>

Yes, I mentioned in the commit comment that we are dropping XP support.
Keyboard switching is handled by changing the CurrentInputLanguage which has a comment on line 70. 
What other kind of comment would be helpful for future developers?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 23 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8H_q6KsKcGip38YGQQ:-L8IZn2OthqpcMRW4WiJ:b-4pd5ar) ([raw file](https://github.com/sillsdev/libpalaso/blob/de6b5e98404415f086e54314e31b3fd746c7426c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L23)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

> ITfInputProcessorProfiles

I didn't check where this (and related interfaces/structs) are defined, but I wonder if it's in our code and we could get rid of some of the definitions if we no longer use them.
</blockquote></details>

I'll look them over and see if I can clean some out.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 106 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HTkvCdl1UqM79euuq:-L8IZrsUwPCmMOFrwOar:b6fcpua) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L106)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I probably don't understand why this is needed, but if a user manually switches the keyboard in a field, wouldn't we still want to save the IME status so that when he switches back he will get the same status again?
</blockquote></details>

So if a user enters a field we switch the keyboard. If they then manually change the keyboard for some reason we don't want to save the IME status for that other keyboard which is not associated with the writing system of our field.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 155 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HUnSKwlSdqU5dMx6P:-L8I_ZwORqG95DTKZynn:b-74w85n) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L155)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

We don't have to stop the timer in the else case?
</blockquote></details>

Actually we either need it in both, or not at all. I decided the responsibility for stopping the timer is outside of this Method so I've removed this extra stop call.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 163 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HUwxL5tOTFC77YBWM:-L8I_jQGi-pYNaYXhm77:b-yjbram) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L163)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

This is surprising. I'd have thought that this _is_ the primary adapter. If this is not what else is?
</blockquote></details>

Bad comment copied in during my exploratory refactoring.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 354 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HVzpy4TxImK_HIQg3:-L8IaXcIPX4FOS_5xtgu:byzg2im) ([raw file](https://github.com/sillsdev/libpalaso/blob/de6b5e98404415f086e54314e31b3fd746c7426c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L354)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I guess removing this class means we get the input method change notifications a different way now and that works reliable enough?
</blockquote></details>

I couldn't actually figure out why we needed to receive them, and if I understand it correctly starting in Windows 8.1 we don't receive them on a Form by default. A user would have to go to 'Control Panel\Clock, Language, and Region\Language\Advanced settings' and check a box to 'Let me set a different input method for each app window'

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 35 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HXrV2qtBRIbsdHsZ9:-L8IcT6shxOKEz0G_d2I:bpvhxii) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L35)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

So, `InputLanguage.InstalledInputLanguages` returns what we need now? And also works with older Keyman versions and on older Windows versions?
</blockquote></details>

Well, older Keyman versions are handled elsewhere right? We have all the information we need to switch keyboards. But I'm not sure if it returns everything we need to display a reasonable name. I haven't got the keyboard display information to match yet, this is part of the work in progress.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 123 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HY_INtN9NTC3d8Hj_:-L8IdInaCrVFaOdAZ56-:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L123)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Inline this method?
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs, line 26 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/669#-L8HYm8nyfSHqaxV_08B:-L8IdRIYETQKMmjfXN5z:b-2i7ry0) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardDescription.cs#L26)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

We no longer need the localized name? It still works the same when a user with an English Windows and a user with an Non-English Windows share their writing systems? (It's quite possible that it does, or that it never really worked, just wondering why we had that parameter and why we no longer have it).
</blockquote></details>

This is also involved in the parts I'm still tweaking.  Look for some changes here in the next patch set.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/669)*

**Comment by ermshiperete** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 13 at r1](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L8HWol3uBcHusov27ft:-L8WL4q51olMLNlYreja:b7vdjz4) ([raw file](https://github.com/sillsdev/libpalaso/blob/2ebf66db4dc6241a0c3cfb4253502b22e8dc506e/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L13)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Yes, I mentioned in the commit comment that we are dropping XP support.
Keyboard switching is handled by changing the CurrentInputLanguage which has a comment on line 70. 
What other kind of comment would be helpful for future developers?
</blockquote></details>

Ah, yes, I overlooked that in the commit comment.

What might be good to add though is that this switching adapter is also used for Keyman 10.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669)*

**Comment by ermshiperete** [comment]
Reviewed 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, line 51 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pTl557KDuSOAjoumU:-L9pTl557KDuSOAjoumV:b-7pdr) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj#L51)):*
> ```XML
>     <Optimize>false</Optimize>
>     <OutputPath>..\output\Debug</OutputPath>
>     <DefineConstants>TRACE;DEBUG;X64</DefineConstants>
> ```

It seems a little strange to define `X64` for `AnyCPU` since this could be running on a 32-bit system. It might be clearer to define `AnyCPU` or something like that, and in `MsTsInterfaces.cs` check for `X64 or AnyCPU`.

---

*[SIL.Windows.Forms.Keyboarding/Windows/MsTsfInterfaces.cs, line 11 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pV6EX01NHbApcEpDq:-L9pV6EX01NHbApcEpDr:b9itgkt) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/Windows/MsTsfInterfaces.cs#L11)):*
> ```Smalltalk
> 	#region Structs
> #if X86
> 	[StructLayout(LayoutKind.Sequential, Pack = 4)]
> ```

I wonder if we could specify `Pack = 0` which uses the default packing size for the current platform. I'd think that should give the same result and we wouldn't have to worry about AnyCPU or unknown architectures.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 16 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pVrvZ3j5lxjG0Y1yA:-L9pVrvZ3j5lxjG0Y1yB:b-7h8p5l) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L16)):*
> ```Smalltalk
> 	/// This class handles switching for normal Windows keyboards, Windows IME keyboards, and Keyman 10 keyboards
> 	/// </summary>
> 	internal class WindowsKeyboardSwitchingAdapter : IKeyboardSwitchingAdaptor
> ```

Since we have a Timer I think we still should implement `IDisposable`.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669)*

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Windows/MsTsfInterfaces.cs, line 11 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pV6EX01NHbApcEpDq:-L9pXYdf3c43dnU7wyn2:bpafdkq) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/Windows/MsTsfInterfaces.cs#L11)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I wonder if we could specify `Pack = 0` which uses the default packing size for the current platform. I'd think that should give the same result and we wouldn't have to worry about AnyCPU or unknown architectures.
</blockquote></details>

Oh, that would be awesome if it works. I didn't see that option when I was looking into this. I only knew about 1, 4, and 8

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669)*

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, line 51 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pTl557KDuSOAjoumU:-L9qJ3n1B8nNCls5YHWs:b-4ddyum) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj#L51)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It seems a little strange to define `X64` for `AnyCPU` since this could be running on a 32-bit system. It might be clearer to define `AnyCPU` or something like that, and in `MsTsInterfaces.cs` check for `X64 or AnyCPU`.
</blockquote></details>

Not sure what will happen when we build for AnyCPU so far as the struct packing goes, but using Pack = 0 seems safe enough for now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669)*

**Comment by jasonleenaylor** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj, line 51 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pTl557KDuSOAjoumU:-L9qJDyD6Ag_466qD92c:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/SIL.Windows.Forms.Keyboarding.csproj#L51)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Not sure what will happen when we build for AnyCPU so far as the struct packing goes, but using Pack = 0 seems safe enough for now.
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/MsTsfInterfaces.cs, line 11 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pV6EX01NHbApcEpDq:-L9qJ2mZA3b8iwbqJ3rm:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/Windows/MsTsfInterfaces.cs#L11)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Oh, that would be awesome if it works. I didn't see that option when I was looking into this. I only knew about 1, 4, and 8
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 340 at r1](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L8HWWWZjj6o2eCGlqya:-L9qJ0hQ8kAGYjgXGpJc:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/de6b5e98404415f086e54314e31b3fd746c7426c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L340)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Wouldn't we still need a Dispose method to dispose the timer and to make sure we don't leave it running when the app exits?
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 16 at r3](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-L9pVrvZ3j5lxjG0Y1yA:-L9qJ1UHEKK1Iw01vwUw:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/9f5af2d431229c269e49966d13b1934a83643d2c/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L16)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Since we have a Timer I think we still should implement `IDisposable`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669)*

**Comment by ermshiperete** [comment]
Thanks! :lgtm:

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/669#-:-L9sl9-m6YslEdxM0ElB:b-ftzx47)*

**Pull request merged**
