### PR TITLE
Fixed some bugs and some code cleanup

### PR DESCRIPTION
**Pull request by FoolRunning**
Fixed some bugs found in the Versification/VerseRef code
Fixed ReflectionHelper not finding members in base classes (also some code consolidation)
Removed testing resources that weren't used

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/543)

### CODE REVIEW

**Comment by FoolRunning** [comment]
win32-master build initially failed, but it passed when I re-ran it. I'm going to assume it was a fluke. :)

**Comment by jasonleenaylor** [comment]
*[SIL.Core/Reflection/ReflectionHelper.cs, line 367 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/543#-Km8XY9tscq5V-fa96xN:-Km8XY9tscq5V-fa96xO:b-11zeda) ([raw file](https://github.com/sillsdev/libpalaso/blob/af869ea9e6fb0efe5da444eeb27a1b7aa52e9eeb/SIL.Core/Reflection/ReflectionHelper.cs#L367)):*
> ```Smalltalk
> 			// Otherwise invoke on an instance method, property or field.
> 			flags |= BindingFlags.NonPublic | BindingFlags.Public |
> 					 (binding is Type ? BindingFlags.Static : BindingFlags.Instance);
> ```

| FlattenHierarchy eliminates the need for the recursion below if I'm not mistaken.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by jasonleenaylor** [comment]
*[SIL.Scripture.Tests/SIL.Scripture.Tests.csproj, line 344 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/543#-Km8YEGhxxUlBjPU69bJ:-Km8YEGhxxUlBjPU69bK:bfg8n4t) ([raw file](https://github.com/sillsdev/libpalaso/blob/bd5a293a771e42ade0b0843c5980384d18225656/SIL.Scripture.Tests/SIL.Scripture.Tests.csproj#L344)):*
> ```XML
>   </ItemGroup>
>   <ItemGroup>
>     <None Include="Resources\eng.vrs" />
> ```

removed on purpose?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by jasonleenaylor** [comment]
*[SIL.Scripture.Tests/SIL.Scripture.Tests.csproj, line 344 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/543#-Km8YEGhxxUlBjPU69bJ:-Km8YSrFW2Xi_5mWk6YZ:bpan8eb) ([raw file](https://github.com/sillsdev/libpalaso/blob/bd5a293a771e42ade0b0843c5980384d18225656/SIL.Scripture.Tests/SIL.Scripture.Tests.csproj#L344)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

removed on purpose?
</blockquote></details>

Ah, looks like a yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by jasonleenaylor** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by andrew-polk** [comment]
Reviewed 10 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by FoolRunning** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Core/Reflection/ReflectionHelper.cs, line 367 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/543#-Km8XY9tscq5V-fa96xN:-Km8YvNXtTaNCzAunpH3:b-rvxqtl) ([raw file](https://github.com/sillsdev/libpalaso/blob/af869ea9e6fb0efe5da444eeb27a1b7aa52e9eeb/SIL.Core/Reflection/ReflectionHelper.cs#L367)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

| FlattenHierarchy eliminates the need for the recursion below if I'm not mistaken.
</blockquote></details>

According to the documentation, **FlattenHierarchy** only works for static members (admittedly I didn't try it - this code was copied from Paratext's implementation).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by FoolRunning** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Core/Reflection/ReflectionHelper.cs, line 367 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/543#-Km8XY9tscq5V-fa96xN:-Km8_6e-jYZ0cXqNSjlF:b-m745ll) ([raw file](https://github.com/sillsdev/libpalaso/blob/af869ea9e6fb0efe5da444eeb27a1b7aa52e9eeb/SIL.Core/Reflection/ReflectionHelper.cs#L367)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

According to the documentation, **FlattenHierarchy** only works for static members (admittedly I didn't try it - this code was copied from Paratext's implementation).
</blockquote></details>

Yep, I just confirmed that it does not work for instance members.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by FoolRunning** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Core/Reflection/ReflectionHelper.cs, line 367 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/543#-Km8XY9tscq5V-fa96xN:-Km8_CxtjsDDjBtGNEKB:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/af869ea9e6fb0efe5da444eeb27a1b7aa52e9eeb/SIL.Core/Reflection/ReflectionHelper.cs#L367)):*
<details><summary><i>Previously, FoolRunning (Tim Steenwyk) wrote…</i></summary><blockquote>

Yep, I just confirmed that it does not work for instance members.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543)*

**Comment by jasonleenaylor** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/543#-:-Km8_zZB1MswCUJF_44C:bnfp4nl)*

**Pull request merged**
