### PR TITLE
Add tests for CombinedIbusKeyboardSwitchingAdaptor.DefaultKeyboard

### PR DESCRIPTION
**Pull request by ermshiperete**
[Review on Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/270)

### CODE REVIEW

**Comment by papeh** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, line 44 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/270#-JxfXEdXALkYqrNUp0_e)** ([raw file](https://github.com/sillsdev/libpalaso/blob/cfc24843cf1c495a85e8908a290d3add7cf8f24a/PalasoUIWindowsForms/Keyboarding/KeyboardController.cs#L44)):</sup>
It looks like this removes a member of the public API. You should make a comment on the sil-lsdev email list so other teams have a chance to review.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/270)

**Comment by papeh** [comment]
<sup>**[PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, line 44 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/270#-JxfXEdXALkYqrNUp0_e)** ([raw file](https://github.com/sillsdev/libpalaso/blob/cfc24843cf1c495a85e8908a290d3add7cf8f24a/PalasoUIWindowsForms/Keyboarding/KeyboardController.cs#L44)):</sup>
FLEx's `SIL.FieldWorks.Common.RootSites.SimpleRootSiteTests.IbusRootSiteEventHandlerTests` uses this; if this change is made, we'll need to add it to the friends list if we haven't already.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/270)

**Comment by ermshiperete** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, line 44 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/270#-JxfXEdXALkYqrNUp0_e)** ([raw file](https://github.com/sillsdev/libpalaso/blob/cfc24843cf1c495a85e8908a290d3add7cf8f24a/PalasoUIWindowsForms/Keyboarding/KeyboardController.cs#L44)):</sup>
You're right. I changed back SetKeyboardRetrievers() and Reset().

---

<sup>**[PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, line 78 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/270#-JxjEfbjJ2GFXm_urSyj)** ([raw file](https://github.com/sillsdev/libpalaso/blob/cfc24843cf1c495a85e8908a290d3add7cf8f24a/PalasoUIWindowsForms/Keyboarding/KeyboardController.cs#L78)):</sup>
I won't change the visibility of this method because it got introduced only in the previous change, so no one else should use it - and it really is an implementation detail. Tests should call SetKeyboardRetrievers() to provide alternative keyboard retrievers.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/270)

**Comment by ermshiperete** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[PalasoUIWindowsForms/Keyboarding/KeyboardController.cs, line 44 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/270#-JxfXEdXALkYqrNUp0_e)** ([raw file](https://github.com/sillsdev/libpalaso/blob/cfc24843cf1c495a85e8908a290d3add7cf8f24a/PalasoUIWindowsForms/Keyboarding/KeyboardController.cs#L44)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/270)

**Comment by jasonleenaylor** [comment]
Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/270)

**Comment by jasonleenaylor** [comment]
LGTM

**Pull request merged**
