### PR TITLE
[API] Mark XmlUtils.AppendAttribute as obsolete

### PR DESCRIPTION
**Pull request by ermshiperete**
The preferred way is to use `SetAttribute` which deals with both
setting an attribute and replacing an existing one.

`AppendAttribute` always appended the attribute to the end of
the collection (and the collection removed an already existing one
with the same name). `SetAttribute` will keep an existing attribute
and just change its value, thus keeping the order of attributes.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/550)

### CODE REVIEW

**Comment by papeh** [comment]
👍

**Comment by gtryus** [comment]
It would be good to inform those responsible for code bases that use AppendAttribute that you are making it obsolete.

**Comment by ermshiperete** [comment]
Email announcing the upcoming change sent to the `sil-lsdev` group.

**Comment by ermshiperete** [comment]
Good point. Updated version to 4.1.

**Pull request merged**
