### PR TITLE
remove macrolanguages using a manual list

### PR DESCRIPTION
**Pull request by glasseyes**
they cause crashes in WeSay WS-238, WS-260

update TwoToThreeCodes.txt to the version in libpalaso-3.1

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/590)

### CODE REVIEW

**Comment by megahirt** [comment]
I cannot say approve/disapprove to these changes because there's several changes here and I'm not entirely sure which changes are just updates from the 3.1 branch and which are made in addition to that.  I approve by default any changes that are already in the 3.1 branch.  Can this PR be separated into "3.1 branch merge" and "additional fixes"?  Ethnologue code changes are dicey :)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-:-KzakxvV5GygbSbhy3Dr:bem8md)*

**Comment by glasseyes** [comment]
The only thing from libpalaso-3.1 is TwoToThreeCodes.txt. Everything else is specific to libpalaso-2.6 which doesn't have the LanguageData changes that are in libpalaso-3.1 and master - and they rely on TwoToThreeCodes.txt having the correct codes for Chinese, Arabic and Farsi macrolanguages

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-:-KzbTxjV_r8reFZOh7wJ:b-43kpmp)*

**Comment by megahirt** [comment]
OK, so basically reimplementing LanguageData changes in libpalaso-2.6 but there's nothing really "new" here, as best as I can tell

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-:-KzbvbXOD_XUgcnV5pUQ:b77oovq)*

**Comment by glasseyes** [comment]
it is reimplementing one LanguageData change in a different way

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-:-Kzc9mMLPPPRxfiISEFX:b-80hza6)*

**Comment by ddaspit** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[Palaso/Resources/TwoToThreeCodes.txt, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-KzvXaTjxu12mO3ukSkX:-KzvXaTjxu12mO3ukSkY:b-e6wqgc) ([raw file](https://github.com/sillsdev/libpalaso/blob/c6ebc95c37f70d4aee959ef6ff23945ed02b2181/Palaso/Resources/TwoToThreeCodes.txt#L6)):*
> ```
> ak	aka
> am	amh
> ar	ara
> ```

So this file was updated to the same one that is used in libpalaso 3.1?

---

*[Palaso/WritingSystems/EthnologueLookup.cs, line 117 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-KzvXd8dTXkpSKbFOuTy:-KzvXd8dTXkpSKbFOuTz:b-shswri) ([raw file](https://github.com/sillsdev/libpalaso/blob/c6ebc95c37f70d4aee959ef6ff23945ed02b2181/Palaso/WritingSystems/EthnologueLookup.cs#L117)):*
> ```Smalltalk
> 			get
> 			{
> 				if (_macroLanguages.Count == 0)
> ```

There is a Lazy class that can be used to lazy load this list. This data could also be included as a text file that is an embedded resource. That way the list isn't hard-coded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590)*

**Comment by glasseyes** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[Palaso/Resources/TwoToThreeCodes.txt, line 6 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-KzvXaTjxu12mO3ukSkX:-L-0TR4jgS3e2Ee8XvqR:b2nhswy) ([raw file](https://github.com/sillsdev/libpalaso/blob/c6ebc95c37f70d4aee959ef6ff23945ed02b2181/Palaso/Resources/TwoToThreeCodes.txt#L6)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

So this file was updated to the same one that is used in libpalaso 3.1?
</blockquote></details>

Yes

---

*[Palaso/WritingSystems/EthnologueLookup.cs, line 117 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-KzvXd8dTXkpSKbFOuTy:-L-56o7V6wi4a8dk34Yn:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c6ebc95c37f70d4aee959ef6ff23945ed02b2181/Palaso/WritingSystems/EthnologueLookup.cs#L117)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary><blockquote>

There is a Lazy class that can be used to lazy load this list. This data could also be included as a text file that is an embedded resource. That way the list isn't hard-coded.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590)*

**Comment by glasseyes** [comment]
Review status: 3 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[Palaso/WritingSystems/EthnologueLookup.cs, line 117 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-KzvXd8dTXkpSKbFOuTy:-L-56sO7lRa46W3ouJm_:bcgba2s) ([raw file](https://github.com/sillsdev/libpalaso/blob/c6ebc95c37f70d4aee959ef6ff23945ed02b2181/Palaso/WritingSystems/EthnologueLookup.cs#L117)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ie as text file embedded resource

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590)*

**Comment by ddaspit** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/590#-:-L-6ArOOEwihjylrpnZn:bnfp4nl)*

**Pull request merged**
