### PR TITLE
Fix some problems on Linux with failing tests

### PR DESCRIPTION
**Pull request by StephenMcConnel**
These are mostly related to the new FileLock code.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/397)

### CODE REVIEW

**Comment by ddaspit** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Core.Tests/IO/FileLock/SimpleFileLockTests.cs, line 165 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/397#-KUFUQf-TLFhHcLG-2Hx:-KUFUQf0Uvsz4ScjF6AJ:b-av6j0q) ([raw file](https://github.com/sillsdev/libpalaso/blob/050cec55adfcebd232091bdce84cb725b74c1b48/SIL.Core.Tests/IO/FileLock/SimpleFileLockTests.cs#L165)):*
> ```Smalltalk
> 		private string GetSafeActiveProcessName()
> 		{
> 			return Platform.IsLinux ? "init" : Process.GetProcessById(ActiveProcessId).ProcessName;
> ```

Shouldn't this also check if the process Id is 1?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/397)*

**Comment by StephenMcConnel** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Core.Tests/IO/FileLock/SimpleFileLockTests.cs, line 165 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/397#-KUFUQf-TLFhHcLG-2Hx:-KUNZKL_qZ2Dnr3s5NXS:b-sdzbw) ([raw file](https://github.com/sillsdev/libpalaso/blob/050cec55adfcebd232091bdce84cb725b74c1b48/SIL.Core.Tests/IO/FileLock/SimpleFileLockTests.cs#L165)):*
<details><summary><i>Previously, ddaspit (Damien Daspit) wrote…</i></summary>
> Shouldn't this also check if the process Id is 1?
</details>
Done.  oops.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/397)*

**Comment by ddaspit** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/397#-:-KUQgKzFHsnMUp1fUqRz:bnfp4nl)*

**Comment by andrew-polk** [comment]
Pre-builds indicate compile failure.

**Comment by StephenMcConnel** [comment]
My original fix was bad (and probably unneeded after looking at the whole file and thinking about it).  But I've made a second fix that works okay.

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/397#-:-KUcnZABLTT5jBQ9sSHj:bnfp4nl)*

**Pull request merged**
