### PR TITLE
Libpalaso 2.6 remove pejorative languages

### PR DESCRIPTION
**Pull request by glasseyes**
this applies JH's changes adapted for the libpalaso-2.6 branch

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/451)

### CODE REVIEW

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/451#-:-Kbt-feThjgPE63OSjUx:bnfp4nl)*

**Comment by megahirt** [comment]
The tests are all correct.  I suggested more explicit ways of stating them FWIW.  :lgtm: 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Palaso.Tests/WritingSystems/EthnologueLookupTests.cs, line 168 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/451#-KcawJr9_wYIbIX0TpQi:-KcawJr9_wYIbIX0TpQj:b-fgpjfc) ([raw file](https://github.com/sillsdev/libpalaso/blob/972b8ac2ed212e2de4e65dc61397195842746516/Palaso.Tests/WritingSystems/EthnologueLookupTests.cs#L168)):*
> Assert.True(languages.Any(l => l.Names.Contains("Deg Xit'an")));

Just to be complete, the test probably ought to have Assert.False(languages.Any(l => l.Names.Contains("pejorative name here"))); for each of the excluded names

---

*[Palaso.Tests/WritingSystems/EthnologueLookupTests.cs, line 192 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/451#-Kcax-i7IF0mBqnMEUna:-Kcax-i7IF0mBqnMEUnb:buz4oc2) ([raw file](https://github.com/sillsdev/libpalaso/blob/972b8ac2ed212e2de4e65dc61397195842746516/Palaso.Tests/WritingSystems/EthnologueLookupTests.cs#L192)):*
> Assert.True(languages.All(l => l.Code.StartsWith("om")), "We should be suppressing gax, hae, gaz");
Another way to more explicitly state the assertions:
Assert.False(languages.Any(l => l.Code.Equals("gax")), "suppress gax code");
Assert.False(languages.Any(l => l.Code.Equals("hae")), "suppress hae code");
Assert.False(languages.Any(l => l.Code.Equals("gaz")), "suppress gaz code");

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/451#-:-KcaxlPO9DjXcW1pYukL:b-j6xi6l)*

**Comment by megahirt** [comment]
:lgtm: thanks Daniel!

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/451#-:-KcbGzRJBgOKh0jmngeY:bfultzu)*

**Comment by megahirt** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/451)*

**Comment by glasseyes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Palaso.Tests/WritingSystems/EthnologueLookupTests.cs, line 168 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/451#-KcawJr9_wYIbIX0TpQi:-KcbJyzSBIjMbYsY3J3A:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/972b8ac2ed212e2de4e65dc61397195842746516/Palaso.Tests/WritingSystems/EthnologueLookupTests.cs#L168)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

> Assert.True(languages.Any(l => l.Names.Contains("Deg Xit'an")));

Just to be complete, the test probably ought to have Assert.False(languages.Any(l => l.Names.Contains("pejorative name here"))); for each of the excluded names
</blockquote></details>

Done.

---

*[Palaso.Tests/WritingSystems/EthnologueLookupTests.cs, line 192 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/451#-Kcax-i7IF0mBqnMEUna:-KcbJxnxIQDCz06n8y9w:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/972b8ac2ed212e2de4e65dc61397195842746516/Palaso.Tests/WritingSystems/EthnologueLookupTests.cs#L192)):*
<details><summary><i>Previously, megahirt (Chris Hirt) wrote…</i></summary><blockquote>

> Assert.True(languages.All(l => l.Code.StartsWith("om")), "We should be suppressing gax, hae, gaz");
Another way to more explicitly state the assertions:
Assert.False(languages.Any(l => l.Code.Equals("gax")), "suppress gax code");
Assert.False(languages.Any(l => l.Code.Equals("hae")), "suppress hae code");
Assert.False(languages.Any(l => l.Code.Equals("gaz")), "suppress gaz code");

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/451)*

**Pull request merged**
