### PR TITLE
BL-4030 Make RobustFile use WriteThrough

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/467)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Causes test failures on the TC Linux builds of the PR.

A few comments. Overall looks good, but I wouldn't mind someone else taking a look since it is such a critical change for us.

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 12 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenwHS3oyydS2qoKmkW:-KenwHS3oyydS2qoKmkX:b-h0vj0t) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core.Tests/IO/RobustFileTests.cs#L12)):*
> ```Smalltalk
> {
> 	[TestFixture]
> 	public class RobustFileTests
> ```

Worth having some tests for which the data written is larger than the buffer?

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 15 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Kense0uUbUwFzpuGDpy:-Kense0uUbUwFzpuGDpz:b287743) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core.Tests/IO/RobustFileTests.cs#L15)):*
> [Test]

You actually don't need the Test attribute if you have TestCase attributes.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 144 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Kentm7omL4pEafNMAVW:-Kentm7omL4pEafNMAVX:bhvs7hc) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core.Tests/IO/RobustFileTests.cs#L144)):*
> ```Smalltalk
> 					RobustFile.Copy(temp.Path, output.Path);
> 					Assert.That(File.ReadAllText(output.Path), Is.EqualTo("This is a test"));
> 					Assert.Throws<IOException>(() => RobustFile.Copy(temp.Path, output.Path));
> ```

Presumably this is failing because the target file exists?
Could use a comment.

---

*[SIL.Core/IO/RobustFile.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Kenv3fI8F--a39QZOks:-Kenv3fI8F--a39QZOkt:bb7nug1) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L13)):*
> ///·

Not really a big deal, but your editor oddly added trailing spaces on several of these comment lines.

---

*[SIL.Core/IO/RobustFile.cs, line 51 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenvxjGVUQbd3mY07UP:-KenvxjIPxBdm5wFoy_2:bkasaye) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L51)):*
> FileShare.None

Do we need to do anything to try to preserve the setting from the source file?

---

*[SIL.Core/IO/RobustFile.cs, line 83 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenwmoE2a_pXzohCNA2:-KenwmoE2a_pXzohCNA3:byfqwts) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L83)):*
> 4096

Should we go ahead and create our own constant which represents .Net's since this is used in more than one place?

---

*[SIL.Core/IO/RobustFile.cs, line 201 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenxcBYH42moH-MJW8m:-KenxcBYH42moH-MJW8n:b-l6r2l9) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L201)):*
> ```Smalltalk
> 		{
> 			// I haven't tried to make this WriteThrough; not sure how to do that while keeping all the
> 			// clever properties Replace has.
> ```

Any evaluation of where this is used in Bloom to make sure we aren't exposing ourselves on any critical operations?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-:-KenuFt1zu_7uHgJ7kGY:bnkzauh)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 12 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenwHS3oyydS2qoKmkW:-KeoYWbdZWvb0bxtiKZW:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core.Tests/IO/RobustFileTests.cs#L12)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Worth having some tests for which the data written is larger than the buffer?
</blockquote></details>

Done.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 15 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Kense0uUbUwFzpuGDpy:-KeoYdA2G8Prprs9MEpd:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core.Tests/IO/RobustFileTests.cs#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> [Test]

You actually don't need the Test attribute if you have TestCase attributes.
</blockquote></details>

Done.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 144 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Kentm7omL4pEafNMAVW:-KeoYg0iUJx9c3tA5e50:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core.Tests/IO/RobustFileTests.cs#L144)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Presumably this is failing because the target file exists?
Could use a comment.
</blockquote></details>

Done.

---

*[SIL.Core/IO/RobustFile.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Kenv3fI8F--a39QZOks:-KeoZiyNeu5wJUKVTKiC:b-937wva) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ///·

Not really a big deal, but your editor oddly added trailing spaces on several of these comment lines.
</blockquote></details>

Lots of trailing space in the file already. I've tried to fix where I added it, at least.

---

*[SIL.Core/IO/RobustFile.cs, line 51 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenvxjGVUQbd3mY07UP:-KeoZHT9Z3KFD0eusisJ:b-om2e39) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> FileShare.None

Do we need to do anything to try to preserve the setting from the source file?
</blockquote></details>

This doesn't govern long-term sharing of the file (e.g., with other users). It just says, no other process can read or write this file until I get done creating it. At least that's my read.

---

*[SIL.Core/IO/RobustFile.cs, line 83 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenwmoE2a_pXzohCNA2:-Keo_dMkVnn_bHl-R7cT:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L83)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> 4096

Should we go ahead and create our own constant which represents .Net's since this is used in more than one place?
</blockquote></details>

Done.

---

*[SIL.Core/IO/RobustFile.cs, line 201 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KenxcBYH42moH-MJW8m:-Keo_otmE3B8Rcktk2aN:bsvek2g) ([raw file](https://github.com/sillsdev/libpalaso/blob/c0eb8d383bd5b003843f4d47fe2b06b9974e6ba7/SIL.Core/IO/RobustFile.cs#L201)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Any evaluation of where this is used in Bloom to make sure we aren't exposing ourselves on any critical operations?
</blockquote></details>

Not currently used anywhere. After the changes I'm making in 3.8, it will be used when writing out json. But I really don't know how to improve it. I can't find a write-through version of either this or even of a simple Move. Could implement using copy, but that might actually increase the chances of leaving the file in an incomplete state during write.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Comment by andrew-polk** [comment]
:lgtm: other than the failing tests on Linux.
As I said above, it may be worth another pair of eyes.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-:-Keod9TOkSB3Ve7fSJRk:b-wg09nd)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 51 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KeoqtOhGZmBOztUHcEs:-KeoqtOhGZmBOztUHcEt:b32hz2j) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L51)):*
> ```Smalltalk
> 				result = File.ReadAllBytes(temp.Path);
> 			}
> 			if (text == "")
> ```

Now that we have to have this condition, I wonder if it would be better to split out TestCase("") to a separate test. But then you would have to duplicate the code in the first part of the test. 
Anyway, that is an optional suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Comment by ermshiperete** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 54 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Ker1LE1NeqQlUgFCnHG:-Ker1LE1NeqQlUgFCnHH:b-ntmosw) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L54)):*
> ```Smalltalk
> 			{
> 				// Linux behaves unexpectedly as of Mono 3.4 and omits the preamble for empty strings.
> 				Assert.That(result, Is.EqualTo(Encoding.UTF8.GetPreamble()));
> ```

I think it would be cleaner to check for the empty string in the first using() statement and set `correct` to the preamble.  I had a hard time understanding the comment because it looked backwards at first. But this could also be caused by the early morning... :smile:  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Comment by jasonleenaylor** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 15 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesP-CdZ6clU7a13rvA:-KesP-CeiwN0jvrZWj5y:b-7lz9zh) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L15)):*
> ```Smalltalk
> 	{
> 		[TestCase("abc")]
> 		[TestCase("")]
> ```

null?

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 138 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesPOYs9utC6RDyM0KD:-KesPOYs9utC6RDyM0KE:bj55v5b) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L138)):*
> ```Smalltalk
> 		}
> 
> 		private static void WriteTestDataToStream(Stream writer)
> ```

This method seems to generate some pretty specific test data. Should the name reflect it?

---

*[SIL.Core/IO/RobustFile.cs, line 73 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesQ9GKmm2796viXUvO:-KesQ9GKmm2796viXUvP:b-7ffr5t) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core/IO/RobustFile.cs#L73)):*
> ```Smalltalk
> 		// Creates a stream that will write to disk on every write.
> 		// For most purposes (except perhaps logging when crashes are likely),
> 		// calling Flush(true) on the stream when finished would probaby suffice.
> ```

Any reason that this comment isn't a ///<summary> ?

---

*[SIL.Core/IO/RobustFile.cs, line 237 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesREpYGQQAzGsMQMvq:-KesREpZINlC3p-dnM94:bc2h4dd) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core/IO/RobustFile.cs#L237)):*
> ```Smalltalk
> 		/// using UTF8.
> 		/// On Windows, the BOM is inserted even if contents is an empty string.
> 		/// As of Mono 3.4, Linux instead writes an empty file. We think this is a bug.
> ```

I would recommend, as someone else has, that the special behavior to insert the BOM on mono gets a separate unit test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Comment by JohnThomson** [comment]
Review status: 1 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 15 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesP-CdZ6clU7a13rvA:-KeszTXfoW1TN5UMCnsg:b-dtvq2z) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L15)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

null?
</blockquote></details>

Done. (And good suggestion, it discovered some problems.)

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 51 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KeoqtOhGZmBOztUHcEs:-Ket3SRyBk1wCiTbqLbY:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L51)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Now that we have to have this condition, I wonder if it would be better to split out TestCase("") to a separate test. But then you would have to duplicate the code in the first part of the test. 
Anyway, that is an optional suggestion.
</blockquote></details>

Done.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 54 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Ker1LE1NeqQlUgFCnHG:-KeszXOljHpRDvdfNpWo:b-dh27gx) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L54)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I think it would be cleaner to check for the empty string in the first using() statement and set `correct` to the preamble.  I had a hard time understanding the comment because it looked backwards at first. But this could also be caused by the early morning... :smile:  
</blockquote></details>

Two others suggested a separate test, so I decided to do it that way.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 138 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesPOYs9utC6RDyM0KD:-KeszsHmcQM1JfwzqOME:b-ujeq0f) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L138)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

This method seems to generate some pretty specific test data. Should the name reflect it?
</blockquote></details>

I don't think so. There was no particular purpose in the data I chose so I can't think what better to call the method.

---

*[SIL.Core/IO/RobustFile.cs, line 73 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesQ9GKmm2796viXUvO:-Ket-hsIrGyM_ZkaeAn4:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core/IO/RobustFile.cs#L73)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Any reason that this comment isn't a ///<summary> ?
</blockquote></details>

Done.

---

*[SIL.Core/IO/RobustFile.cs, line 237 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesREpYGQQAzGsMQMvq:-Ket0wBOi2BHOycC2Mq2:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core/IO/RobustFile.cs#L237)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I would recommend, as someone else has, that the special behavior to insert the BOM on mono gets a separate unit test.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Comment by jasonleenaylor** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-:-Ketzy5ZAeGEWIvnYwia:bnfp4nl)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 15 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesP-CdZ6clU7a13rvA:-Kf6nDCCORXDKC8_ZM3X:b-h6td7o) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Done. (And good suggestion, it discovered some problems.)
</blockquote></details>

You say done, but I don't see it. Is this another case of Reviewable not showing me the latest...?

---

*[SIL.Core/IO/RobustFile.cs, line 252 at r4](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-Kf6n24VL6GSRRVtTyTU:-Kf6n24VL6GSRRVtTyTV:b-h74w62) ([raw file](https://github.com/sillsdev/libpalaso/blob/da907ff51055635efbf70a34968549f0164dee40/SIL.Core/IO/RobustFile.cs#L252)):*
> actaully

actually
Not worth another commit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Comment by JohnThomson** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 15 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesP-CdZ6clU7a13rvA:-Kf6r-RKkp8Keoa4gVQl:b-49hac1) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L15)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

You say done, but I don't see it. Is this another case of Reviewable not showing me the latest...?
</blockquote></details>

Null throws an exception, so it doesn't belong as a TestCase in this test. See WriteAllTextExceptions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[SIL.Core.Tests/IO/RobustFileTests.cs, line 15 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/467#-KesP-CdZ6clU7a13rvA:-Kf7MIDfk4cblybhq0Pz:b-jhyysx) ([raw file](https://github.com/sillsdev/libpalaso/blob/dbba760e4849a9774895306d1d732a041692ea80/SIL.Core.Tests/IO/RobustFileTests.cs#L15)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Null throws an exception, so it doesn't belong as a TestCase in this test. See WriteAllTextExceptions.
</blockquote></details>

Got it. Thanks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/467)*

**Pull request merged**
