### PR TITLE
get more things from nuget (master branch)

### PR DESCRIPTION
**Pull request by glasseyes**
get NAudio, Commons.Xml.RelaxNG, Moq, Rhino.Mocks from nuget
all closest versions to what is currently in the repo

upgrade Commons.Xml.RelaxNG to 3.2.3 from 2.0.0
upgrade Rhino.Mocks to 3.6.1 from 3.5
upgrade Moq from 4.0.812 to 4.0.10827
upgrade icu.net to 2.2.0
don't include dbus or ibus project targets in windows builds nor icu dlls in linux builds

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/585)

### CODE REVIEW

**Comment by papeh** [comment]
A few dependencies have been added and removed apart from simply switching to NuGet. Assuming this is intentional, :LGTM:

---

Reviewed 43 of 43 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Core/SIL.Core.csproj, line 576 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KxryjUr60hECYScOZSu:-KxryjUr60hECYScOZSv:b5genri) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Core/SIL.Core.csproj#L576)):*
> ```XML
>   <ItemGroup />
>   <Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />
>   <Import Project="..\packages\NDesk.DBus.0.15.0\build\NDesk.DBus.targets" Condition="Exists('..\packages\NDesk.DBus.0.15.0\build\NDesk.DBus.targets') And ('$(Configuration)' == 'DebugMono' Or '$(Configuration)' == 'DebugMonoStrongName' Or '$(Configuration)' == 'ReleaseMono' Or '$(Configuration)' == 'ReleaseMonoStrongName')" />
> ```

`$(Configuration.Contains('Mono'))`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-:-KxsJQoBV0gK7GpkHH4q:b-aa01ja)*

**Comment by ermshiperete** [comment]
:lgtm_cancel:  a few minor issues...

---

Reviewed 43 of 43 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[LanguageData/packages.config, line 5 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFlh9gjCkkpqkEI2Ez:-KyFlh9gjCkkpqkEI2F-:b-ynglv9) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/LanguageData/packages.config#L5)):*
> ```XML
>   <package id="CommandLineParser" version="1.9.71" targetFramework="net40" requireReinstallation="True" />
>   <package id="Newtonsoft.Json" version="7.0.1" targetFramework="net40"  requireReinstallation="True" />
> </packages>
> ```

Don't we need a corresponding change in the .csproj file?

---

*[SIL.Lift/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFkPQfkY7XmkwH-KDP:-KyFkPQfkY7XmkwH-KDQ:b-211gg2) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Lift/packages.config#L4)):*
> ```XML
> <packages>
>   <package id="RelaxNG" version="3.2.3" /> 
> </packages>
> ```

It would be good to add this file to the .csproj file.

---

*[SIL.Lift.Tests/SIL.Lift.Tests.csproj, line 253 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFirJ4g7yeITA3PFrh:-KyFirJ53Qwoz4mQGBn0:b-w1x4zo) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Lift.Tests/SIL.Lift.Tests.csproj#L253)):*
> ```XML
>   </PropertyGroup>
>   <ItemGroup>
>     <Reference Include="Moq"> 
> ```

Nit: trailing space

---

*[SIL.Lift.Tests/SIL.Lift.Tests.csproj, line 254 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFiuHEIML4HzOSBtfU:-KyFiuHEIML4HzOSBtfV:bb7eybp) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Lift.Tests/SIL.Lift.Tests.csproj#L254)):*
> ```XML
>   <ItemGroup>
>     <Reference Include="Moq"> 
>       <HintPath>..\packages\Moq.4.0.10827\lib\NET40\Moq.dll</HintPath> 
> ```

dito

---

*[SIL.Media/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFjZCPwibu_SDRwesI:-KyFjZCPwibu_SDRwesJ:b-211gg2) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Media/packages.config#L4)):*
> ```XML
> <packages>
>   <package id="NAudio" version="1.8.3" />
> </packages>
> ```

It would be good to add this file to the .csproj file.

---

*[SIL.Media/SIL.Media.csproj, line 303 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFj8OOXEzaFv8Yhjnt:-KyFj8OOXEzaFv8Yhjnu:bwwk4b9) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Media/SIL.Media.csproj#L303)):*
> ```XML
>   <ItemGroup Condition="$(Configuration.StartsWith('Debug'))">
>     <Reference Include="NAudio">
>       <HintPath>..\packages\NAudio.1.8.3\lib\NAudio.dll</HintPath>
> ```

It would be better to move this reference to the non-conditional ItemGroup below - I think that will work better in case the package gets updated to a newer version inside VS in the future.

---

*[SIL.Windows.Forms/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFlHIn7tbdM_Mf2B0e:-KyFlHIn7tbdM_Mf2B0f:bc9a1hv) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Windows.Forms/packages.config#L4)):*
> ```XML
> <packages>
>   <package id="MarkdownDeep.NET" version="1.5" targetFramework="net40" />
>   <package id="NAudio" version="1.8.3" />
> ```

It seems we'd need a corresponding change in the .csproj file

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-:-KyFm1af7JRQTHG0yZvA:b-95le0)*

**Comment by glasseyes** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[LanguageData/packages.config, line 5 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFlh9gjCkkpqkEI2Ez:-L-AFwc5NYf7jjYxpZH5:b-2ugzdl) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/LanguageData/packages.config#L5)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Don't we need a corresponding change in the .csproj file?
</blockquote></details>

it is already in the csproj, it was missing from the packages.config

---

*[SIL.Core/SIL.Core.csproj, line 576 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KxryjUr60hECYScOZSu:-L-AX2_icJWEAiKz_g_3:b-oh7wt) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Core/SIL.Core.csproj#L576)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

`$(Configuration.Contains('Mono'))`?
</blockquote></details>

Done, good catch

---

*[SIL.Lift/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFkPQfkY7XmkwH-KDP:-L07oq83G0qJnTtUyoX6:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Lift/packages.config#L4)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It would be good to add this file to the .csproj file.
</blockquote></details>

Done.

---

*[SIL.Lift.Tests/SIL.Lift.Tests.csproj, line 253 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFirJ4g7yeITA3PFrh:-L-AXY1BIHpCwgVDjwGU:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Lift.Tests/SIL.Lift.Tests.csproj#L253)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Nit: trailing space
</blockquote></details>

Done.

---

*[SIL.Lift.Tests/SIL.Lift.Tests.csproj, line 254 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFiuHEIML4HzOSBtfU:-L-AXYTo3t76-SLihcg-:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Lift.Tests/SIL.Lift.Tests.csproj#L254)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

dito
</blockquote></details>

Done.

---

*[SIL.Media/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFjZCPwibu_SDRwesI:-L07p6RQZ2Z-5XRM4-ai:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Media/packages.config#L4)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It would be good to add this file to the .csproj file.
</blockquote></details>

Done.

---

*[SIL.Media/SIL.Media.csproj, line 303 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFj8OOXEzaFv8Yhjnt:-L07pxyqw9cRV7sIhEmv:b-gh1rtw) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Media/SIL.Media.csproj#L303)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It would be better to move this reference to the non-conditional ItemGroup below - I think that will work better in case the package gets updated to a newer version inside VS in the future.
</blockquote></details>

This reference looks wrong - NAudio isn't used on mono, fixed

---

*[SIL.Windows.Forms/packages.config, line 4 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-KyFlHIn7tbdM_Mf2B0e:-L07qOsvIjlOYPO7dzgi:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3ee1c8dc1442267b6359a0870e4333b1aeae857b/SIL.Windows.Forms/packages.config#L4)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It seems we'd need a corresponding change in the .csproj file
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/585)*

**Comment by papeh** [comment]
Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/585)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/585#-:-L2KO5rtZR3xdp7jhcZ6:bnfp4nl)*

**Pull request merged**
