### PR TITLE
Various cleanup

### PR DESCRIPTION
**Pull request by ermshiperete**
- Update copyright information for keyboarding code
- Cleanup KeyboardController interface
- update version numbers (see commit message for reasons)

### CODE REVIEW

**Comment by regnrand** [comment]
Palaso and Chorus don't put the version number in those AssemblyInfo files. It is done elsewhere and all assemblies are then stamped with the version number. See:

palaso\build\build.common.proj

For details.

So, while your version number changes do no harm, neither do they do any good.

**Comment by ermshiperete** [comment]
It depends on how you build. If you compile in VS/MD the version numbers from AssemblyInfo get used without being updated. That's the case I'm trying to fix here.

For the official builds (i.e. TC) and for building from the command line I agree that this doesn't make any difference.

**Comment by regnrand** [comment]
Ok

**Comment by chrisvire** [comment]
:+1:

**Pull request merged**
