### PR TITLE
Udisks2

### PR DESCRIPTION
**Pull request by marksvc**
I wasn't able to test an aspect of this so I am hoping to test it more now that I am sharing the code (namely that the list of drives reported is only USB flash drives). Also, I'm not confident that the 3rd commit about closing the NDesk bus when the process exits is working but I have found it not to be easy to test these things.

[Review on Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/338)

### CODE REVIEW

**Comment by ermshiperete** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[Palaso/PalasoSetup.cs, line 15 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7QHJz0Ud2b1kHdA26o:-K7QH9vScCloIt9pvJ5n:-162310041) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/PalasoSetup.cs#L15)):*
Typo: /origiinally/originally/

---

*[Palaso/PalasoSetup.cs, line 17 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VGn48As_gbaGclxvB:-K7VGn49sFkJ1ilvGTEl:-582775606) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/PalasoSetup.cs#L17)):*
I'm hesitant in leaving an empty class around just in case, but on the other hand removing it would require code changes in all clients, so it's better to leave it in.

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 20 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VHmB0ft2XKlEcmR7l:-K7VHmB0ft2XKlEcmR7m:65231291) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L20)):*
Why redeclare this interface instead of using `org.freedesktop.DBus.IBus.ListActivatableNames()` ?

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 77 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VIUkNTxf7iTP6JzHK:-K7VIUkNTxf7iTP6JzHL:592297337) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L77)):*
Are we sure we always get a value for "org.freedesktop.UDisks2.Block" and "IdLabel"?

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 138 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VJ1TOHkuY9rlAEmZA:-K7VJ1TOHkuY9rlAEmZB:997389172) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L138)):*
Will the value we get always be in lowercase, or do we have to compare case-insensitive?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/338)*

**Comment by ermshiperete** [comment]
A few remarks.

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 1 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VKjlAdHcuYPiFLNtm:-K7VKjlAdHcuYPiFLNtn:294829695) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L1)):*
File should be surrounded by `#if __MonoCS__` so that it doesn't try to compile on Windows.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-:-K7VL1DRJgZxkdrpYDKw:-1324533017)*

**Comment by ermshiperete** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs, line 172 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K8PfTZEDZmIYPJklcJZ:-K8PfTZEDZmIYPJklcJ_:540642917) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs#L172)):*
The drive might not have a label set, so we shouldn't check VolumeLabel.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/338)*

**Comment by marksvc** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs, line 172 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K8PfTZEDZmIYPJklcJZ:-K8Q7EqZsaAJ_rmuMwyp:284911213) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs#L172)):*
Do you think that's important? This unit test is very excluded by Categories, and also I think all USB drives I have purchased have had labels. I can take this out though if you think that's important.

---

*[Palaso/PalasoSetup.cs, line 15 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7QHJz0Ud2b1kHdA26o:-K8QD7v8jVR9qwzWHz5-:-499146009) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/PalasoSetup.cs#L15)):*
Done.

---

*[Palaso/PalasoSetup.cs, line 17 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VGn48As_gbaGclxvB:-K8QD9kWbo0N_zfQy4eV:-1425289697) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/PalasoSetup.cs#L17)):*
BTW, I recall that in a brief look it wasn't clear that other projects were using this. But it is indeed safer to leave it.

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 1 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VKjlAdHcuYPiFLNtm:-K8QDIWjcL61vrejZ3VR:-1639351726) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L1)):*
Thank you. I am moving this file into a different group in Palaso.csproj so that it only compiles on Linux, and in conformance with the way the other Linux USB Drive files are excluded on Windows (which is in a different section of the csproj).

The other Linux USB Drive files aren't using #if __MonoCS__, but I could take that additional step if you think that's important.

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 20 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VHmB0ft2XKlEcmR7l:-K8QUKM3-w7dVwja23Ct:-1303327134) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L20)):*
Thank you. Still learning.

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 77 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VIUkNTxf7iTP6JzHK:-K8QUwtvF9u6cTj11ei3:1134185192) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L77)):*
So http://udisks.freedesktop.org/docs/latest/gdbus-org.freedesktop.UDisks2.Block.html says that IdLabel will at least be blank.

GetUsbBlockDevices filters the list of objects by ones which have the org.freedesktop.UDisks2.Block key, and even works with the value from that key later in the method, so I would assume that BlockDevice.Value["org.freedesktop.UDisks2.Block"] should always return something.

As for whether BlockDevice would never be null, I suppose that if a UsbDriveInfoUDisks2 was generated, and then the corresponding USB drive was removed, then BlockDevice would probably return null for this stale UsbDriveInfoUDisks2 object, and calling BlockDevice.Value would probably crash.

---

*[Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs, line 138 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K7VJ1TOHkuY9rlAEmZA:-K8QdI374QmJ2Ptvl_79:1472502636) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso/UsbDrive/Linux/UsbDriveInfoUDisks2.cs#L138)):*
According to http://udisks.freedesktop.org/docs/latest/gdbus-org.freedesktop.UDisks2.Drive.html#gdbus-property-org-freedesktop-UDisks2-Drive.ConnectionBus , it should be "usb". So I assume it will be lower-case in compliant implementations.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/338)*

**Comment by ermshiperete** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs, line 172 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K8PfTZEDZmIYPJklcJZ:-K8SuFrFAAmRPvpRgCqS:1609406286) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs#L172)):*
Mine didn't have a label...

Yes, the tests are excluded by category, but when you run the tests in MD/VS you'll get failing tests because the categories don't get excluded automatically.

But I'm ok with how it is.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-:-K8Sv24qxUjSKffDTcHx:980077423)*

**Comment by marksvc** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs, line 172 \[r1\]](https://reviewable.io:443/reviews/sillsdev/libpalaso/338#-K8PfTZEDZmIYPJklcJZ:-K8V5K4DORVcv5bn0mIl:1087844720) ([raw file](https://github.com/sillsdev/libpalaso/blob/02a894bdf1b4991be982e4c6d77e310a28f0aa9a/Palaso.Tests/UsbDrive/UsbDeviceInfoTests.cs#L172)):*
Right. We can refine it more, like maybe if VolumeLabel is null or empty, we could Assert.Ignore and then at least the test can still be usable for someone working in the USB drive area. I see that your later commit smooths out some of this so maybe that will take care of such things.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sillsdev/libpalaso/338)*

**Comment by marksvc** [comment]
So I either don't have access to or don't know how to accept the PR. So at this point maybe you can accept the PR if you are able to do that.

**Pull request merged**
