### PR TITLE
BL-5464 improve internationalization of credits dialog

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/596)

### CODE REVIEW

**Comment by gmartin7** [comment]
Probably works... maybe you could add a (by hand) test to MetaDataEditorControlTests that fills in some labels with the Spanish versions to see how they fit? There are several tests in that file with: "[Test, Ignore("By Hand")]".

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs, line 248 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/596#-L3F6MMqZjMRl5iEJtpg:-L3F6MMqZjMRl5iEJtph:b-98ry0j) ([raw file](https://github.com/sillsdev/libpalaso/blob/cc74d7704cacf0023823fa7ac288d3fdee6962c4/SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs#L248)):*
> ```Smalltalk
> 			// _unknownLicense
> 			// 
> 			this._unknownLicense.AutoSize = true;
> ```

Are you sure you don't want this to AutoSize (e.g. to the right)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/596#-:-L3F6vlG4xU7GN9vhXgN:b-f8f7o9)*

**Comment by JohnThomson** [comment]
I could, but it's pretty easy to test it with LOTS of real, current localizations by just installing the DLL into Bloom...maybe I'm just being lazy, but it doesn't seem worth it.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs, line 248 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/596#-L3F6MMqZjMRl5iEJtpg:-L3FAbWd7LVNotdm0OuS:b-4norqm) ([raw file](https://github.com/sillsdev/libpalaso/blob/cc74d7704cacf0023823fa7ac288d3fdee6962c4/SIL.Windows.Forms/ClearShare/WinFormsUI/MetadataEditorControl.Designer.cs#L248)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Are you sure you don't want this to AutoSize (e.g. to the right)?
</blockquote></details>

Yes. Autosize does not allow more than one line of text. That isn't enough for Spanish. I've made it as wide as there is room for, and two lines high.
Now, the second line overlaps the next radio button. But see the screenshot in the issue for how you can kludge the translation to put a couple of extra words over on the right.
I don't know whether people (esp. JohnH) will be happy, but it's a lot easier than figuring out code to move all the lower controls, including things in the parent dialog, when we need two lines. I thought it might be good enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/596#-:-L3FByzCgJYLoxVrmT0U:b-g2n5d2)*

**Comment by papeh** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/596#-:-L3FQ0z0n2vJGLW0PoCG:bnfp4nl)*

**Comment by hatton** [comment]
Didn't pass the pesky UI reviewer.

**Pull request merged**
