### PR TITLE
keyboarding thru flatpak

### PR DESCRIPTION
**Pull request by marksvc**
===
Along with a needed ibusdotnet change, this should make keyboarding work in flatpak when the host is running Gnome on Ubuntu.

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127)

### CODE REVIEW

**Comment by marksvc** [comment]
I wouldn't think the TC pre-merge failure (SIL.Windows.Forms.Tests.ImageToolbox.ImageGallery.ImageCollectionManagerTests.GetMatchingPictures_FindsMatchesOnMultipleIndonesianWords) is from this PR.

**Review by papeh — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-:-Mv_9qzxCf1r0zYaqlBk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @marksvc)

___
*[SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs, line 53 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-Mv_7DG0C39C2myFTvgf:-Mv_7DG0C39C2myFTvgg:bhtg3fk) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs#L53)):*
> ```Smalltalk
> 			} else {
> 				startInfo.FileName = "/usr/bin/setxkbmap";
> 			}
> ```

nit: this is just a little more boilerplate code than I prefer
___
*[SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs, line 61 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-Mv_9Hsv4rtyOxtc5un6:-Mv_9Hsv4rtyOxtc5un7:b-wxzlgq) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs#L61)):*
> ```Smalltalk
> 		[TestCase("()\n", new string[] {}, TestName = "Handles unexpected input 4")]
> 		[TestCase("\n", new string[] {}, TestName = "Handles unexpected input 5")]
> 		[TestCase("", new string[] {}, TestName = "Handles unexpected input 6")]
> ```

I think these tests would be better without `TestName = "Handles . . . #"`

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127)* status: 3 of 6 files reviewed, 5 unresolved discussions (waiting on @ermshiperete and @papeh)

___
*[SIL.Core/PlatformUtilities/Platform.cs, line 351 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-MvdCJda7Wnu-Kib-Tac:-MvdwJrf0iItqLxhElkQ:b-vt1gyi) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Core/PlatformUtilities/Platform.cs#L351)):*
Hmm. What do you mean? I see that Platform.DesktopEnvironment has logic to take account of a situation where there is some indication for Gnome and other indication for Cinnamon. Do you mean that we might be "running Gnome" but it's actually Cinnamon? I don't suppose you mean Gnome 2.

> might be better to change the caller

There is keyboarding code that wants to interact specifically with Gnome Shell, so it makes sense for it to query if Gnome Shell is the currently running desktop. (Or.. I guess it also depends on what you mean by "run Gnome but not Gnome Shell".)

BTW , in a flatpak in Wasta 18.04 running Cinnamon, I see environment settings like
DESKTOP_SESSION=cinnamon
XDG_SESSION_DESKTOP=cinnamon
XDG_CURRENT_DESKTOP=X-Cinnamon
DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
GDMSESSION=cinnamon
(and `env|grep -i gnome` doesn't report anything as interesting).

In a flatpak in Ubuntu 20.04 running Gnome Shell, I see environment settings like
XDG_MENU_PREFIX=gnome-
GNOME_SHELL_SESSION_MODE=ubuntu
XDG_CURRENT_DESKTOP=ubuntu:GNOME
___
*[SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs, line 53 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-Mv_7DG0C39C2myFTvgf:-Mve-1RT50DB7hI6DXqY:b-3bnels) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Windows.Forms.Keyboarding/Linux/CombinedIbusKeyboardSwitchingAdaptor.cs#L53)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

nit: this is just a little more boilerplate code than I prefer
</blockquote></details>

I have a hard time making this elegant :). How about this variant?
___
*[SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs, line 102 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-MvdEPlrCW_poJUU6noc:-Mve-_wk-pGwYWi957Px:bx9cgk0) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Windows.Forms.Keyboarding/Linux/UnityKeyboardRetrievingHelper.cs#L102)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Might be better to directly call `GnomeInputSourcesViaFlatpakPortal()` if `Platform.IsFlatpak`.
</blockquote></details>

Done. I was leaving the door open in case using gsettings spontaneously started working :)
___
*[SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs, line 52 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-MvdGdpG1weQnMorCZYX:-Mve0TYTCF0s_xHIWbT6:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs#L52)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

can we put this testcase on multiple lines, please? Makes it easier reading on GH for example.
</blockquote></details>

Done.
___
*[SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs, line 61 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-Mv_9Hsv4rtyOxtc5un6:-Mve0cEXB6vpmXoAkruu:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Windows.Forms.Keyboarding.Tests/UnityKeyboardRetrievingHelperTests.cs#L61)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I think these tests would be better without `TestName = "Handles . . . #"`
</blockquote></details>

Done.

**Comment by marksvc** [comment]
I added a +semver:minor

**Review by ermshiperete — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127)* status: all files reviewed, 3 unresolved discussions (waiting on @marksvc and @papeh)

___
*[SIL.Core/PlatformUtilities/Platform.cs, line 351 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-MvdCJda7Wnu-Kib-Tac:-MvhBeGD51uzsO5jRpxE:b2og71v) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Core/PlatformUtilities/Platform.cs#L351)):*
<details><summary><i>Previously, marksvc wrote…</i></summary><blockquote>

Hmm. What do you mean? I see that Platform.DesktopEnvironment has logic to take account of a situation where there is some indication for Gnome and other indication for Cinnamon. Do you mean that we might be "running Gnome" but it's actually Cinnamon? I don't suppose you mean Gnome 2.

> might be better to change the caller

There is keyboarding code that wants to interact specifically with Gnome Shell, so it makes sense for it to query if Gnome Shell is the currently running desktop. (Or.. I guess it also depends on what you mean by "run Gnome but not Gnome Shell".)

BTW , in a flatpak in Wasta 18.04 running Cinnamon, I see environment settings like
DESKTOP_SESSION=cinnamon
XDG_SESSION_DESKTOP=cinnamon
XDG_CURRENT_DESKTOP=X-Cinnamon
DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
GDMSESSION=cinnamon
(and `env|grep -i gnome` doesn't report anything as interesting).

In a flatpak in Ubuntu 20.04 running Gnome Shell, I see environment settings like
XDG_MENU_PREFIX=gnome-
GNOME_SHELL_SESSION_MODE=ubuntu
XDG_CURRENT_DESKTOP=ubuntu:GNOME


</blockquote></details>

I think there are other kinds of [login sessions](https://en.wikipedia.org/wiki/GNOME#GNOME_Classic) besides Gnome Shell, like Gnome Classic and Gnome Flashback. I'd hate if `IsGnomeShell` would return true in those cases.

**Review by marksvc — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @ermshiperete and @papeh)

___
*[SIL.Core/PlatformUtilities/Platform.cs, line 351 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-MvdCJda7Wnu-Kib-Tac:-Mw7rdWuC-zmRQQQxphC:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/11c38cb01e5a9ca6d1178fb5469f34cd2088ece2/SIL.Core/PlatformUtilities/Platform.cs#L351)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I think there are other kinds of [login sessions](https://en.wikipedia.org/wiki/GNOME#GNOME_Classic) besides Gnome Shell, like Gnome Classic and Gnome Flashback. I'd hate if `IsGnomeShell` would return true in those cases.
</blockquote></details>

Done.

**Comment by marksvc** [comment]
The PR continues to distinguish Gnome Flashback from Gnome Shell. But it now considers that running Gnome Classic means we are running Gnome Shell. 
When I look into what Gnome Classic is, it seems that it's mostly a different set of extensions to run in Gnome Shell. 
@ermshiperete if you still don't want Gnome Classic to cause IsGnomeShell==true, we can go back to Gnome Classic resulting in IsGnomeShell==false. Tho in that situation, every use of `IsGnomeShell` in libpalaso Keyboarding and the one use in FieldWorks needs changed to essentially `(IsGnomeShell || IsGnomeClassic)` for keyboarding to work. We can chat more about it.

**Review by ermshiperete — APPROVED** [review]
:lgtm:

**Review by ermshiperete — CHANGES_REQUESTED** [review]
Actually, the two new `Platform` properties should get an entry in `CHANGELOG.md`, and the commit message should have `+semver:minor`. Otherwise :lgtm: 

> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-:-MwXEJwQ2XSbvsftLmxu:b-nx12kq)* status: all files reviewed, 2 unresolved discussions (waiting on @papeh)

**Review by ermshiperete — APPROVED** [review]
Ahh, this is for libpalaso-6.0. So forget my previous comment :smile: 

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-:-MwXEqdmDIfMEl3WRSiI:br4k0pu)* status: all files reviewed, 2 unresolved discussions (waiting on @papeh)

**Comment by ermshiperete** [comment]
Should be cherry-picked to `master` (with the proper `CHANGELOG.md` entry :smile: )

**Review by marksvc — COMMENTED** [review]
@ermshiperete So adding `+semver:minor` may not matter here then, but for future reference:  I did put a `+semver:minor` in one of the commits in the series, which was the "keyboarding: work in flatpak in Gnome". Is it important that each commit in a PR, which does something version-bump-worthy, be marked with `+semver:minor`, or is it only important that one commit in a PR contain it? 
I suppose after rebasing a PR to the target, a release could happen from a commit in the middle of the recent commits, and thus miss out on a `+semver:minor` marker. But it also seems like having multiple `+semver:minor` markers in a series of commits in a PR will needlessly increase the version number by more than 1. (like from 6.1 to 6.4, if I had 3x `+semver:minor`markers)

There will probably be a few things that will be good to merge to master from libpalaso-6.0.

> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1127#-:-MwcjLZo3dQy05glhkyr:b9nucrn)* status: all files reviewed, 2 unresolved discussions (waiting on @papeh)

**Comment by ermshiperete** [comment]
@marksvc I think every commit that does something version-bump-worthy should be marked for documentation purposes. Having multiple `+semver:minor/+semver:major` tags won't affect the version number. The version will get increased only by 1, regardless of the number of tags. Only after we create a release (instead of a pre-release) the version will get bumped again.

**Comment by marksvc** [comment]
@ermshiperete Okay, thank you.

**Pull request merged**
