### PR TITLE
Support Keyman10 Keyboard Switching

### PR DESCRIPTION
**Pull request by jasonleenaylor**
* Refactor KeyboardSwitchingAdapter
* Implement new adapter for KM 10

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/627)

### CODE REVIEW

**Comment by jasonleenaylor** [comment]
This is something of a WIP - It lets me switch in the TestApp but I haven't had success integrating this into FLEx yet.

**Comment by ermshiperete** [comment]
A few comments.

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 364 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aZSGGz9NfLQD0nVv-:-L6aZSGGz9NfLQD0nVv0:b-60lpb) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L364)):*
> ```Smalltalk
> 		#region IKeyboardSwitchingAdaptor Members
> 
> 		private class LegacyKeymanKeyboardSwitchingAdapter : IKeyboardSwitchingAdaptor
> ```

Move to separate file?

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 459 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aZWMGIP8RID7fAXEb:-L6aZWMGIP8RID7fAXEc:b-60lpb) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L459)):*
> ```Smalltalk
> 		}
> 
> 		private class KeymanKeyboardSwitchingAdapter : IKeyboardSwitchingAdaptor
> ```

Move to separate file?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 14 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aJdQUt4zSwhd5ObfD:-L6aJdQV0pn2JfE7QTLb:b-uuxqcb) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L14)):*
> ```Smalltalk
> 	/// This keyboard switching adapter handles windows keyboard switching using the modern api as well as falling back to old win API for XP.
> 	/// </summary>
> 	internal class WindowsXPKeyboardSwitchingAdapter : IKeyboardSwitchingAdaptor, IDisposable
> ```

The name suggests that this is only relevant for XP, but the comment shows that it's probably also used on modern Windows. Maybe a better name would then be to drop the XP? `WindowsKeyboardSwitchingAdapter`?

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 113 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aKfP5XO68AEb5p14C:-L6aKfP5XO68AEb5p14D:b99yt4n) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L113)):*
> ```Smalltalk
> 		}
> ```

nit-pick: extra empty line

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 145 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aLihLy1dyoG3b55rP:-L6aLihLy1dyoG3b55rQ:ba4a9o2) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L145)):*
> ```Smalltalk
> 
> 				var profile = winKeyboard.InputProcessorProfile;
> 				if ((profile.Flags & TfIppFlags.Enabled) == 0)
> ```

I know I originally wrote this code. But now I couldn't make immediate sense out of it, maybe a comment would be helpful. Something like: profile disabled, will be handled in...

Unfortunately I don't remember under what circumstances a profile is disabled and if we entirely ignore it then or if this means that the switching/activating is done elsewhere.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 271 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aRDtmzdCNnZu6Uf_1:-L6aRDtmzdCNnZu6Uf_2:bo1e2i8) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L271)):*
> ```Smalltalk
> 		public void Dispose()
> 		{
> 			Timer?.Dispose();
> ```

That's missing`GC.SuppressFinalize(this);`

Also, I personally would prefer if we'd follow the [dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern) - although I agree that's debatable in this case. If we don't implement the dispose pattern we should make the class `sealed`.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 25 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aTZsMpEyB9GQ6j-7o:-L6aTZsMpEyB9GQ6j-7p:bv14x1k) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L25)):*
> ```Smalltalk
> 		/// e.g. on Windows XP.
> 		/// </summary>
> 		private class TfLanguageProfileNotifySink : ITfLanguageProfileNotifySink
> ```

It seems to me that this class should be in `WindowsXPKeyboardSwitchingAdapter` since it's more related with keyboard switching than retrieval.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 355 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aVjoAixKWuPepgsTm:-L6aVjoAixKWuPepgsTn:b-jbsq4p) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L355)):*
> ```Smalltalk
> 			foreach (var existingKeyboard in curKeyboards.Values)
> 			{
> 				existingKeyboard.SetIsAvailable(false);
> ```

Is this necessary? I'd have thought that they start with `IsAvailable == false`

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardUtils.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aWJJJXi8v3ykDWcco:-L6aWJJJXi8v3ykDWccp:bhogofg) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardUtils.cs#L13)):*
> ```Smalltalk
> namespace SIL.Windows.Forms.Keyboarding.Windows
> {
> 	internal class LayoutName
> ```

Put this class in a separate file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-:-L6a_Ie5CRz5ZTRq6BhI:b-804dua)*

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 145 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aLihLy1dyoG3b55rP:-L6bjfEPYUuj8fG0ot9G:b-s8v0tf) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L145)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I know I originally wrote this code. But now I couldn't make immediate sense out of it, maybe a comment would be helpful. Something like: profile disabled, will be handled in...

Unfortunately I don't remember under what circumstances a profile is disabled and if we entirely ignore it then or if this means that the switching/activating is done elsewhere.
</blockquote></details>

I have no idea, after fighting with this for 2 days to try and make it re-usable with Keyman10 keyboards I finally gave up and used a different much simpler method.  I can't add a comment because I don't understand it enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 14 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aJdQUt4zSwhd5ObfD:-L6bk6Fr-dHmZfQvjn_1:btcivpc) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L14)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

The name suggests that this is only relevant for XP, but the comment shows that it's probably also used on modern Windows. Maybe a better name would then be to drop the XP? `WindowsKeyboardSwitchingAdapter`?
</blockquote></details>

Yes, I was working on having a WindowsKeyboardSwitchingAdapter that this class would extend but I didn't follow through on that idea when I couldn't use this class successfully with Keyman. I've renamed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 355 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aVjoAixKWuPepgsTm:-L6bkOnQ2UC8feRksKVf:b-s37tx2) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L355)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Is this necessary? I'd have thought that they start with `IsAvailable == false`
</blockquote></details>

I don't know. This is what all the rest of the UpdateAvailableKeyboards did so I assumed I needed to follow suit.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by jasonleenaylor** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 113 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aKfP5XO68AEb5p14C:-L6bk4rmBDaHfF84zP3t:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L113)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

nit-pick: extra empty line
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs, line 271 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aRDtmzdCNnZu6Uf_1:-L6bjesdeyClBi8YLd5W:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WindowsXPKeyboardSwitchingAdapter.cs#L271)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

That's missing`GC.SuppressFinalize(this);`

Also, I personally would prefer if we'd follow the [dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/dispose-pattern) - although I agree that's debatable in this case. If we don't implement the dispose pattern we should make the class `sealed`.
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 25 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aTZsMpEyB9GQ6j-7o:-L6bkbFwiHM6M5yXmbvJ:b3fa1vp) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L25)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

It seems to me that this class should be in `WindowsXPKeyboardSwitchingAdapter` since it's more related with keyboard switching than retrieval.
</blockquote></details>

I moved it to its own file instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 355 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aVjoAixKWuPepgsTm:-L6bws9ISnbl8I3MIc7G:bek5675) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L355)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I don't know. This is what all the rest of the UpdateAvailableKeyboards did so I assumed I needed to follow suit.
</blockquote></details>

Oh! actually this is a bug. This didn't need to be here. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by jasonleenaylor** [comment]
So this appears to be working with FLEx, there is one test failing in the Keyboard area that I haven't fixed yet. However, it already fails on master. I'm not sure if it is valid.

`public void ActivateDefaultKeyboard_ActivatesDefaultInputLanguage()`

**Comment by jasonleenaylor** [comment]
*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 25 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aTZsMpEyB9GQ6j-7o:-L6cbHcfFZGPGpebOzPB:bn6vwbm) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L25)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I moved it to its own file instead.
</blockquote></details>

I reconsidered and put it and the other related code into the switching adapter

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by jasonleenaylor** [comment]
Review status: 4 of 13 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardUtils.cs, line 13 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aWJJJXi8v3ykDWcco:-L6cbQ2e-czqor-mCAUd:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardUtils.cs#L13)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Put this class in a separate file?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by mcdurdin** [comment]
Review status: 4 of 13 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 258 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6obkDD5BWeXsY0Qe5k:-L6obkDEP2oCadsolHZN:b-u9mywb) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L258)):*
> ```Smalltalk
> 			{
> 				case KeymanVersion.Keyman10:
> 					string[] parts = id.Split('_');
> ```

This should probably be refactored into a helper function since we do it more than once -- it'd also be good to clarify why we are doing it.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 331 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6obun7_FqtXuGTU-wU:-L6obun7_FqtXuGTU-wV:b-txon70) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L331)):*
> ```Smalltalk
> 			using (var olderKeyman = Registry.LocalMachine.OpenSubKey(@"Software\Tavultesoft\Keyman", false))
> 			using (var keyman10_32 = Registry.LocalMachine.OpenSubKey(@"Software\WOW6432Node\Keyman\Keyman Desktop", false))
> 			using (var older32Keyman = Registry.LocalMachine.OpenSubKey(@"Software\WOW6432Node\Tavultesoft\Keyman", false))
> ```

Perhaps rename the variables `olderKeyman` and `older32Keyman` to match the `keyman10` pattern?  `keyman6to9`?

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs, line 18 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6nvRNDusRLMnmnaofV:-L6nvRNE6X2Ys5qEpiwr:ba6brxg) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs#L18)):*
> ```Smalltalk
> 			foreach (InputLanguage lang in InputLanguage.InstalledInputLanguages)
> 			{
> 				if (keyboard.InputLanguage.Culture.EnglishName == lang.Culture.EnglishName)
> ```

Why comparing by `EnglishName` instead of `.Name?

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs, line 41 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6nw4v8MEIkOcZzpMwk:-L6nw4v8MEIkOcZzpMwl:bb81qtk) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs#L41)):*
> ```Smalltalk
> 			{
> 				throw new NotImplementedException(
> 					"Keyman keyboards that are not associated with a language are never the system default.");
> ```

Conceptually in Keyman 10 a keyboard is only available for use if it is associated with a Windows language. I'm not sure if the error message is accurate

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 369 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6oaq4rCbQyh5FcH-Jk:-L6oaq4rCbQyh5FcH-Jl:bcdyill) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L369)):*
> ```Smalltalk
> 			{
> 				// In my tests we never hit this method (Windows 8.1). I don't know if the
> 				// method signature is wrong or why that is.
> ```

I believe this is the case because the Win8 language switcher replaces the TSF language bar which issued this event. In the Win8 language switch model, there is no pathway to decline a language switch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by ermshiperete** [comment]
Reviewed 9 of 10 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 355 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aVjoAixKWuPepgsTm:-L6pGf_7B_NtPxFlHDIM:b-c634e6) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L355)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

Oh! actually this is a bug. This didn't need to be here. Thanks!
</blockquote></details>

Ehhm - I still see it here!? :confused: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by jasonleenaylor** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 364 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aZSGGz9NfLQD0nVv-:-L6rZ6CgKl7iW8xNZK3d:b-ws2k8r) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L364)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Move to separate file?
</blockquote></details>

The region was left over from the switching adapter extraction, and the CanHandleFormat was in the wrong section.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 459 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aZWMGIP8RID7fAXEb:-L6rZumKIzY97rGqxy0H:bg6g6o4) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L459)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Move to separate file?
</blockquote></details>

it belongs here as part of the IKeyboardRetrievingAdapter interface

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 258 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6obkDD5BWeXsY0Qe5k:-L6rXyu-nPEtz0CH4lZ5:bkjdw0f) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L258)):*
<details><summary><i>Previously, mcdurdin (Marc Durdin) wrote…</i></summary><blockquote>

This should probably be refactored into a helper function since we do it more than once -- it'd also be good to clarify why we are doing it.
</blockquote></details>

Extracted a method and put it in KeyboardController. I've only moved this code around, I didn't invent it. I called the method GetLayoutAndLocaleFromLanguageId but I didn't look up why this is the right way to do that. Let me know if we need to add a comment, or @ermshiperete can chip in since I think he was the original author if this code.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs, line 331 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6obun7_FqtXuGTU-wU:-L6rYmJzLJvkMNCp7Svb:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardAdaptor.cs#L331)):*
<details><summary><i>Previously, mcdurdin (Marc Durdin) wrote…</i></summary><blockquote>

Perhaps rename the variables `olderKeyman` and `older32Keyman` to match the `keyman10` pattern?  `keyman6to9`?
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs, line 18 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6nvRNDusRLMnmnaofV:-L6rUGOSlSpbzJRFeiCE:b1ldbiu) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs#L18)):*
<details><summary><i>Previously, mcdurdin (Marc Durdin) wrote…</i></summary><blockquote>

Why comparing by `EnglishName` instead of `.Name?
</blockquote></details>

No good reason, changed it.

---

*[SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs, line 41 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6nw4v8MEIkOcZzpMwk:-L6rUFkKhFvh-JoJROb8:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/KeymanKeyboardSwitchingAdapter.cs#L41)):*
<details><summary><i>Previously, mcdurdin (Marc Durdin) wrote…</i></summary><blockquote>

Conceptually in Keyman 10 a keyboard is only available for use if it is associated with a Windows language. I'm not sure if the error message is accurate
</blockquote></details>

Done.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 369 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6oaq4rCbQyh5FcH-Jk:-L6rZUSd43-x1kK0713d:bytlkxi) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L369)):*
<details><summary><i>Previously, mcdurdin (Marc Durdin) wrote…</i></summary><blockquote>

I believe this is the case because the Win8 language switcher replaces the TSF language bar which issued this event. In the Win8 language switch model, there is no pathway to decline a language switch.
</blockquote></details>

I'll modify this comment to reflect this information.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs, line 355 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6aVjoAixKWuPepgsTm:-L6rZon8vZ6P5QPTTmAY:b-os8fkm) ([raw file](https://github.com/sillsdev/libpalaso/blob/d83a57a309a39012d1f5739c9e2f54fa6bbdefee/SIL.Windows.Forms.Keyboarding/Windows/WinKeyboardAdaptor.cs#L355)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Ehhm - I still see it here!? :confused: 
</blockquote></details>

Er, I removed it from somewhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r2, 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs, line 369 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-L6oaq4rCbQyh5FcH-Jk:-L6uc9aeO9J0uIdOP4ns:b-8fx2u7) ([raw file](https://github.com/sillsdev/libpalaso/blob/977941ef9c8d92a23bc83a1ea1aba120371cbb5d/SIL.Windows.Forms.Keyboarding/Windows/WindowsKeyboardSwitchingAdapter.cs#L369)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

I'll modify this comment to reflect this information.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/627#-:-L6uceU4W9ac_7cZnX4T:bnfp4nl)*

**Pull request merged**
