### PR TITLE
Log stderr as message by default in unit tests

### PR DESCRIPTION
**Pull request by glasseyes**
"The standard error stream is the default destination for
  error messages and other diagnostic warnings."

By default log the message as it is most likely a warning.
If the stderr message includes error, crash or fail then log it as an
error and investigate. Change this if it is too broad.

This addresses [issue 635](https://github.com/sillsdev/libpalaso/issues/635)

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/636)

### CODE REVIEW

**Comment by ermshiperete** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 293 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L78dh1dBGS49SiOkYFd:-L78dh1euuBbvT5AQipd:b2ibeid) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L293)):*
> ```Smalltalk
> 					}
> 
> 					bool logError = false;
> ```

We still want to output the messages/errors only if `Verbose` is true. If `Verbose` is false `logContents` gets added to `m_TestLog` and output after the tests are finished.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636)*

**Comment by glasseyes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 293 at r1](https://beta.reviewable.io/reviews/sillsdev/libpalaso/636#-L78dh1dBGS49SiOkYFd:-L78iwMI-owdpttwABqW:b-dtd46d) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L293)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

We still want to output the messages/errors only if `Verbose` is true. If `Verbose` is false `logContents` gets added to `m_TestLog` and output after the tests are finished.
</blockquote></details>

`StreamReaderThread_Output` doesn't depend on `Verbose` being true. How is it different?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/sillsdev/libpalaso/636)*

**Comment by ermshiperete** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 293 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L78dh1dBGS49SiOkYFd:-L78nmCZKUIs51umWarH:buklacb) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L293)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

`StreamReaderThread_Output` doesn't depend on `Verbose` being true. How is it different?
</blockquote></details>

You're right! That doesn't have it. Looks like a bug in either `StreamReaderThread_Output` or in the comment of `Verbose`. I'd suggest changing the comment on `Verbose`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636)*

**Comment by ermshiperete** [comment]
#637 adds some unit tests (and fixes one previously ignored one). It shows that this change should work.

#637 has two ignored tests that can be enabled once this PR is merged.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-:-L79Tu8LdCeLGkTAfulV:b-6g0e6s)*

**Comment by ermshiperete** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-:-L79UBgGoO8_LghLFV1U:bnfp4nl)*

**Comment by papeh** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 308 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L7BGUBTDaD31Q1lAiDs:-L7BGUBTDaD31Q1lAiDt:b4jcx6) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L308)):*
> ```Smalltalk
> 					}
> 
> 					if (logError)
> ```

`if ({ "error", "crash", "fail" }.Any(err => logContents.Contains(err, OrdIgnCase)))`?

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 314 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L7BIEL6IW-zvo2N--Fk:-L7BIEL6IW-zvo2N--Fl:b-q4fyym) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L314)):*
> ```Smalltalk
> 					else
> 					{
> 						Log.LogMessage(MessageImportance.High, logContents);
> ```

LogWarning?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636)*

**Comment by glasseyes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 293 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L78dh1dBGS49SiOkYFd:-L7NB2MQo94Qee6JDeNT:b-qnua7l) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L293)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

You're right! That doesn't have it. Looks like a bug in either `StreamReaderThread_Output` or in the comment of `Verbose`. I'd suggest changing the comment on `Verbose`.
</blockquote></details>

I changed both to only output messages/warnings if Verbose but to log the error (to cause the build to fail) if it thinks it's an error

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 308 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L7BGUBTDaD31Q1lAiDs:-L7NBvbVx8JpguVRYdPd:b-6ph1u5) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L308)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

`if ({ "error", "crash", "fail" }.Any(err => logContents.Contains(err, OrdIgnCase)))`?
</blockquote></details>

Done. Though `{ "error", "crash", "fail" }.Any` didn't compile so I put it in a variable

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 314 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L7BIEL6IW-zvo2N--Fk:-L7N8e8k1qZpIDsRAF8R:bdaek36) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L314)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

LogWarning?
</blockquote></details>

good point

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636)*

**Comment by papeh** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 308 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L7BGUBTDaD31Q1lAiDs:-L7QdciqLAFitDMrtQZh:bj4gjod) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L308)):*
<details><summary><i>Previously, glasseyes wrote…</i></summary><blockquote>

Done. Though `{ "error", "crash", "fail" }.Any` didn't compile so I put it in a variable
</blockquote></details>

Could you help me understand why we're using `IndexOf >= 0` instead of `Contains`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-:-L7Qdzm5irV83-4MZPrx:bnfp4nl)*

**Comment by glasseyes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[SIL.BuildTasks/UnitTestTasks/TestTask.cs, line 308 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/636#-L7BGUBTDaD31Q1lAiDs:-L7S55E-WDxybxlNDXxw:bbmf1s2) ([raw file](https://github.com/sillsdev/libpalaso/blob/ffc76c7e8a4a39bdac61fa31db9e79f00cf3c32c/SIL.BuildTasks/UnitTestTasks/TestTask.cs#L308)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

Could you help me understand why we're using `IndexOf >= 0` instead of `Contains`?
</blockquote></details>

That is a reasonable question. In `SIL.Core` there is a StringExtension that allows you to pass in a `StringComparison` to use in `Contains`. But `SIL.BuildTasks` doesn't use `SIL.Core`. It doesn't depend on any of the SIL dlls. So we have to use `IndexOf >= 0` there 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/636)*

**Pull request merged**
