### PR TITLE
run writingsystem tests against dotnet 8

### PR DESCRIPTION
**Pull request by hahn-kev**
There's a bug when using SIL.WritingSystems from a dotnet 8 app, but only when you explicitly reference icu.net from that app.

This PR adds a test to expose that issue, while also fixing it by updating the icu.net version. Since this is a dotnet 8 specific issue it also runs the SIL.WritingSystems tests against dotnet 8

Issue explanation: https://github.com/sillsdev/icu-dotnet/pull/202

this replaces PR #1330 which was made on a fork

- - -
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1336)

### CODE REVIEW

**Comment by hahn-kev** [comment]
It looks like a lot of our WritingSystem tests (especially related to sorting) are not expecting dotnet 8 to use ICU natively. To resolve this I went ahead and used a configuration flag so that instead of dotnet using ICU it will use [NLS](https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization#nls) which is what .Net Framework uses, this meets the expectations of our tests. That said many of these tests may be over specified, so we should consider if we want to change them or not.

**Comment by jasonleenaylor** [comment]
*[`SIL.WritingSystems/CultureInfoExtensions.cs` line 15 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1336#-O3t2oYw0lOorStCdEcC:-O3t2oYxBUzFpcX9UV81:b-y3q00w) ([raw file](https://github.com/sillsdev/libpalaso/blob/ee5ba576c0c3a62d994d9aae2c8ae05eee7a1afc/SIL.WritingSystems/CultureInfoExtensions.cs#L15)):*
> ```Smalltalk
> 			// Source: https://stackoverflow.com/a/71388328/1964319
> 			return cultureInfo.CultureTypes.HasFlag(CultureTypes.UserCustomCulture) &&
> 			       cultureInfo.ThreeLetterWindowsLanguageName == "ZZZ";
> ```

So this behaves correctly on Windows 8, and Windows 7?

**Review by jasonleenaylor — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1336)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Comment by hahn-kev** [comment]
*[`SIL.WritingSystems/CultureInfoExtensions.cs` line 15 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1336#-O3t2oYw0lOorStCdEcC:-O4DkrCZDkeTG519GId5:b-f2sxf2) ([raw file](https://github.com/sillsdev/libpalaso/blob/ee5ba576c0c3a62d994d9aae2c8ae05eee7a1afc/SIL.WritingSystems/CultureInfoExtensions.cs#L15)):*
<details><summary><i>Previously, jasonleenaylor (Jason Naylor) wrote…</i></summary><blockquote>

So this behaves correctly on Windows 8, and Windows 7?
</blockquote></details>

from my testing on windows 7 the CultureInfo constructor throws if you try to use an unknown culture, so yeah this will work on windows 7 I suppose since you can't have an invalid instance.

**Comment by hahn-kev** [comment]
@ermshiperete can you see why appveyor is failing? The error looks like it's trying to use dotnet 5, however according to https://www.appveyor.com/docs/windows-images-software/ the Visual Studio 2019 image has dotnet 8 installed, and I can't see anywhere that we've hardcoded dotnet 5 in our build scripts. Addtionally using msbuild on Palaso.proj works fine locally, even when I set CI to true.

**Comment by ermshiperete** [comment]
> @ermshiperete can you see why appveyor is failing? The error looks like it's trying to use dotnet 5, however according to https://www.appveyor.com/docs/windows-images-software/ the Visual Studio 2019 image has dotnet 8 installed, and I can't see anywhere that we've hardcoded dotnet 5 in our build scripts. Addtionally using msbuild on Palaso.proj works fine locally, even when I set CI to true.

`appveyor.yml` specifies "Visual Studio 2019". If I use that locally the build fails with the same error. With VS 2022 things work for me locally.

**Comment by rmunn** [comment]
> `appveyor.yml` specifies "Visual Studio 2019". If I use that locally the build fails with the same error. With VS 2022 things work for me locally.

Ditto. Their docs say that the Visual Studio 2019 image includes the .NET 8 SDK, but in practice I've found that that's false and you need the 2022 image in order for .NET 8 to work. See https://github.com/sillsdev/flexbridge/pull/407 for example.

**Review by jasonleenaylor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1336)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @josephmyers)

**Review by josephmyers — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/1336)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @hahn-kev)

___
*[`SIL.WritingSystems/CultureInfoExtensions.cs` line 15 at r3](https://reviewable.io/reviews/sillsdev/libpalaso/1336#-O3t2oYw0lOorStCdEcC:-O4Jwfl24sW6HC2GyqxM:bv0ay1v) ([raw file](https://github.com/sillsdev/libpalaso/blob/ee5ba576c0c3a62d994d9aae2c8ae05eee7a1afc/SIL.WritingSystems/CultureInfoExtensions.cs#L15)):*
<details><summary><i>Previously, hahn-kev (Kevin Hahn) wrote…</i></summary><blockquote>

from my testing on windows 7 the CultureInfo constructor throws if you try to use an unknown culture, so yeah this will work on windows 7 I suppose since you can't have an invalid instance.
</blockquote></details>

We did the same thing [in L10nSharp], for reference (https://github.com/sillsdev/l10nsharp/pull/118)

**Pull request merged**
