### PR TITLE
Allow clients to change audio device icons to suit their color scheme

### PR DESCRIPTION
**Pull request by hatton**
Also adds and updates some audio device icons

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/547)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 16 of 16 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZXqO4vgjsEtFN9pZu:-KnZXqO4vgjsEtFN9pZv:b-hcg0ig) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L57)):*
> order is important here

"The order of the keys in the Dictionary<TKey, TValue>.KeyCollection is unspecified"

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 230 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZYbvdPfxicy5XWxij:-KnZYbveueMhji8Wt69m:b-ywdabr) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L230)):*
> GetIconForRecodingDevice

GetIconForRecordingDevice

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 248 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZZ-TZKxLlslq_e9Zp:-KnZZ-TZKxLlslq_e9Zq:b6lphqh) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L248)):*
> ```Smalltalk
> 			try
> 			{
> 				System.Diagnostics.Process.Start("control", "mmsys.cpl,,1");
> ```

What does this do? Wants a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZXqO4vgjsEtFN9pZu:-Kn_1MHA0vlXfOP5zNTL:b6xle88) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> order is important here

"The order of the keys in the Dictionary<TKey, TValue>.KeyCollection is unspecified"
</blockquote></details>

thanks. Change to SortedDictionary

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 230 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZYbvdPfxicy5XWxij:-Kn_1Ktd6fbXHXXE_Cek:b-k73z76) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L230)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> GetIconForRecodingDevice

GetIconForRecordingDevice
</blockquote></details>

thanks

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 248 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZZ-TZKxLlslq_e9Zp:-Kn_0Og-jZ3PCrtHT6IB:b-k73z76) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L248)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What does this do? Wants a comment.
</blockquote></details>

thanks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZXqO4vgjsEtFN9pZu:-Kn_28MsjVVmJbmbXwU8:bf3zq2q) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L57)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

thanks. Change to SortedDictionary
</blockquote></details>

I'm pretty sure that do a string sort on the keys since you haven't specified a comparer.
Perhaps replace the strings with an enum? Then the default comparer will be the order you put them in the enum. Also helps clients know what can be set rather than setting via string.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZXqO4vgjsEtFN9pZu:-Kn_2WJN5_A66ODqRYDK:b141wv8) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm pretty sure that do a string sort on the keys since you haven't specified a comparer.
Perhaps replace the strings with an enum? Then the default comparer will be the order you put them in the enum. Also helps clients know what can be set rather than setting via string.
</blockquote></details>

Should read, "I'm pretty sure that will do a string sort..."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZXqO4vgjsEtFN9pZu:-Kn_3tvFRCeYjhbGBM7i:b-gjc7wa) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L57)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Should read, "I'm pretty sure that will do a string sort..."
</blockquote></details>

oh my. I think I should go work on my lawn today...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Comment by hatton** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-KnZXqO4vgjsEtFN9pZu:-Kn_4P8yQH8mAi7-K8iK:b-atc8xp) ([raw file](https://github.com/sillsdev/libpalaso/blob/0f5cfc34f3fe1fe02acb9b52a080e7c348f05cc6/SIL.Media/Naudio/UI/RecordingDeviceIndicator.cs#L57)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

oh my. I think I should go work on my lawn today...
</blockquote></details>

Now uses public properties for the customization, and private List<> to preserve order.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Comment by andrew-polk** [comment]
One accidental push which needs to be reverted.
Otherwise, :lgtm: 

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[SIL.Media/SIL.Media.csproj, line 135 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-Kn_ZZ9xmVP3EdXPRCBV:-Kn_ZZ9xmVP3EdXPRCBW:bb726f6) ([raw file](https://github.com/sillsdev/libpalaso/blob/894e59e70df5a6d3579ddd69f43b1309f0a1be80/SIL.Media/SIL.Media.csproj#L135)):*
> ..\..\HearThis\lib\dotnet\

Oops. Don't think you meant to push this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-:-Kn__PQaBF3eplZtY1yi:b-5h17aw)*

**Comment by hatton** [comment]
Review status: 15 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[SIL.Media/SIL.Media.csproj, line 135 at r3](https://reviewable.io:443/reviews/sillsdev/libpalaso/547#-Kn_ZZ9xmVP3EdXPRCBV:-Kn_xS2Z7g9b5EI2AtZc:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/894e59e70df5a6d3579ddd69f43b1309f0a1be80/SIL.Media/SIL.Media.csproj#L135)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ..\..\HearThis\lib\dotnet\

Oops. Don't think you meant to push this.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Comment by andrew-polk** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/547)*

**Pull request merged**
