### PR TITLE
Improve tests for NUnit task

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/637)

### CODE REVIEW

**Comment by papeh** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks.Tests/SIL.BuildTasks.Tests.Helper/ForceCrash/ForceCrash.c, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/637#-L7Aq6IIla_3O5lV47Bp:-L7Aq6IIla_3O5lV47Bq:bz8e8k3) ([raw file](https://github.com/sillsdev/libpalaso/blob/e65c5f12e9c51c7010befd82844ee1e275dabb15/SIL.BuildTasks.Tests/SIL.BuildTasks.Tests.Helper/ForceCrash/ForceCrash.c#L11)):*
> ```C
> #endif
> 
> void ForceCrash(int *p)
> ```

I would expect a method with this name to crash even if a valid pointer were passed. Could ForceCrash be made to take no arguments? If not, how about `CrashIfInvalidPointer(int *p)`

---

*[SIL.BuildTasks.Tests/UnitTestTasks/NUnitTests.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/637#-L7At-CiZGn0PkyKmVLW:-L7At-CiZGn0PkyKmVLX:b-g3fh4q) ([raw file](https://github.com/sillsdev/libpalaso/blob/e65c5f12e9c51c7010befd82844ee1e275dabb15/SIL.BuildTasks.Tests/UnitTestTasks/NUnitTests.cs#L57)):*
> ```Smalltalk
> 				Directory.CreateDirectory(targetDir);
> 				File.Copy(file, Path.Combine(targetDir, Path.GetFileName(file)));
> 			}
> ```

this seems a bit pricey, but I can't think of a better way

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/637)*

**Comment by glasseyes** [comment]
#636 is now merged

**Comment by ermshiperete** [comment]
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[SIL.BuildTasks.Tests/SIL.BuildTasks.Tests.Helper/ForceCrash/ForceCrash.c, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/637#-L7Aq6IIla_3O5lV47Bp:-L7SfAlIJh9fVH5mCXkr:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/198ef9398057d47b01db5684eacc0fa6c0633b0b/SIL.BuildTasks.Tests/SIL.BuildTasks.Tests.Helper/ForceCrash/ForceCrash.c#L11)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

I would expect a method with this name to crash even if a valid pointer were passed. Could ForceCrash be made to take no arguments? If not, how about `CrashIfInvalidPointer(int *p)`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/637)*

**Comment by ermshiperete** [comment]
Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[SIL.BuildTasks.Tests/UnitTestTasks/NUnitTests.cs, line 57 at r1](https://reviewable.io:443/reviews/sillsdev/libpalaso/637#-L7At-CiZGn0PkyKmVLW:-L7SfqM5ZPYA-IcXGFFy:b-krbbnx) ([raw file](https://github.com/sillsdev/libpalaso/blob/198ef9398057d47b01db5684eacc0fa6c0633b0b/SIL.BuildTasks.Tests/UnitTestTasks/NUnitTests.cs#L57)):*
<details><summary><i>Previously, papeh wrote…</i></summary><blockquote>

this seems a bit pricey, but I can't think of a better way
</blockquote></details>

Yes. The problem is that we don't want the TC addin because that would report the failing tests that we run to test the task as failed tests. Those tests fail intentionally, so we don't want them to be reported as failure of the build.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/637)*

**Comment by glasseyes** [comment]
:lgtm:

---

Review status: 8 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/libpalaso/637#-:-L7T6LIyLD7vUAzO0y1o:bnfp4nl)*

**Pull request merged**
