### PR TITLE
BL-5736 Enable Variants

### PR DESCRIPTION
**Pull request by gmartin7**
* Add a LanguageInfo clone method
* Remove some more old code in LLModel
* Add a manual test of LanguageLookDialog

---
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694)

### CODE REVIEW

**Comment by hatton** [comment]
Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj, line 314 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1pd2j11b2VTd4CoxS:-LB1pd2j11b2VTd4CoxT:b-7ioex4) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj#L314)):*
> ```XML
>       <Name>SIL.Windows.Forms.WritingSystems</Name>
>     </ProjectReference>
>     <ProjectReference Include="..\SIL.Windows.Forms\SIL.Windows.Forms.csproj">
> ```

Can you comment on why this addition is needed?

---

*[SIL.WritingSystems/LanguageInfo.cs, line 37 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1pGwK27lai2EHp8Nh:-LB1pGwK27lai2EHp8Ni:b3mqt6h) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.WritingSystems/LanguageInfo.cs#L37)):*
> ```Smalltalk
> 		/// Special constructor only for use by static CloneLanguageInfo method.
> 		/// </summary>
> 		/// <param name="names"></param>
> ```

I think empty ``<param>`` lines are just noise :-)

---

*[SIL.WritingSystems/LanguageInfo.cs, line 96 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1p3rh8OgaWps3yzdF:-LB1p3rh8OgaWps3yzdG:b-c621r1) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.WritingSystems/LanguageInfo.cs#L96)):*
> ```Smalltalk
> 		{
> 			var newLangInfo =
> 				new LanguageInfo(oldInfo._names, oldInfo._countries)
> ```

Could you instead use https://msdn.microsoft.com/en-us/library/system.object.memberwiseclone(v=vs.110).aspx

so that if a new property is added, this won't fall behind?

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694)*

**Comment by gmartin7** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj, line 314 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1pd2j11b2VTd4CoxS:-LB1rFgR2A8LRSEDAutV:b-qgewie) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.Windows.Forms.WritingSystems.Tests/SIL.Windows.Forms.WritingSystems.Tests.csproj#L314)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Can you comment on why this addition is needed?
</blockquote></details>

Because of the new test which calls the LanguageLookupDialog (used in Bloom's CollectionSettings.ChangeLanguage(), which in turn is based on SIL.Windows.Forms.Miscellaneous.FormForUsingPortableClipboard.

---

*[SIL.WritingSystems/LanguageInfo.cs, line 37 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1pGwK27lai2EHp8Nh:-LB1rto7D2w9FXctHxaB:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.WritingSystems/LanguageInfo.cs#L37)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

I think empty ``<param>`` lines are just noise :-)
</blockquote></details>

Done.

---

*[SIL.WritingSystems/LanguageInfo.cs, line 96 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1p3rh8OgaWps3yzdF:-LB1tw5B3TCiK49ZSaQ5:bbz7lvm) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.WritingSystems/LanguageInfo.cs#L96)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Could you instead use https://msdn.microsoft.com/en-us/library/system.object.memberwiseclone(v=vs.110).aspx

so that if a new property is added, this won't fall behind?
</blockquote></details>

Wonderful idea! But... having .Net version problems...

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694)*

**Comment by andrew-polk** [comment]
Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, line 289 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB20SY27F16XAuUnL2y:-LB20SY27F16XAuUnL2z:bes2dof) ([raw file](https://github.com/sillsdev/libpalaso/blob/3518823f3dfd96e66c038291639e872a8ad22dcd/SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs#L289)):*
> ```Smalltalk
> 				if (dlg.ShowDialog() != DialogResult.OK)
> 					return;
> 				var newLanguageInfo = LanguageInfo.CloneLanguageInfo(_model.SelectedLanguage);
> ```

Deserves a comment stating why we can't use and modify the existing one.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694)*

**Comment by gmartin7** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, line 289 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB20SY27F16XAuUnL2y:-LB2E32uB3h5-Zvmdgax:b-896fix) ([raw file](https://github.com/sillsdev/libpalaso/blob/3518823f3dfd96e66c038291639e872a8ad22dcd/SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs#L289)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Deserves a comment stating why we can't use and modify the existing one.
</blockquote></details>

Done.

---

*[SIL.WritingSystems/LanguageInfo.cs, line 96 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1p3rh8OgaWps3yzdF:-LB2E9lc5oGzo-3PL4Pf:b-n0qmes) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.WritingSystems/LanguageInfo.cs#L96)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Wonderful idea! But... having .Net version problems...
</blockquote></details>

Ah. I just needed to install the .Net Core SDK on my machine... works now!

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694)*

**Comment by andrew-polk** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, line 289 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB20SY27F16XAuUnL2y:-LB2FcbM5a9xH-RqnQpT:b-9ijwus) ([raw file](https://github.com/sillsdev/libpalaso/blob/3518823f3dfd96e66c038291639e872a8ad22dcd/SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs#L289)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If you just need it to call LanguageLookupControl.SelectedLanguageChanged method, you could call that directly.
If you need to actually invoke the event handler, you could do that directly, too.

---

*[SIL.WritingSystems/LanguageInfo.cs, line 96 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1p3rh8OgaWps3yzdF:-LB2H2jpBJvi5PMiH1lC:b-cipa74) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.WritingSystems/LanguageInfo.cs#L96)):*
<details><summary><i>Previously, gmartin7 (Gordon Martin) wrote…</i></summary><blockquote>

Ah. I just needed to install the .Net Core SDK on my machine... works now!
</blockquote></details>

Now that this is one line, I'm not convinced it is worth keeping. But if you are able to make the change I suggested above, this will go away anyway.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694)*

**Comment by gmartin7** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs, line 289 at r2](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB20SY27F16XAuUnL2y:-LB2Mii-CvdMn_PBfLPR:bvvwye3) ([raw file](https://github.com/sillsdev/libpalaso/blob/3518823f3dfd96e66c038291639e872a8ad22dcd/SIL.Windows.Forms.WritingSystems/LanguageLookupControl.cs#L289)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If you just need it to call LanguageLookupControl.SelectedLanguageChanged method, you could call that directly.
If you need to actually invoke the event handler, you could do that directly, too.
</blockquote></details>

OK, yeah, that's simpler. Of course, I learned more stuff in the process, so it's all good!

---

*[SIL.WritingSystems/LanguageInfo.cs, line 96 at r1](https://reviewable.io/reviews/sillsdev/libpalaso/694#-LB1p3rh8OgaWps3yzdF:-LB2KzzBB5az_49Yxxvu:b-87j1qu) ([raw file](https://github.com/sillsdev/libpalaso/blob/c44bcef8a318e04ab039126241ceaecb3f1c9d9e/SIL.WritingSystems/LanguageInfo.cs#L96)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Now that this is one line, I'm not convinced it is worth keeping. But if you are able to make the change I suggested above, this will go away anyway.
</blockquote></details>

Gone.

---


*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694)*

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/sillsdev/libpalaso/694#-:-LB2Nm730QqueRJfnjGH:bnfp4nl)*

**Pull request merged**
